### ISSUE TITLE
Cannot access the file '[..].squirrel-lock-9A162D395BA3F4161595F8A9410AA28527AF740D

### ISSUE THREAD

**Issue by stefanolson** [Squirrel/Squirrel.Windows#1000]
Using version 1.4.4.

I have thousands of users installing software perfectly fine but I have 1 user who can't update or even reinstall from scratch.   There seems to be some sort of a problem with the squirrel lock file but it's very unclear exactly what  the problem is - maybe another installer?   I've had the user reboot his machine which presumably should clear anything that is locked and yet the problem with updating still occurs.   Here's the log after reinstalling,  starting with the uninstall icon. And then straight after that it seems to have a problem deleting a file for no particularly apparent reason.  Any ideas on how to track this down?
2017-04-06 15:22:45> InstallHelperImpl: Couldn't write uninstall icon, don't care: System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.InstallHelperImpl.<CreateUninstallerRegistryEntry>d__5.MoveNext()
2017-04-06 15:22:45> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.IO.IOException: The process cannot access the file 'C:\Users\username\AppData\Local\Temp\.squirrel-lock-9A162D395BA3F4161595F8A9410AA28527AF740D' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at Squirrel.SingleGlobalInstance.<>c__DisplayClass1_0.<.ctor>b__0()
   at Squirrel.Disposable.AnonDisposable.Dispose()
   at Squirrel.SingleGlobalInstance.Dispose()
   at Squirrel.UpdateManager.<>c__DisplayClass31_0.<acquireUpdateLock>b__2()
   at Squirrel.Disposable.AnonDisposable.Dispose()
   at Squirrel.UpdateManager.Dispose()
   at Squirrel.Update.Program.<Install>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.IO.IOException: The process cannot access the file 'C:\Users\username\AppData\Local\Temp\.squirrel-lock-9A162D395BA3F4161595F8A9410AA28527AF740D' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at Squirrel.SingleGlobalInstance.<>c__DisplayClass1_0.<.ctor>b__0()
   at Squirrel.Disposable.AnonDisposable.Dispose()
   at Squirrel.SingleGlobalInstance.Dispose()
   at Squirrel.UpdateManager.<>c__DisplayClass31_0.<acquireUpdateLock>b__2()
   at Squirrel.Disposable.AnonDisposable.Dispose()
   at Squirrel.UpdateManager.Dispose()
   at Squirrel.Update.Program.<Install>d__4.MoveNext()<---

Thanks,
Stefan

**Comment by stefanolson** [comment]
Further information:  Appears as though this happens only on update now.  He can reinstall but not update.

**Comment by Thieum** [comment]
@stefanolson is it still an issue with the current version of Squirrel?

**Comment by stefanolson** [comment]
I haven't been able to upgrade to a later version because the latest version signs ALL the DLLs (vs just exes in 1.4.4), so ends up taking FAR too long to build.  But I can't see any other error reports coming through to my system of recent times so can assume it's a one-off. So I'm happy to close it.
