### ISSUE TITLE
Getting an issue preventing me releasify [System.Exception: File is not a PE image]

### ISSUE THREAD

**Issue by JonZso** [Squirrel/Squirrel.Windows#1034]
Everything was working yesterday but I seem to get a massive error which won't let me move forward with my application anyone witnessed this before?

Squirrel : System.AggregateException: One or more errors occurred. ---> System.Exception: File is not a PE image
At line:1 char:1
+ Squirrel --releasify Installer.2.0.5.nupkg
+ 
    + CategoryInfo          : NotSpecified: (System.Aggregat... not a PE image:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
   at Squirrel.Utility.ExecutableUsesWin32Subsystem(String peImage)
   at Squirrel.Update.Program.<>c.<Releasify>b__10_5(FileInfo x)
   at System.Linq.

Enumerable.<>c__DisplayClass6_0`1.<CombinePredicates>b__0(TSource x)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Concurrent.Partitioner.DynamicPartitionerForIEnumerable`1.InternalPartitionEnumerable.GrabChunk_Buffered(KeyValuePair`2[] destArray, Int32 requestedChunkSize, Int32& actualNumElementsGrabbed)
   at System.Collections.Concurrent.Partitioner.DynamicPartitionerForIEnumerable`1.InternalPartitionEnumerable.GrabChunk(KeyValuePair`2[] destArray, Int32 requestedChunkSize, Int32& actualNumElementsGrabbed)
   at System.Collections.Concurrent.Partitioner.DynamicPartitionerForIEnumerable`1.InternalPartitionEnumerator.GrabNextChunk(Int32 requestedChunkSize)
   at System.Collections.Concurrent.Partitioner.DynamicPartitionEnumerator_Abstract`2.MoveNext()
   at System.Collections.Concurrent.OrderablePartitioner`1.EnumeratorDropIndices.MoveNext()
   at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Squirrel.Update.Program.<>c__DisplayClass10_0.<Releasify>b__2(String pkgPath)
   at Squirrel.ReleasePackage.CreateReleasePackage(String outputFile, String packagesRootDir, Func`2 releaseNotesProcessor, Action`1 contentsPostProcessHook)
   at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon, Boolean generateMsi, String frameworkVersion)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)
---> (Inner Exception #0) System.Exception: File is not a PE image
   at Squirrel.Utility.ExecutableUsesWin32Subsystem(String peImage)
   at Squirrel.Update.Program.<>c.<Releasify>b__10_5(FileInfo x)
   at System.Linq.Enumerable.<>c__DisplayClass6_0`1.<CombinePredicates>b__0(TSource x)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Concurrent.Partitioner.DynamicPartitionerForIEnumerable`1.InternalPartitionEnumerable.GrabChunk_Buffered(KeyValuePair`2[] destArray, Int32 requestedChunkSize, Int32& actualNumElementsGrabbed)
   at System.Collections.Concurrent.Partitioner.DynamicPartitionerForIEnumerable`1.InternalPartitionEnumerable.GrabChunk(KeyValuePair`2[] destArray, Int32 requestedChunkSize, Int32& actualNumElementsGrabbed)
   at System.Collections.Concurrent.Partitioner.DynamicPartitionerForIEnumerable`1.InternalPartitionEnumerator.GrabNextChunk(Int32 requestedChunkSize)
   at System.Collections.Concurrent.Partitioner.DynamicPartitionEnumerator_Abstract`2.MoveNext()
   at System.Collections.Concurrent.OrderablePartitioner`1.EnumeratorDropIndices.MoveNext()
   at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()<---

**Comment by jjeffery** [comment]
I've had something very similar happen to me. I have a new project, to which I have just added Squirrel. I have restarted VS2015. When I try to run squirrel I encounter the following exception. 

```
PM> squirrel --releasify example.1.0.0.nupkg
squirrel : System.AggregateException: One or more errors occurred. ---> System.Exception: File is not a PE image
At line:1 char:1
+ squirrel --releasify example.1.0.0.nupkg
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (System.Aggregat... not a PE image:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
   at Squirrel.Utility.ExecutableUsesWin32Subsystem(String peImage)
   at Squirrel.Update.Program.<>c.<Releasify>b__10_6(FileInfo x)
   at System.Linq.
Enumerable.<>c__DisplayClass6_0`1.<CombinePredicates>b__0(TSource x)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Concurrent.Partitioner.DynamicPartitionerForIEnumerable`1.InternalPartitionEnumerable.GrabChunk_Buffered(KeyValuePair`2[] destArray, 
Int32 requestedChunkSize, Int32& actualNumElementsGrabbed)
   at System.Collections.Concurrent.Partitioner.DynamicPartitionerForIEnumerable`1.InternalPartitionEnumerator.GrabNextChunk(Int32 requestedChunkSize)
   at System.Collections.Concurrent.Partitioner.DynamicPartitionEnumerator_Abstract`2.MoveNext()
   at System.Collections.Concurrent.OrderablePartitioner`1.EnumeratorDropIndices.MoveNext()
   at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Squirrel.Update.Program.<>c__DisplayClass10_1.<Releasify>b__2(String pkgPath)
   at Squirrel.ReleasePackage.CreateReleasePackage(String outputFile, String packagesRootDir, Func`2 releaseNotesProcessor, Action`1 contentsPostProcessHook)
   at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String 
signingOpts, String baseUrl, String setupIcon, Boolean generateMsi, String frameworkVersion, Boolean generateDeltas)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)
---> (Inner Exception #0) System.Exception: File is not a PE image
   at Squirrel.Utility.ExecutableUsesWin32Subsystem(String peImage)
   at Squirrel.Update.Program.<>c.<Releasify>b__10_6(FileInfo x)
   at System.Linq.Enumerable.<>c__DisplayClass6_0`1.<CombinePredicates>b__0(TSource x)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Concurrent.Partitioner.DynamicPartitionerForIEnumerable`1.InternalPartitionEnumerable.GrabChunk_Buffered(KeyValuePair`2[] destArray, 
Int32 requestedChunkSize, Int32& actualNumElementsGrabbed)
   at System.Collections.Concurrent.Partitioner.DynamicPartitionerForIEnumerable`1.InternalPartitionEnumerator.GrabNextChunk(Int32 requestedChunkSize)
   at System.Collections.Concurrent.Partitioner.DynamicPartitionEnumerator_Abstract`2.MoveNext()
   at System.Collections.Concurrent.OrderablePartitioner`1.EnumeratorDropIndices.MoveNext()
   at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()<---
```

**Comment by JKSnd** [comment]
Just a hunch - have you confirmed that the structure of your nupkgs is correct?

**Comment by jjeffery** [comment]
@JKSnd You are probably correct. I had created my nupkg manually, but when I followed the instructions for [Visual Studio Packaging](https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/visual-studio-packaging.md) it worked for me. I have not been back to check the nupkg file I created manually.

**Comment by Thieum** [comment]
@shiftkey issue resolved, this can be closed.
