### ISSUE TITLE
Releasify error when running from a service

### ISSUE THREAD

**Issue by persi12** [Squirrel/Squirrel.Windows#1060]
I made a cakebuild ps script to create my release from octopus. Since squirrel switched to 7z the creation of the delta package fails, it seems it is due to some account authorization issue.

The script works well running from the command line, running from octopus tentacle with the system account I get that:

```

2017-06-12 16:18:35> Program: Starting Squirrel Updater: --releasify C:/Octopus/Applications/Dev/Corpovia.BackOffice/1.7891.0_4/Corpovia_Backoffice_Dev.1.7891.0.nupkg --releaseDir C:/Corpovia/Dev/AppsInstallers/Backoffice --no-msi
2017-06-12 16:18:35> Program: Bootstrapper EXE found at:C:\Octopus\Applications\Dev\Corpovia.BackOffice\1.7891.0_4\DeployConfigs\tools\squirrel.windows\tools\Setup.exe
2017-06-12 16:18:35> Program: Creating release package: C:\Corpovia\Dev\AppsInstallers\Backoffice\Corpovia_Backoffice_Dev.1.7891.0.nupkg
2017-06-12 16:18:35> ReleasePackage: Creating release package: C:\Corpovia\Dev\AppsInstallers\Backoffice\Corpovia_Backoffice_Dev.1.7891.0.nupkg => C:\Corpovia\Dev\AppsInstallers\Backoffice\Corpovia_Backoffice_Dev-1.7891.0-full.nupkg
2017-06-12 16:18:35> ReleasePackage: Extracting dependent packages: []
2017-06-12 16:18:35> ReleasePackage: Removing unnecessary data
2017-06-12 16:18:35> ReleasePackage: No release notes found in C:\Windows\system32\config\systemprofile\AppData\Local\SquirrelTemp\tempa\Corpovia_Backoffice_Dev.nuspec
2017-06-12 16:18:36> Utility: Failed to extract file C:\Corpovia\Dev\AppsInstallers\Backoffice\Corpovia_Backoffice_Dev-1.7891.0-full.nupkg to C:\Windows\system32\config\systemprofile\AppData\Local\SquirrelTemp\tempa
7-Zip [64] 16.04 : Copyright (c) 1999-2016 Igor Pavlov : 2016-10-04

Open archive: C:\Corpovia\Dev\AppsInstallers\Backoffice\Corpovia_Backoffice_Dev-1.7891.0-full.nupkg
--
Path = C:\Corpovia\Dev\AppsInstallers\Backoffice\Corpovia_Backoffice_Dev-1.7891.0-full.nupkg
Type = zip
Physical Size = 6878880

Scanning the drive:
0 files, 0 bytes

Updating archive: C:\Corpovia\Dev\AppsInstallers\Backoffice\Corpovia_Backoffice_Dev-1.7891.0-full.nupkg

Items to compress: 0


Files read from disk: 0
Archive size: 6878880 bytes (6718 KiB)

Scan WARNINGS for files and folders:

 : Le chemin d'accès spécifié est introuvable. (path not found)
----------------
Scan WARNINGS: 1


WARNING: Le chemin d'accès spécifié est introuvable. (path not found)
2017-06-12 16:18:36> Unhandled exception: System.AggregateException: Une ou plusieurs erreurs se sont produites. ---> System.Exception: 7-Zip [64] 16.04 : Copyright (c) 1999-2016 Igor Pavlov : 2016-10-04

Open archive: C:\Corpovia\Dev\AppsInstallers\Backoffice\Corpovia_Backoffice_Dev-1.7891.0-full.nupkg
--
Path = C:\Corpovia\Dev\AppsInstallers\Backoffice\Corpovia_Backoffice_Dev-1.7891.0-full.nupkg
Type = zip
Physical Size = 6878880

Scanning the drive:
0 files, 0 bytes

Updating archive: C:\Corpovia\Dev\AppsInstallers\Backoffice\Corpovia_Backoffice_Dev-1.7891.0-full.nupkg

Items to compress: 0


Files read from disk: 0
Archive size: 6878880 bytes (6718 KiB)

Scan WARNINGS for files and folders:

 : Le chemin d'accès spécifié est introuvable.
----------------
Scan WARNINGS: 1


WARNING: Le chemin d'accès spécifié est introuvable. (path not found)
   à Squirrel.Utility.<CreateZipFromDirectory>d__23.MoveNext()
   --- Fin de la trace de la pile d'exception interne ---
   à System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   à System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   à System.Threading.Tasks.Task.Wait()
   à Squirrel.ReleasePackage.CreateReleasePackage(String outputFile, String packagesRootDir, Func`2 releaseNotesProcessor, Action`1 contentsPostProcessHook)
   à Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon, Boolean generateMsi, String frameworkVersion, Boolean generateDeltas)
   à Squirrel.Update.Program.executeCommandLine(String[] args)
   à Squirrel.Update.Program.main(String[] args)
---> (Exception interne #0) System.Exception: 7-Zip [64] 16.04 : Copyright (c) 1999-2016 Igor Pavlov : 2016-10-04

Open archive: C:\Corpovia\Dev\AppsInstallers\Backoffice\Corpovia_Backoffice_Dev-1.7891.0-full.nupkg
--
Path = C:\Corpovia\Dev\AppsInstallers\Backoffice\Corpovia_Backoffice_Dev-1.7891.0-full.nupkg
Type = zip
Physical Size = 6878880

Scanning the drive:
0 files, 0 bytes

Updating archive: C:\Corpovia\Dev\AppsInstallers\Backoffice\Corpovia_Backoffice_Dev-1.7891.0-full.nupkg

Items to compress: 0


Files read from disk: 0
Archive size: 6878880 bytes (6718 KiB)

Scan WARNINGS for files and folders:

 : Le chemin d'accès spécifié est introuvable. (path not found)
----------------
Scan WARNINGS: 1


WARNING: Le chemin d'accès spécifié est introuvable. (path not found)
   à Squirrel.Utility.<CreateZipFromDirectory>d__23.MoveNext()<---

```

**Comment by SeriousM** [comment]
The service needs "Network Service" as user then it's able to build the package.

**Comment by SeriousM** [comment]
The service needs "Network Service" as user then it's able to build the package.

**Comment by Thieum** [comment]
@persi12 did you try to apply the fix suggested by [the previous comment](https://github.com/Squirrel/Squirrel.Windows/issues/1060#issuecomment-437296557)? If it worked, feel free to close this issue.

**Comment by Adeshtalakane** [comment]
Hi can you brief how to accomodate
The service needs "Network Service" as user then it's able to build the package.

**Comment by persi12** [comment]
Changing the user worked, thx.

**Comment by Adeshtalakane** [comment]
hi can you tell me which service

**Comment by Adeshtalakane** [comment]
can you tell me step by step procedure to accomodate the change. thanks in advance

**Comment by Adeshtalakane** [comment]
HI Persi12,

Can you briefly me the fix step by step(changing the user worked). Thanks in advance

**Comment by Adeshtalakane** [comment]
2019-06-25 14:43:45> Program: Starting Squirrel Updater: --releasify D:\SASRepository\SGRE.SiteAssessment\APC7032_FrameworkWindows\SGRE.SiteAssessment.SASWindows\SASFrameWork.1.0.3.nupkg --releaseDir D:\SASRepository\SGRE.SiteAssessment\APC7032_FrameworkWindows\SGRE.SiteAssessment.SASWindows\Releases\1.0.3
2019-06-25 14:43:45> Program: Bootstrapper EXE found at:D:\SASRepository\SGRE.SiteAssessment\packages\squirrel.windows.1.9.1\tools\Setup.exe
2019-06-25 14:43:46> Program: Creating release package: D:\SASRepository\SGRE.SiteAssessment\APC7032_FrameworkWindows\SGRE.SiteAssessment.SASWindows\Releases\1.0.3\SASFrameWork.1.0.3.nupkg
2019-06-25 14:43:46> ReleasePackage: Creating release package: D:\SASRepository\SGRE.SiteAssessment\APC7032_FrameworkWindows\SGRE.SiteAssessment.SASWindows\Releases\1.0.3\SASFrameWork.1.0.3.nupkg => D:\SASRepository\SGRE.SiteAssessment\APC7032_FrameworkWindows\SGRE.SiteAssessment.SASWindows\Releases\1.0.3\SASFrameWork-1.0.3-full.nupkg
2019-06-25 14:43:56> ReleasePackage: Extracting dependent packages: []
2019-06-25 14:43:56> ReleasePackage: Removing unnecessary data
2019-06-25 14:43:56> Utility: Failed to extract file D:\SASRepository\SGRE.SiteAssessment\APC7032_FrameworkWindows\SGRE.SiteAssessment.SASWindows\Releases\1.0.3\SASFrameWork-1.0.3-full.nupkg to C:\WINDOWS\system32\config\systemprofile\AppData\Local\SquirrelTemp\tempa
7-Zip [64] 16.04 : Copyright (c) 1999-2016 Igor Pavlov : 2016-10-04

Open archive: D:\SASRepository\SGRE.SiteAssessment\APC7032_FrameworkWindows\SGRE.SiteAssessment.SASWindows\Releases\1.0.3\SASFrameWork-1.0.3-full.nupkg
--
Path = D:\SASRepository\SGRE.SiteAssessment\APC7032_FrameworkWindows\SGRE.SiteAssessment.SASWindows\Releases\1.0.3\SASFrameWork-1.0.3-full.nupkg
Type = zip
Physical Size = 22

Scanning the drive:
0 files, 0 bytes

Updating archive: D:\SASRepository\SGRE.SiteAssessment\APC7032_FrameworkWindows\SGRE.SiteAssessment.SASWindows\Releases\1.0.3\SASFrameWork-1.0.3-full.nupkg

Items to compress: 0


Files read from disk: 0
Archive size: 22 bytes (1 KiB)

Scan WARNINGS for files and folders:

 : The system cannot find the path specified.
----------------
Scan WARNINGS: 1


WARNING: The system cannot find the path specified.
2019-06-25 14:43:56> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.Exception: 7-Zip [64] 16.04 : Copyright (c) 1999-2016 Igor Pavlov : 2016-10-04

Open archive: D:\SASRepository\SGRE.SiteAssessment\APC7032_FrameworkWindows\SGRE.SiteAssessment.SASWindows\Releases\1.0.3\SASFrameWork-1.0.3-full.nupkg
--
Path = D:\SASRepository\SGRE.SiteAssessment\APC7032_FrameworkWindows\SGRE.SiteAssessment.SASWindows\Releases\1.0.3\SASFrameWork-1.0.3-full.nupkg
Type = zip
Physical Size = 22

Scanning the drive:
0 files, 0 bytes

Updating archive: D:\SASRepository\SGRE.SiteAssessment\APC7032_FrameworkWindows\SGRE.SiteAssessment.SASWindows\Releases\1.0.3\SASFrameWork-1.0.3-full.nupkg

Items to compress: 0


Files read from disk: 0
Archive size: 22 bytes (1 KiB)

Scan WARNINGS for files and folders:

 : The system cannot find the path specified.
----------------
Scan WARNINGS: 1


WARNING: The system cannot find the path specified.
   at Squirrel.Utility.<CreateZipFromDirectory>d__23.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.ReleasePackage.CreateReleasePackage(String outputFile, String packagesRootDir, Func`2 releaseNotesProcessor, Action`1 contentsPostProcessHook)
   at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon, Boolean generateMsi, String frameworkVersion, Boolean generateDeltas)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.Exception: 7-Zip [64] 16.04 : Copyright (c) 1999-2016 Igor Pavlov : 2016-10-04

Open archive: D:\SASRepository\SGRE.SiteAssessment\APC7032_FrameworkWindows\SGRE.SiteAssessment.SASWindows\Releases\1.0.3\SASFrameWork-1.0.3-full.nupkg
--
Path = D:\SASRepository\SGRE.SiteAssessment\APC7032_FrameworkWindows\SGRE.SiteAssessment.SASWindows\Releases\1.0.3\SASFrameWork-1.0.3-full.nupkg
Type = zip
Physical Size = 22

Scanning the drive:
0 files, 0 bytes

Updating archive: D:\SASRepository\SGRE.SiteAssessment\APC7032_FrameworkWindows\SGRE.SiteAssessment.SASWindows\Releases\1.0.3\SASFrameWork-1.0.3-full.nupkg

Items to compress: 0


Files read from disk: 0
Archive size: 22 bytes (1 KiB)

Scan WARNINGS for files and folders:

 : The system cannot find the path specified.
----------------
Scan WARNINGS: 1


WARNING: The system cannot find the path specified.
   at Squirrel.Utility.<CreateZipFromDirectory>d__23.MoveNext()<---
