### ISSUE TITLE
Error when running Setup.exe

### ISSUE THREAD

**Issue by Jorriss** [Squirrel/Squirrel.Windows#1091]
When running Setup.exe I'm getting an error. The application is a c# console app.

![image](https://user-images.githubusercontent.com/737277/28026402-ecf928a8-6563-11e7-84a7-5a39f96bbbec.png)

```
2017-07-10 11:06:34> Program: Starting Squirrel Updater: --install .
2017-07-10 11:06:34> Program: Starting install, writing to C:\Users\Richie\AppData\Local\SquirrelTemp
2017-07-10 11:06:34> Program: About to install to: C:\Users\Richie\AppData\Local\ConstantCare
2017-07-10 11:06:35> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Richie\AppData\Local\ConstantCare\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2017-07-10 11:06:35> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Richie\AppData\Local\ConstantCare\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2017-07-10 11:06:35> CheckForUpdateImpl: Reading RELEASES file from C:\Users\Richie\AppData\Local\SquirrelTemp
2017-07-10 11:06:35> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2017-07-10 11:06:35> ApplyReleasesImpl: Writing files to app directory: C:\Users\Richie\AppData\Local\ConstantCare\app-1.0.0
2017-07-10 11:06:35> ApplyReleasesImpl: Squirrel Enabled Apps: []
2017-07-10 11:06:35> ApplyReleasesImpl: No apps are marked as Squirrel-aware! Going to run them all
2017-07-10 11:06:35> ApplyReleasesImpl: About to create shortcuts for ConstantCare.exe, rootAppDir C:\Users\Richie\AppData\Local\ConstantCare
2017-07-10 11:06:35> ApplyReleasesImpl: Creating shortcut for ConstantCare.exe => C:\Users\Richie\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Brent Ozar Unlimited\BlitzCollector.lnk
2017-07-10 11:06:35> ApplyReleasesImpl: About to save shortcut: C:\Users\Richie\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Brent Ozar Unlimited\BlitzCollector.lnk (target C:\Users\Richie\AppData\Local\ConstantCare\ConstantCare.exe, workingDir C:\Users\Richie\AppData\Local\ConstantCare\app-1.0.0, args , toastActivatorCSLID 2452eeac-9218-5e80-9649-fee4fe29e6a8)
2017-07-10 11:06:35> ApplyReleasesImpl: Creating shortcut for ConstantCare.exe => C:\Users\Richie\Desktop\BlitzCollector.lnk
2017-07-10 11:06:35> ApplyReleasesImpl: About to save shortcut: C:\Users\Richie\Desktop\BlitzCollector.lnk (target C:\Users\Richie\AppData\Local\ConstantCare\ConstantCare.exe, workingDir C:\Users\Richie\AppData\Local\ConstantCare\app-1.0.0, args , toastActivatorCSLID 2452eeac-9218-5e80-9649-fee4fe29e6a8)
2017-07-10 11:06:35> ApplyReleasesImpl: Examining Pin: Cmder.lnk
2017-07-10 11:06:35> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2017-07-10 11:06:35> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2017-07-10 11:06:35> ApplyReleasesImpl: Examining Pin: SourceTree.lnk
2017-07-10 11:06:35> ApplyReleasesImpl: Examining Pin: Visual Studio 2017.lnk
2017-07-10 11:06:35> ApplyReleasesImpl: Examining Pin: Visual Studio Code.lnk
2017-07-10 11:06:35> ApplyReleasesImpl: Starting fixPinnedExecutables
2017-07-10 11:06:35> ApplyReleasesImpl: Examining Pin: Cmder.lnk
2017-07-10 11:06:35> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2017-07-10 11:06:35> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2017-07-10 11:06:35> ApplyReleasesImpl: Examining Pin: SourceTree.lnk
2017-07-10 11:06:35> ApplyReleasesImpl: Examining Pin: Visual Studio 2017.lnk
2017-07-10 11:06:35> ApplyReleasesImpl: Examining Pin: Visual Studio Code.lnk
2017-07-10 11:06:35> ApplyReleasesImpl: Fixing up tray icons
2017-07-10 11:06:35> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__13_0(RegistryView view)
2017-07-10 11:06:35> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__13_0(RegistryView view)
2017-07-10 11:06:35> ApplyReleasesImpl: cleanDeadVersions: for version 1.0.0
2017-07-10 11:06:35> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.0.0
```

**Comment by JKSnd** [comment]
Duplicate of #1071?

**Comment by Jorriss** [comment]
It is. I'll close this.

**Comment by Mnazish70** [comment]
How to fix
