### ISSUE TITLE
Did the last update break something?

### ISSUE THREAD

**Issue by AndyinHawick** [Squirrel/Squirrel.Windows#1095]
I'm trying to install other stuff and they keep on crashing with errors:
2017-07-11 12:09:14> Unhandled exception: System.IO.FileNotFoundException: Could not load file or assembly 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
File name: 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)

**Comment by Thieum** [comment]
@AndyinHawick is it still an issue with the latest version of Squirrel?
