### ISSUE TITLE
EndOfStreamException at ApplyReleases

### ISSUE THREAD

**Issue by schmidtdiego** [Squirrel/Squirrel.Windows#1104]
Hi all, I'm having an EndOfStreamException at running the method ApplyReleases:

`
                        string newPath = await mgr.ApplyReleases(updateInfo, OnProgreso);`

I updated to last version 1.7.7 but I'm facing the same issue.

The "%LocalAppData%\SquirrelTemp\SquirrelTemp.log" is not modified at all.

The method DownloadReleases runs without any problem. In the folder %LocalAppData%\MyApp\packages I can see the downloaded file MyApp-1.0.24-delta.nupkg downloaded OK, but it is not installed.

I tried to unzip that file with "7-zip" app, and it unzips OK, so it is not corrupted.

Could anyone help with this?

Thanks!!

Exception detail:
```
System.IO.EndOfStreamException: Attempted to read past the end of the stream.
   en Squirrel.Bsdiff.StreamUtility.ReadExactly(Stream stream, Byte[] buffer, Int32 offset, Int32 count) en C:\Users\paulb\code\Squirrel\squirrel.windows\src\Squirrel\BinaryPatchUtility.cs:línea 916
   en Squirrel.Bsdiff.BinaryPatchUtility.Apply(Stream input, Func`1 openPatchStream, Stream output) en C:\Users\paulb\code\Squirrel\squirrel.windows\src\Squirrel\BinaryPatchUtility.cs:línea 358
   en Squirrel.DeltaPackageBuilder.applyDiffToFile(String deltaPath, String relativeFilePath, String workingDirectory) en C:\Users\paulb\code\Squirrel\squirrel.windows\src\Squirrel\DeltaPackage.cs:línea 256
   en Squirrel.DeltaPackageBuilder.<>c__DisplayClass3_1.<ApplyDeltaPackage>b__4(String file) en C:\Users\paulb\code\Squirrel\squirrel.windows\src\Squirrel\DeltaPackage.cs:línea 133
   en Squirrel.EnumerableExtensions.ForEach[TSource](IEnumerable`1 source, Action`1 onNext) en C:\Users\paulb\code\Squirrel\squirrel.windows\src\Squirrel\EnumerableExtensions.cs:línea 29
   en Squirrel.DeltaPackageBuilder.ApplyDeltaPackage(ReleasePackage basePackage, ReleasePackage deltaPackage, String outputFile) en C:\Users\paulb\code\Squirrel\squirrel.windows\src\Squirrel\DeltaPackage.cs:línea 126
   en Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass8_0.<createFullPackagesFromDeltas>b__3() en C:\Users\paulb\code\Squirrel\squirrel.windows\src\Squirrel\UpdateManager.ApplyReleases.cs:línea 329
   en System.Threading.Tasks.Task`1.InnerInvoke()
   en System.Threading.Tasks.Task.Execute()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Squirrel.UpdateManager.ApplyReleasesImpl.<createFullPackagesFromDeltas>d__8.MoveNext() en C:\Users\paulb\code\Squirrel\squirrel.windows\src\Squirrel\UpdateManager.ApplyReleases.cs:línea 325
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__2.MoveNext() en C:\Users\paulb\code\Squirrel\squirrel.windows\src\Squirrel\UpdateManager.ApplyReleases.cs:línea 35
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Squirrel.UpdateManager.<ApplyReleases>d__9.MoveNext() en C:\Users\paulb\code\Squirrel\squirrel.windows\src\Squirrel\UpdateManager.cs:línea 73
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   en RustPlanningLBU.Wpf.ViewModel.UCUpdateAppViewModel.<updateAppDesdeRuta>d__17.MoveNext() en C:\Apps\RustPlanningLBU\RustPlanningLBU\trunk\RustPlanningLBU\RustPlanningLBU.Wpf\ViewModel\UCUpdateAppViewModel.cs:línea 152
```

**Comment by the-dansan** [comment]
Happening here too frequently.

**Comment by schmidtdiego** [comment]
If anyone is having the same issue, a Workaround is to use only the full package, and delete the delta line from the "releases" file.

**Comment by the-dansan** [comment]
Yup, but if deltas are important to you, just roll back to 1.5.2 or similar.

**Comment by paulcbetts** [comment]
Can people who are having this issue please try Squirrel.Windows 1.7.8? Hopefully this is fixed.

**Comment by the-dansan** [comment]
So far so good. I've still got the temp file not found exception showing up occasionally, but I haven't reproduced this since going to 178.

**Comment by paulcbetts** [comment]
@the-dansan Cool, thanks for reporting back

**Comment by the-dansan** [comment]
Specified argument was out of the range of valid values.
Parameter name: COUNT

   at Squirrel.Bsdiff.StreamUtility.ReadExactly(Stream stream, Byte[] buffer, Int32 offset, Int32 count)
   at Squirrel.Bsdiff.BinaryPatchUtility.Apply(Stream input, Func`1 openPatchStream, Stream output)
   at Squirrel.DeltaPackageBuilder.applyDiffToFile(String deltaPath, String relativeFilePath, String workingDirectory)
   at Squirrel.EnumerableExtensions.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)
   at Squirrel.DeltaPackageBuilder.ApplyDeltaPackage(ReleasePackage basePackage, ReleasePackage deltaPackage, String outputFile)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<createFullPackagesFromDeltas>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<ApplyReleases>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EFTours.Atlas.Shared.Squirrel.Operations.UpdateApplication.<ApplyReleasesAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EFTours.Atlas.Shared.Squirrel.Operations.UpdateApplication.<RunAsync>d__3.MoveNext()
