### ISSUE TITLE
Releasify wrong order: Expected to see ChecksumFailedException

### ISSUE THREAD

**Issue by bfcamara** [Squirrel/Squirrel.Windows#1105]
I am trying to diagnose a scenario where the releasify of versions was done in a wrong order and I was expecting to see on logs the pattern
```
"Patched file {0} has incorrect SHA1, expected {1}, got {2}"
```

Here are the steps to repro:

1. Releasify version 1.0.0 and Publish Releases folder
1. Install version 1.0.0
1. Do some changes on the app and Releasify version 1.1.0
1. From original code of 1.0.0, fix a bug and Releasify version 1.0.1
1. **Publish** the changes of Releases folder (with 2 new deltas)

At this point I have two deltas to be applied to my current version 1.0.0:

1. **1.1.0-delta** -> from 1.0.0 to 1.1.0
1. **1.0.1-delta** -> from 1.0.0 to 1.0.1

**Basically there is no delta that allows me to go from 1.0.1 to 1.1.0**.  So, I thought Squirrel would do something like this (after downloading the new RELEASES file):
1. Deterine deltas to apply: 1.0.1-delta and 1.1.0-delta
1. Apply delta 1.0.1-delta. It should be working
1. Apply delta 1.1.0-delta. **I was expecting to see the error thrown by [verifyPatchedFile](https://github.com/Squirrel/Squirrel.Windows/blob/ffaf5f2392d34a415e433581fffe78c4ff96862b/src/Squirrel/DeltaPackage.cs#L285) since the application of this delta was generated based on 1.0.0 and not 1.0.1.**

Instead of the error related with verifyPatchedFile, I see this error in logs

```
IEnableLogger: Failed to apply updates: System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at DeltaCompressionDotNet.MsDelta.MsDeltaCompression.ApplyDelta(String deltaFilePath, String oldFilePath, String newFilePath)
   at Squirrel.DeltaPackageBuilder.applyDiffToFile(String deltaPath, String relativeFilePath, String workingDirectory)
   at Squirrel.DeltaPackageBuilder.<>c__DisplayClass3_1.<ApplyDeltaPackage>b__4(String file)
   at Squirrel.EnumerableExtensions.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)
   at Squirrel.DeltaPackageBuilder.ApplyDeltaPackage(ReleasePackage basePackage, ReleasePackage deltaPackage, String outputFile)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass8_0.<createFullPackagesFromDeltas>b__3()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<createFullPackagesFromDeltas>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<createFullPackagesFromDeltas>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<ApplyReleases>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__43`1.MoveNext()
```

If I repeat the whole process with the correct order, relasifying first 1.0.1 and then 1.1.0, everything is OKas expected.

I am attaching both logs (OK and wrong order).

In both scenarios I end to have installed 1.1.0 as expected. However I was expecting to see something on logs in the scenario with the wrong releasifying order.

Am I missing something?

Thanks in advance

[MyAppUpdateLog_OK.txt](https://github.com/Squirrel/Squirrel.Windows/files/1165119/MyAppUpdateLog_OK.txt)
[MyAppUpdateLog_Wrong_Order.txt](https://github.com/Squirrel/Squirrel.Windows/files/1165120/MyAppUpdateLog_Wrong_Order.txt)

**Comment by bfcamara** [comment]
I guess if I want to support the case where some users are on 1.0.x and others on 1.1.x I would need to have different URLs (one for each group of users, maybe my beta users vs production).

I do understand that the concept is not supported, but I was just trying to understand how Squirrel behaves in a situation where I releasified in a wrong order. So the first thing is, if it is not supported, I was expecting that the releasify command would throw an error (at least when generating deltas) telling me that there is already greater version. Since I was able to releasify, I was expecting to see some warnings/errors on logs related with deltas, in particular the shassum validation because the calculated diffs during releasify will produce files at some point with different shasum.

My concern here is, if for some reason this wrong order of releasify happens (automated releases with versions calculated with GitVersion based on branch names), how Squirrel behaves and what will be the final version installed.

**Comment by lukeskinner** [comment]
It's hard to say what state the app is left in without trying it/seeing the results. 

I think the releasify process should block this, @paulcbetts have you got an opinion on this?

Yep different URLs/folders would be the best way to have many versions out at a time. Technically you can also use a web service to give you even better control over who gets what and when but you would have to write said web service.

**Comment by bfcamara** [comment]
From by tests, both scenarios ended in 1.1.0., which was the end goal and what I was expecting. The curious part is that, from what I read in code, I was expecting to have some log entries for the wrong order scenario, which didn't happen. That's what triggered my attention for all this issue. 

I am with you in blocking the releasify command, unless the flag no-deltas is passed or a force flag.
