### ISSUE TITLE
.net 4.5 specific issue in windows 7

### ISSUE THREAD

**Issue by ishwarrimal** [Squirrel/Squirrel.Windows#1108]
We are facing installation issues on few windows 7 machine because of .net 4.5 dependency. It wont allow to install unless .net 4.5 in installed.
And worse, in some case even if .net 4.7 is installed in system , it wont run. There are so many issues related to this.

And in this specific case, its got to do something wiht .4.0.30319 and i am not able to solve this no matter what i do
Is there any solution to this?

2017-07-24 19:41:59> Unhandled exception: System.TypeInitializationException: The type initializer for '' threw an exception. ---> .ModuleLoadException: The C++ module failed to load during appdomain initialization.
---> System.DllNotFoundException: C:\Windows\Microsoft.NET\Framework\v4.0.30319\WPF\wpfgfx_v0400.dll ---> System.ComponentModel.Win32Exception: Access is denied
--- End of inner exception stack trace ---
at MS.Internal.NativeWPFDLLLoader.LoadNativeWPFDLL(UInt16* relDllPath, UInt16* baseDllPath)
at MS.Internal.NativeWPFDLLLoader.LoadCommonDLLsAndDwrite()
at CModuleInitialize.{ctor}(CModuleInitialize* , IntPtr cleaningUpFunc)
at ?A0xc025e03f.CreateCModuleInitialize()
at ?A0xc025e03f.??__E?A0xc025e03f@cmiStartupRunner@@ymxxz()
at _initterm_m((fnptr)* pfbegin, (fnptr)* pfend)
at .LanguageSupport.InitializePerAppDomain(LanguageSupport* )
at .LanguageSupport._Initialize(LanguageSupport* )
at .LanguageSupport.Initialize(LanguageSupport* )
--- End of inner exception stack trace ---
at .LanguageSupport.Initialize(LanguageSupport* )
at .cctor()
--- End of inner exception stack trace ---
at Squirrel.Update.Program.executeCommandLine(String[] args)
at Squirrel.Update.Program.main(String[] args)
2017-07-24 19:42:51> Unhandled exception: System.TypeInitializationException: The type initializer for '' threw an exception. ---> .ModuleLoadException: The C++ module failed to load during appdomain initialization.
---> System.DllNotFoundException: C:\Windows\Microsoft.NET\Framework\v4.0.30319\WPF\wpfgfx_v0400.dll ---> System.ComponentModel.Win32Exception: Access is denied
--- End of inner exception stack trace ---
at MS.Internal.NativeWPFDLLLoader.LoadNativeWPFDLL(UInt16* relDllPath, UInt16* baseDllPath)
at MS.Internal.NativeWPFDLLLoader.LoadCommonDLLsAndDwrite()
at CModuleInitialize.{ctor}(CModuleInitialize* , IntPtr cleaningUpFunc)
at ?A0xc025e03f.CreateCModuleInitialize()
at ?A0xc025e03f.??__E?A0xc025e03f@cmiStartupRunner@@ymxxz()
at _initterm_m((fnptr)* pfbegin, (fnptr)* pfend)
at .LanguageSupport.InitializePerAppDomain(LanguageSupport* )
at .LanguageSupport._Initialize(LanguageSupport* )
at .LanguageSupport.Initialize(LanguageSupport* )
--- End of inner exception stack trace ---
at .LanguageSupport.Initialize(LanguageSupport* )
at .cctor()
--- End of inner exception stack trace ---
at Squirrel.Update.Program.executeCommandLine(String[] args)
at Squirrel.Update.Program.main(String[] args)
2017-07-24 19:48:59> Unhandled exception: System.TypeInitializationException: The type initializer for '' threw an exception. ---> .ModuleLoadException: The C++ module failed to load during appdomain initialization.
---> System.DllNotFoundException: C:\Windows\Microsoft.NET\Framework\v4.0.30319\WPF\wpfgfx_v0400.dll ---> System.ComponentModel.Win32Exception: Access is denied
--- End of inner exception stack trace ---
at MS.Internal.NativeWPFDLLLoader.LoadNativeWPFDLL(UInt16* relDllPath, UInt16* baseDllPath)
at MS.Internal.NativeWPFDLLLoader.LoadCommonDLLsAndDwrite()
at CModuleInitialize.{ctor}(CModuleInitialize* , IntPtr cleaningUpFunc)
at ?A0xc025e03f.CreateCModuleInitialize()
at ?A0xc025e03f.??__E?A0xc025e03f@cmiStartupRunner@@ymxxz()
at _initterm_m((fnptr)* pfbegin, (fnptr)* pfend)
at .LanguageSupport.InitializePerAppDomain(LanguageSupport* )
at .LanguageSupport._Initialize(LanguageSupport* )
at .LanguageSupport.Initialize(LanguageSupport* )
--- End of inner exception stack trace ---
at .LanguageSupport.Initialize(LanguageSupport* )
at .cctor()
--- End of inner exception stack trace ---
at Squirrel.Update.Program.executeCommandLine(String[] args)
at Squirrel.Update.Program.main(String[] args)
2017-07-24 19:49:15> Unhandled exception: System.TypeInitializationException: The type initializer for '' threw an exception. ---> .ModuleLoadException: The C++ module failed to load during appdomain initialization.
---> System.DllNotFoundException: C:\Windows\Microsoft.NET\Framework\v4.0.30319\WPF\wpfgfx_v0400.dll ---> System.ComponentModel.Win32Exception: Access is denied
--- End of inner exception stack trace ---
at MS.Internal.NativeWPFDLLLoader.LoadNativeWPFDLL(UInt16* relDllPath, UInt16* baseDllPath)
at MS.Internal.NativeWPFDLLLoader.LoadCommonDLLsAndDwrite()
at CModuleInitialize.{ctor}(CModuleInitialize* , IntPtr cleaningUpFunc)
at ?A0xc025e03f.CreateCModuleInitialize()
at ?A0xc025e03f.??__E?A0xc025e03f@cmiStartupRunner@@ymxxz()
at _initterm_m((fnptr)* pfbegin, (fnptr)* pfend)
at .LanguageSupport.InitializePerAppDomain(LanguageSupport* )
at .LanguageSupport._Initialize(LanguageSupport* )
at .LanguageSupport.Initialize(LanguageSupport* )
--- End of inner exception stack trace ---
at .LanguageSupport.Initialize(LanguageSupport* )
at .cctor()
--- End of inner exception stack trace ---
at Squirrel.Update.Program.executeCommandLine(String[] args)
at Squirrel.Update.Program.main(String[] args)
2017-07-25 11:08:23> Unhandled exception: System.TypeInitializationException: The type initializer for '' threw an exception. ---> .ModuleLoadException: The C++ module failed to load during appdomain initialization.
---> System.DllNotFoundException: C:\Windows\Microsoft.NET\Framework\v4.0.30319\WPF\wpfgfx_v0400.dll ---> System.ComponentModel.Win32Exception: Access is denied
--- End of inner exception stack trace ---
at MS.Internal.NativeWPFDLLLoader.LoadNativeWPFDLL(UInt16* relDllPath, UInt16* baseDllPath)
at MS.Internal.NativeWPFDLLLoader.LoadCommonDLLsAndDwrite()
at CModuleInitialize.{ctor}(CModuleInitialize* , IntPtr cleaningUpFunc)
at ?A0xc025e03f.CreateCModuleInitialize()
at ?A0xc025e03f.??__E?A0xc025e03f@cmiStartupRunner@@ymxxz()
at _initterm_m((fnptr)* pfbegin, (fnptr)* pfend)
at .LanguageSupport.InitializePerAppDomain(LanguageSupport* )
at .LanguageSupport._Initialize(LanguageSupport* )
at .LanguageSupport.Initialize(LanguageSupport* )
--- End of inner exception stack trace ---
at .LanguageSupport.Initialize(LanguageSupport* )
at .cctor()
--- End of inner exception stack trace ---
at Squirrel.Update.Program.executeCommandLine(String[] args)
at Squirrel.Update.Program.main(String[] args)
2017-07-25 13:44:44> Unhandled exception: System.TypeInitializationException: The type initializer for '' threw an exception. ---> .ModuleLoadException: The C++ module failed to load during appdomain initialization.
---> System.DllNotFoundException: C:\Windows\Microsoft.NET\Framework\v4.0.30319\WPF\wpfgfx_v0400.dll ---> System.ComponentModel.Win32Exception: Access is denied
--- End of inner exception stack trace ---
at MS.Internal.NativeWPFDLLLoader.LoadNativeWPFDLL(UInt16* relDllPath, UInt16* baseDllPath)
at MS.Internal.NativeWPFDLLLoader.LoadCommonDLLsAndDwrite()
at CModuleInitialize.{ctor}(CModuleInitialize* , IntPtr cleaningUpFunc)
at ?A0xc025e03f.CreateCModuleInitialize()
at ?A0xc025e03f.??__E?A0xc025e03f@cmiStartupRunner@@ymxxz()
at _initterm_m((fnptr)* pfbegin, (fnptr)* pfend)
at .LanguageSupport.InitializePerAppDomain(LanguageSupport* )
at .LanguageSupport._Initialize(LanguageSupport* )
at .LanguageSupport.Initialize(LanguageSupport* )
--- End of inner exception stack trace ---
at .LanguageSupport.Initialize(LanguageSupport* )
at .cctor()
--- End of inner exception stack trace ---
at Squirrel.Update.Program.executeCommandLine(String[] args)
at Squirrel.Update.Program.main(String[] args)
2017-07-25 14:02:51> Unhandled exception: System.TypeInitializationException: The type initializer for '' threw an exception. ---> .ModuleLoadException: The C++ module failed to load during appdomain initialization.
---> System.DllNotFoundException: C:\Windows\Microsoft.NET\Framework\v4.0.30319\WPF\wpfgfx_v0400.dll ---> System.ComponentModel.Win32Exception: Access is denied
--- End of inner exception stack trace ---
at MS.Internal.NativeWPFDLLLoader.LoadNativeWPFDLL(UInt16* relDllPath, UInt16* baseDllPath)
at MS.Internal.NativeWPFDLLLoader.LoadCommonDLLsAndDwrite()
at CModuleInitialize.{ctor}(CModuleInitialize* , IntPtr cleaningUpFunc)
at ?A0xc025e03f.CreateCModuleInitialize()
at ?A0xc025e03f.??__E?A0xc025e03f@cmiStartupRunner@@ymxxz()
at _initterm_m((fnptr)* pfbegin, (fnptr)* pfend)
at .LanguageSupport.InitializePerAppDomain(LanguageSupport* )
at .LanguageSupport._Initialize(LanguageSupport* )
at .LanguageSupport.Initialize(LanguageSupport* )
--- End of inner exception stack trace ---
at .LanguageSupport.Initialize(LanguageSupport* )
at .cctor()
--- End of inner exception stack trace ---
at Squirrel.Update.Program.executeCommandLine(String[] args)
at Squirrel.Update.Program.main(String[] args)
2017-07-25 14:04:01> Unhandled exception: System.TypeInitializationException: The type initializer for '' threw an exception. ---> .ModuleLoadException: The C++ module failed to load during appdomain initialization.
---> System.DllNotFoundException: C:\Windows\Microsoft.NET\Framework\v4.0.30319\WPF\wpfgfx_v0400.dll ---> System.ComponentModel.Win32Exception: Access is denied
--- End of inner exception stack trace ---
at MS.Internal.NativeWPFDLLLoader.LoadNativeWPFDLL(UInt16* relDllPath, UInt16* baseDllPath)
at MS.Internal.NativeWPFDLLLoader.LoadCommonDLLsAndDwrite()
at CModuleInitialize.{ctor}(CModuleInitialize* , IntPtr cleaningUpFunc)
at ?A0xc025e03f.CreateCModuleInitialize()
at ?A0xc025e03f.??__E?A0xc025e03f@cmiStartupRunner@@ymxxz()
at _initterm_m((fnptr)* pfbegin, (fnptr)* pfend)
at .LanguageSupport.InitializePerAppDomain(LanguageSupport* )
at .LanguageSupport._Initialize(LanguageSupport* )
at .LanguageSupport.Initialize(LanguageSupport* )
--- End of inner exception stack trace ---
at .LanguageSupport.Initialize(LanguageSupport* )
at .cctor()
--- End of inner exception stack trace ---
at Squirrel.Update.Program.executeCommandLine(String[] args)
at Squirrel.Update.Program.main(String[] args)
2017-07-25 14:04:11> Unhandled exception: System.TypeInitializationException: The type initializer for '' threw an exception. ---> .ModuleLoadException: The C++ module failed to load during appdomain initialization.
---> System.DllNotFoundException: C:\Windows\Microsoft.NET\Framework\v4.0.30319\WPF\wpfgfx_v0400.dll ---> System.ComponentModel.Win32Exception: Access is denied
--- End of inner exception stack trace ---
at MS.Internal.NativeWPFDLLLoader.LoadNativeWPFDLL(UInt16* relDllPath, UInt16* baseDllPath)
at MS.Internal.NativeWPFDLLLoader.LoadCommonDLLsAndDwrite()
at CModuleInitialize.{ctor}(CModuleInitialize* , IntPtr cleaningUpFunc)
at ?A0xc025e03f.CreateCModuleInitialize()
at ?A0xc025e03f.??__E?A0xc025e03f@cmiStartupRunner@@ymxxz()
at _initterm_m((fnptr)* pfbegin, (fnptr)* pfend)
at .LanguageSupport.InitializePerAppDomain(LanguageSupport* )
at .LanguageSupport._Initialize(LanguageSupport* )
at .LanguageSupport.Initialize(LanguageSupport* )
--- End of inner exception stack trace ---
at .LanguageSupport.Initialize(LanguageSupport* )
at .cctor()
--- End of inner exception stack trace ---
at Squirrel.Update.Program.executeCommandLine(String[] args)
at Squirrel.Update.Program.main(String[] args)
2017-07-25 14:28:12> Unhandled exception: System.TypeInitializationException: The type initializer for '' threw an exception. ---> .ModuleLoadException: The C++ module failed to load during appdomain initialization.
---> System.DllNotFoundException: C:\Windows\Microsoft.NET\Framework\v4.0.30319\WPF\wpfgfx_v0400.dll ---> System.ComponentModel.Win32Exception: Access is denied
--- End of inner exception stack trace ---
at MS.Internal.NativeWPFDLLLoader.LoadNativeWPFDLL(UInt16* relDllPath, UInt16* baseDllPath)
at MS.Internal.NativeWPFDLLLoader.LoadCommonDLLsAndDwrite()
at CModuleInitialize.{ctor}(CModuleInitialize* , IntPtr cleaningUpFunc)
at ?A0xc025e03f.CreateCModuleInitialize()
at ?A0xc025e03f.??__E?A0xc025e03f@cmiStartupRunner@@ymxxz()
at _initterm_m((fnptr)* pfbegin, (fnptr)* pfend)
at .LanguageSupport.InitializePerAppDomain(LanguageSupport* )
at .LanguageSupport._Initialize(LanguageSupport* )
at .LanguageSupport.Initialize(LanguageSupport* )
--- End of inner exception stack trace ---
at .LanguageSupport.Initialize(LanguageSupport* )
at .cctor()
--- End of inner exception stack trace ---
at Squirrel.Update.Program.executeCommandLine(String[] args)
at Squirrel.Update.Program.main(String[] args)

**Comment by muhammetalay** [comment]
We have the same issue on 1 user. How to proceed?

**Comment by lindexi** [comment]
Please re-install .net Framework

**Comment by shiftkey** [comment]
I believe this is a problem with the .NET Framework installation (that Squirrel relies on, even if your application does not), and repairing/reinstalling is the only option here.
