### ISSUE TITLE
Can't releasify Squirrel on Build Agent

### ISSUE THREAD

**Issue by weijoe** [Squirrel/Squirrel.Windows#1125]
Hi, I can't releasify my squirrel app on a TFS Build Agent.
I have 2 Build Agents and one works and an other not.

The build agent runs with an other user. If I run
`Program: Starting Squirrel Updater: --releasify Program.nupkg --no-msi`
in the Console under my normal account it works.

I hope you can help me.

Here is the Error output from the log

```
2017-08-08 13:30:17> ReleasePackage: Extracting dependent packages: []
2017-08-08 13:30:17> ReleasePackage: Removing unnecessary data
2017-08-08 13:30:21> Program: Building embedded zip file for Setup.exe
2017-08-08 13:30:23> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.IO.IOException: The file exists.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.IO.Path.InternalGetTempFileName(Boolean checkHost)
   at Squirrel.Update.Program.<createSetupEmbeddedZip>d__16.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon, Boolean generateMsi, String frameworkVersion, Boolean generateDeltas)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.IO.IOException: The file exists.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.IO.Path.InternalGetTempFileName(Boolean checkHost)
   at Squirrel.Update.Program.<createSetupEmbeddedZip>d__16.MoveNext()<---

```

**Comment by paulcbetts** [comment]
Your temp directory is completely full

**Comment by weijoe** [comment]
thanks. that was the issue. It does not get cleaned.
