### ISSUE TITLE
InvokeProcessAsync can cause child process to hang

### ISSUE THREAD

**Issue by marcusmateus** [Squirrel/Squirrel.Windows#1145]
InvokeProcessAsync redirects StandardOutput & StandardError, but does not read from them during task execution.  This means that if the child process logs too much to either stream it will eventually block on write until the CancellationToken expires.  In practice, it did not take too much logging to start blocking (~100 lines) and prevent further execution of the child.

The relevant section of code is copied below.  Since the output is not read in the while loop, the child can eventually block on write until it is killed via the CancellationToken.
https://github.com/Squirrel/Squirrel.Windows/blob/master/src/Squirrel/Utility.cs#L202
```JS
await Task.Run(() => {
    while (!ct.IsCancellationRequested) {
        if (pi.WaitForExit(2000)) return;
    }

    if (ct.IsCancellationRequested) {
        pi.Kill();
        ct.ThrowIfCancellationRequested();
    }
});
```

The remarks section of this [article](https://msdn.microsoft.com/en-us/library/system.diagnostics.processstartinfo.redirectstandardoutput(v=vs.110).aspx) discusses how to properly avoid a deadlock condition due to output redirection.

**Comment by paulcbetts** [comment]
I'd take a PR to fix this

**Comment by fmilani** [comment]
Do you guys think that's why I'm having this error:

```
2017-11-27 20:04:03,420 [7] INFO  Squirrel.UpdateManager+ApplyReleasesImpl [(null)] - Squirrel Enabled Apps: [C:\Users\felmi\AppData\Local\EvoluServices\app-4.7.1\EvoluServices.UI.Windows.exe]
2017-11-27 20:04:19,453 [6] ERROR Squirrel.UpdateManager+ApplyReleasesImpl [(null)] - Couldn't run Squirrel hook, continuing: C:\Users\felmi\AppData\Local\EvoluServices\app-4.7.1\EvoluServices.UI.Windows.exe
Type: System.OperationCanceledException
Message: The operation was canceled.
Source: mscorlib
TargetSite: Void ThrowOperationCanceledException()
StackTrace:    at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Squirrel.Utility.<>c__DisplayClass11_0.<InvokeProcessAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<InvokeProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass10_0.<<invokePostInstall>b__0>d.MoveNext()

2017-11-27 20:04:19,505 [6] INFO  Squirrel.UpdateManager+ApplyReleasesImpl [(null)] - Starting fixPinnedExecutables
2017-11-27 20:04:19,535 [6] INFO  Squirrel.UpdateManager+ApplyReleasesImpl [(null)] - Fixing up tray icons
2017-11-27 20:04:19,591 [6] INFO  Squirrel.UpdateManager+ApplyReleasesImpl [(null)] - cleanDeadVersions: for version 4.7.1
2017-11-27 20:04:19,601 [6] INFO  Squirrel.UpdateManager+ApplyReleasesImpl [(null)] - cleanDeadVersions: exclude folder app-4.7.0
2017-11-27 20:04:19,612 [6] INFO  Squirrel.UpdateManager+ApplyReleasesImpl [(null)] - cleanDeadVersions: exclude folder app-4.7.1
```

I can't figure out why I'm getting this error.

**Comment by marcusmateus** [comment]
@fmilani, that is how this error manifests itself in the logs.  That said, it is possible you could be timing out for other reasons.  The simplest way to test is to just disable logging during squirrel operations and see if you still time out... in fact that is our current workaround for the issue.

**Comment by fmilani** [comment]
@marcusmateus Thank you for the reply! Our log4net logs were indeed causing the timeout. More precisely the log4net internal debug was turned on in our App.config (`<add key="log4net.Internal.Debug" value="True" />`)
