### ISSUE TITLE
electron-winstaller stops: The specified executable is not a valid application for this OS platform

### ISSUE THREAD

**Issue by jublo** [Squirrel/Squirrel.Windows#1148]
Squirrel.Windows 1.7.1 and 1.7.5 on Windows 7:

```
> an-app-installer@1.0.0 installer C:\Users\User\Documents\ins
taller
> node installer.js

Failed with exit code: 4294967295
Output:
Done Adding Additional Store
Successfully signed: C:\Users\User\AppData\Local\SquirrelTemp\tempc\lib\net45\s
quirrel.exe
Done Adding Additional Store
Successfully signed: C:\Users\ User\AppData\Local\SquirrelTemp\tempc\lib\net45\f
fmpeg.dll
Done Adding Additional Store
Successfully signed: C:\Users\ User\AppData\Local\SquirrelTemp\tempc\lib\net45\l
ibEGL.dll
Done Adding Additional Store
Successfully signed: C:\Users\ User\AppData\Local\SquirrelTemp\tempc\lib\net45\l
ibGLESv2.dll
Done Adding Additional Store
Successfully signed: C:\Users\ User\AppData\Local\SquirrelTemp\tempc\lib\net45\m
ichelin_value_passport_ExecutionStub.exe
Done Adding Additional Store
Successfully signed: C:\Users\ User\AppData\Local\SquirrelTemp\tempc\lib\net45\n
ode.dll
System.AggregateException: One or more errors occurred. ---> System.ComponentMod
el.Win32Exception: The specified executable is not a valid application for this
OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startIn
fo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Squirrel.Utility.<InvokeProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Squirrel.Utility.<CreateZipFromDirectory>d__23.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceled
Exceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationTo
ken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.ReleasePackage.CreateReleasePackage(String outputFile, String pac
kagesRootDir, Func`2 releaseNotesProcessor, Action`1 contentsPostProcessHook)
   at Squirrel.Update.Program.Releasify(String package, String targetDir, String
 packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts,
String baseUrl, String setupIcon, Boolean generateMsi, String frameworkVersion,
Boolean generateDeltas)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)
---> (Inner Exception #0) System.ComponentModel.Win32Exception (0x80004005): The
 specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startIn
fo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Squirrel.Utility.<InvokeProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Squirrel.Utility.<CreateZipFromDirectory>d__23.MoveNext()<---
```

How to resolve?

**Comment by paulcbetts** [comment]
You installed a 32-bit version of Windows, Squirrel.Windows is 64-bit only for building installers

**Comment by lukywong** [comment]
@paulcbetts is it possible to support 32-bit version of windows? because i really want it support

**Comment by paulcbetts** [comment]
@lukywong No, sorry! While the installer you build will support 32-bit computers (i.e. your *users* can have 32-bit OS), your computer must be 64-bit.

**Comment by fengerzh** [comment]
@anaisbetts Is there any official document mentions that we can only build on 64-bit Windows? Thanks!

**Comment by anaisbetts** [comment]
This issue!
