### ISSUE TITLE
First install doesn't add shortcuts for Squirrel aware app

### ISSUE THREAD

**Issue by jauggy** [Squirrel/Squirrel.Windows#1156]
I have a Squirrel enabled app. I added hooks for adding shortcuts. However, they don't get run. I am running the setup.exe as an administrator.  Here is the log:
```

2017-09-22 15:31:47> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\Joshua\AppData\Local\Win10CMU\app-1.81.6\ModernUIApp.exe]
2017-09-22 15:31:47> ApplyReleasesImpl: Couldn't run Squirrel hook, continuing: C:\Users\Joshua\AppData\Local\Win10CMU\app-1.81.6\ModernUIApp.exe: System.ComponentModel.Win32Exception (0x80004005): The requested operation requires elevation
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Squirrel.Utility.<InvokeProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass10_0.<<invokePostInstall>b__0>d.MoveNext()
```

My code is inside the OnStartup method of a wpf app
```                    using (var mgr = new UpdateManager(location, "Win10CMU"))
                    {
                        //https://github.com/Squirrel/Squirrel.Windows/blob/14d6dc1599676a9d83daba60e73507d12b73164d/docs/using/custom-squirrel-events.md
                        SquirrelAwareApp.HandleEvents(
                          onInitialInstall: v => mgr.CreateShortcutForThisExe(),
                          onAppUpdate: v => mgr.CreateShortcutForThisExe(),
                          onAppUninstall: v => mgr.RemoveShortcutForThisExe(),
                          onFirstRun: () => { });
                        await mgr.UpdateApp();
                    }```

**Comment by AkioUnity** [comment]
I have same issue.

Shortcuts (both desktop and start) are not created
but update worked fine.

2018-04-07 09:58:42> ApplyReleasesImpl: Couldn't run Squirrel hook, continuing:

**Comment by MihaMarkic** [comment]
In my case no shortcut is created, but I don't get "Couldn't run Squirrel hook,....".
Just nothing is created.

**Comment by MihaMarkic** [comment]
Nevermind. It was a problem with my application not starting properly.
@AkioUnity As per your case - your app obviously requires elevated privileges. Do you have something like this in your app manifest?
https://msdn.microsoft.com/en-us/library/bb756929.aspx

**Comment by paulcbetts** [comment]
@AkioUnity Elevated apps will 100% not work in Squirrel, if you have to elevate, you need to use a different installer

**Comment by Thieum** [comment]
@shiftkey it can be closed as wontfix (no support for elevated apps). On the other hand, I couldn't find a direct reference to this in the docs, maybe we should add something about this.

**Comment by ken-sands** [comment]
Another thing that can cause this is passing extra parameters through setup, the code returns false if it's not exactly 2 parameters. to get around that:

SquirrelAwareApp.cs line 64 change it from
**            if (args.Length != 2) return;**

to

**            if (args.Length < 2) return;**
