### ISSUE TITLE
Why is releaseify failing?

### ISSUE THREAD

**Issue by mhsimkin** [Squirrel/Squirrel.Windows#1176]
When I try to releaseify my package, Squirrel fails.

The log shows the following:

`2017-10-12 17:30:05> Program: Starting Squirrel Updater: --releasify DesktopClient\ScribeUI\obj\octopacked\ScribeUI.3.2.110.nupkg -n /v /f DesktopClient\ScribeUI\ScribeUICodeSigningCertificate.pfx /P Hydrogen1
2017-10-12 17:30:05> Program: Bootstrapper EXE found at:D:\Work\BN\ProductDataSystemsGitRepos\Tools\Scribe\packages\squirrel.windows.1.7.8\tools\Setup.exe
2017-10-12 17:30:05> Program: Creating release package: D:\Work\BN\ProductDataSystemsGitRepos\Tools\Scribe\Releases\ScribeUI.3.2.110.nupkg
2017-10-12 17:30:05> ReleasePackage: Creating release package: D:\Work\BN\ProductDataSystemsGitRepos\Tools\Scribe\Releases\ScribeUI.3.2.110.nupkg => D:\Work\BN\ProductDataSystemsGitRepos\Tools\Scribe\Releases\ScribeUI-3.2.110-full.nupkg
2017-10-12 17:30:06> ReleasePackage: Extracting dependent packages: []
2017-10-12 17:30:06> ReleasePackage: Removing unnecessary data
2017-10-12 17:30:06> Program: About to sign C:\Users\spmys\AppData\Local\SquirrelTemp\tempa\lib\net462\BackboneAPI.dll
2017-10-12 17:30:06> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.Exception: Failed to sign, command invoked was: 'D:\Work\BN\ProductDataSystemsGitRepos\Tools\Scribe\packages\squirrel.windows.1.7.8\tools\signtool.exe sign /v C:\Users\spmys\AppData\Local\SquirrelTemp\tempa\lib\net462\BackboneAPI.dll'
   at Squirrel.Update.Program.<signPEFile>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<>c__DisplayClass10_1.<<Releasify>b__9>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Squirrel.Update.Program.<>c__DisplayClass10_1.<Releasify>b__2(String pkgPath)
   at Squirrel.ReleasePackage.CreateReleasePackage(String outputFile, String packagesRootDir, Func`2 releaseNotesProcessor, Action`1 contentsPostProcessHook)
   at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon, Boolean generateMsi, String frameworkVersion, Boolean generateDeltas)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.Exception: Failed to sign, command invoked was: 'D:\Work\BN\ProductDataSystemsGitRepos\Tools\Scribe\packages\squirrel.windows.1.7.8\tools\signtool.exe sign /v C:\Users\spmys\AppData\Local\SquirrelTemp\tempa\lib\net462\BackboneAPI.dll'
   at Squirrel.Update.Program.<signPEFile>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<>c__DisplayClass10_1.<<Releasify>b__9>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()<---

`
Any ideas as to what is failing and why?  When I run the sign command at the command prompt there are no issues in signing the file.

Thanks

-marc

**Comment by mhsimkin** [comment]
The squirrelsetup.log file in %localappdata%\squirreltemp has the following details:

`
2016-11-22 14:05:19> Program: Starting Squirrel Updater: --install .
2016-11-22 14:05:19> Program: Starting install, writing to C:\Users\spmys\AppData\Local\SquirrelTemp
2016-11-22 14:05:19> Program: About to install to: C:\Users\spmys\AppData\Local\MongoDBCompass
2016-11-22 14:05:19> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\spmys\AppData\Local\MongoDBCompass\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2016-11-22 14:05:19> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\spmys\AppData\Local\MongoDBCompass\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2016-11-22 14:05:19> CheckForUpdateImpl: Reading RELEASES file from C:\Users\spmys\AppData\Local\SquirrelTemp
2016-11-22 14:05:19> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2016-11-22 14:05:19> ApplyReleasesImpl: Writing files to app directory: C:\Users\spmys\AppData\Local\MongoDBCompass\app-1.4.1
2016-11-22 14:05:21> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\spmys\AppData\Local\MongoDBCompass\app-1.4.1\MongoDBCompass.exe]
2016-11-22 14:05:24> ApplyReleasesImpl: Starting fixPinnedExecutables
2016-11-22 14:05:24> ApplyReleasesImpl: Examining Pin: Altova XMLSpy (x64).lnk
2016-11-22 14:05:24> ApplyReleasesImpl: Examining Pin: dbForge Studio for MySQL.lnk
2016-11-22 14:05:24> ApplyReleasesImpl: Examining Pin: Developer Command Prompt for VS2015.lnk
2016-11-22 14:05:24> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2016-11-22 14:05:24> ApplyReleasesImpl: Examining Pin: IIS Manager.lnk
2016-11-22 14:05:24> ApplyReleasesImpl: File 'C:\Users\spmys\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar\IIS Manager.lnk' could not be converted into a valid ShellLink: System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at Squirrel.Shell.ShellLink.IShellLinkW.Resolve(IntPtr hWnd, UInt32 fFlags)
   at Squirrel.Shell.ShellLink.Open(String linkFile, IntPtr hWnd, EShellLinkResolveFlags resolveFlags, UInt16 timeOut)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<fixPinnedExecutables>b__11_0(FileInfo file)
2016-11-22 14:05:24> ApplyReleasesImpl: Examining Pin: IntelliJ IDEA 2016.2.lnk
2016-11-22 14:05:24> ApplyReleasesImpl: Examining Pin: Internet Explorer.lnk
2016-11-22 14:05:24> ApplyReleasesImpl: Examining Pin: JetBrains DataGrip 2016.2.1.lnk
2016-11-22 14:05:24> ApplyReleasesImpl: Examining Pin: MongoChef Core.lnk
2016-11-22 14:05:24> ApplyReleasesImpl: Examining Pin: Outlook 2016.lnk
2016-11-22 14:05:24> ApplyReleasesImpl: Examining Pin: SmartGit.lnk
2016-11-22 14:05:24> ApplyReleasesImpl: Examining Pin: SQL Server 2014 Management Studio.lnk
2016-11-22 14:05:24> ApplyReleasesImpl: Examining Pin: UltraEdit.lnk
2016-11-22 14:05:24> ApplyReleasesImpl: Examining Pin: Visual Studio 2015.lnk
2016-11-22 14:05:24> ApplyReleasesImpl: Examining Pin: Windows Explorer.lnk
2016-11-22 14:05:24> ApplyReleasesImpl: Fixing up tray icons
2016-11-22 14:05:24> ApplyReleasesImpl: cleanDeadVersions: for version 1.4.1
2016-11-22 14:05:24> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.4.1
`

**Comment by lehne** [comment]
Getting the same issue here. @mhsimkin did you ever resolve it?

**Comment by mhsimkin** [comment]
Nope.  I gave up. Decided to not use the package.

**Comment by lehne** [comment]
Ah OK we just fixed it by renaming the SquirrelTemp folder. It must've been something in that folder because it worked after that.
