### ISSUE TITLE
Error setup

### ISSUE THREAD

**Issue by songsammy** [Squirrel/Squirrel.Windows#1177]
2017-10-14 13:05:43> Program: Starting Squirrel Updater: --install .
2017-10-14 13:05:43> Program: Starting install, writing to C:\Users\Administrator.MS-20171007QKTN\AppData\Local\SquirrelTemp
2017-10-14 13:05:43> Program: About to install to: C:\Users\Administrator.MS-20171007QKTN\AppData\Local\Httpschecker
2017-10-14 13:05:43> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Administrator.MS-20171007QKTN\AppData\Local\Httpschecker\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2017-10-14 13:05:43> CheckForUpdateImpl: Reading RELEASES file from C:\Users\Administrator.MS-20171007QKTN\AppData\Local\SquirrelTemp
2017-10-14 13:05:43> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2017-10-14 13:05:43> ApplyReleasesImpl: Writing files to app directory: C:\Users\Administrator.MS-20171007QKTN\AppData\Local\Httpschecker\app-2.0.1
2017-10-14 13:05:59> ApplyReleasesImpl: Moving file C:\Users\Administrator.MS-20171007QKTN\AppData\Local\Httpschecker\app-2.0.1\lib\net45\blink_image_resources_200_percent.pak to C:\Users\Administrator.MS-20171007QKTN\AppData\Local\Httpschecker\app-2.0.1\blink_image_resources_200_percent.pak
2017-10-14 13:05:59> ApplyReleasesImpl: Moving file C:\Users\Administrator.MS-20171007QKTN\AppData\Local\Httpschecker\app-2.0.1\lib\net45\content_resources_200_percent.pak to C:\Users\Administrator.MS-20171007QKTN\AppData\Local\Httpschecker\app-2.0.1\content_resources_200_percent.pak
2017-10-14 13:05:59> ApplyReleasesImpl: Moving file C:\Users\Administrator.MS-20171007QKTN\AppData\Local\Httpschecker\app-2.0.1\lib\net45\content_shell.pak to C:\Users\Administrator.MS-20171007QKTN\AppData\Local\Httpschecker\app-2.0.1\content_shell.pak
2017-10-14 13:06:00> ApplyReleasesImpl: Moving file C:\Users\Administrator.MS-20171007QKTN\AppData\Local\Httpschecker\app-2.0.1\lib\net45\d3dcompiler_47.dll to C:\Users\Administrator.MS-20171007QKTN\AppData\Local\Httpschecker\app-2.0.1\d3dcompiler_47.dll
2017-10-14 13:06:01> ApplyReleasesImpl: Moving file C:\Users\Administrator.MS-20171007QKTN\AppData\Local\Httpschecker\app-2.0.1\lib\net45\ffmpeg.dll to C:\Users\Administrator.MS-20171007QKTN\AppData\Local\Httpschecker\app-2.0.1\ffmpeg.dll
2017-10-14 13:06:01> ApplyReleasesImpl: Moving file C:\Users\Administrator.MS-20171007QKTN\AppData\Local\Httpschecker\app-2.0.1\lib\net45\Httpschecker.exe to C:\Users\Administrator.MS-20171007QKTN\AppData\Local\Httpschecker\app-2.0.1\Httpschecker.exe
2017-10-14 13:06:01> ApplyReleasesImpl: Moving file C:\Users\Administrator.MS-20171007QKTN\AppData\Local\Httpschecker\app-2.0.1\lib\net45\icudtl.dat to C:\Users\Administrator.MS-20171007QKTN\AppData\Local\Httpschecker\app-2.0.1\icudtl.dat
2017-10-14 13:06:01> ApplyReleasesImpl: Moving file C:\Users\Administrator.MS-20171007QKTN\AppData\Local\Httpschecker\app-2.0.1\lib\net45\libEGL.dll to C:\Users\Administrator.MS-20171007QKTN\AppData\Local\Httpschecker\app-2.0.1\libEGL.dll
2017-10-14 13:06:01> ApplyReleasesImpl: Moving file C:\Users\Administrator.MS-20171007QKTN\AppData\Local\Httpschecker\app-2.0.1\lib\net45\libGLESv2.dll to C:\Users\Administrator.MS-20171007QKTN\AppData\Local\Httpschecker\app-2.0.1\libGLESv2.dll
2017-10-14 13:06:01> ApplyReleasesImpl: Moving file C:\Users\Administrator.MS-20171007QKTN\AppData\Local\Httpschecker\app-2.0.1\lib\net45\LICENSE to C:\Users\Administrator.MS-20171007QKTN\AppData\Local\Httpschecker\app-2.0.1\LICENSE
2017-10-14 13:06:01> ApplyReleasesImpl: Moving file C:\Users\Administrator.MS-20171007QKTN\AppData\Local\Httpschecker\app-2.0.1\lib\net45\natives_blob.bin to C:\Users\Administrator.MS-20171007QKTN\AppData\Local\Httpschecker\app-2.0.1\natives_blob.bin
2017-10-14 13:06:01> ApplyReleasesImpl: Moving file C:\Users\Administrator.MS-20171007QKTN\AppData\Local\Httpschecker\app-2.0.1\lib\net45\node.dll to C:\Users\Administrator.MS-20171007QKTN\AppData\Local\Httpschecker\app-2.0.1\node.dll
2017-10-14 13:06:01> ApplyReleasesImpl: Moving file C:\Users\Administrator.MS-20171007QKTN\AppData\Local\Httpschecker\app-2.0.1\lib\net45\snapshot_blob.bin to C:\Users\Administrator.MS-20171007QKTN\AppData\Local\Httpschecker\app-2.0.1\snapshot_blob.bin
2017-10-14 13:06:01> ApplyReleasesImpl: Moving file C:\Users\Administrator.MS-20171007QKTN\AppData\Local\Httpschecker\app-2.0.1\lib\net45\squirrel.exe to C:\Users\Administrator.MS-20171007QKTN\AppData\Local\Httpschecker\app-2.0.1\squirrel.exe
2017-10-14 13:06:01> ApplyReleasesImpl: Moving file C:\Users\Administrator.MS-20171007QKTN\AppData\Local\Httpschecker\app-2.0.1\lib\net45\ui_resources_200_percent.pak to C:\Users\Administrator.MS-20171007QKTN\AppData\Local\Httpschecker\app-2.0.1\ui_resources_200_percent.pak
2017-10-14 13:06:01> ApplyReleasesImpl: Moving file C:\Users\Administrator.MS-20171007QKTN\AppData\Local\Httpschecker\app-2.0.1\lib\net45\views_resources_200_percent.pak to C:\Users\Administrator.MS-20171007QKTN\AppData\Local\Httpschecker\app-2.0.1\views_resources_200_percent.pak
2017-10-14 13:06:01> ApplyReleasesImpl: Moving file C:\Users\Administrator.MS-20171007QKTN\AppData\Local\Httpschecker\app-2.0.1\lib\net45\xinput1_3.dll to C:\Users\Administrator.MS-20171007QKTN\AppData\Local\Httpschecker\app-2.0.1\xinput1_3.dll
2017-10-14 13:06:29> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\Administrator.MS-20171007QKTN\AppData\Local\Httpschecker\app-2.0.1\Httpschecker.exe]
2017-10-14 13:06:36> ApplyReleasesImpl: Starting fixPinnedExecutables
2017-10-14 13:06:36> ApplyReleasesImpl: Examining Pin: Mozilla Firefox.lnk
2017-10-14 13:06:36> ApplyReleasesImpl: Examining Pin: Windows Explorer.lnk
2017-10-14 13:06:36> ApplyReleasesImpl: Fixing up tray icons
2017-10-14 13:06:36> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__13_0(RegistryView view)
2017-10-14 13:06:36> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__13_0(RegistryView view)
2017-10-14 13:06:36> ApplyReleasesImpl: cleanDeadVersions: for version 2.0.1
2017-10-14 13:06:36> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-2.0.1
2017-10-16 12:22:05> Program: Starting Squirrel Updater: --install .
2017-10-16 12:22:05> Program: Starting install, writing to C:\Users\Administrator.MS-20171007QKTN\AppData\Local\SquirrelTemp
2017-10-16 12:22:05> Program: About to install to: C:\Users\Administrator.MS-20171007QKTN\AppData\Local\ElectronAPIDemos
2017-10-16 12:22:06> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Administrator.MS-20171007QKTN\AppData\Local\ElectronAPIDemos\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2017-10-16 12:22:06> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Administrator.MS-20171007QKTN\AppData\Local\ElectronAPIDemos\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2017-10-16 12:22:06> CheckForUpdateImpl: Reading RELEASES file from C:\Users\Administrator.MS-20171007QKTN\AppData\Local\SquirrelTemp
2017-10-16 12:22:06> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2017-10-16 12:22:06> ApplyReleasesImpl: Writing files to app directory: C:\Users\Administrator.MS-20171007QKTN\AppData\Local\ElectronAPIDemos\app-1.3.0
2017-10-16 12:22:06> LogHost: Rigging execution stub for lib/net45/Electron API Demos_ExecutionStub.exe to C:\Users\Administrator.MS-20171007QKTN\AppData\Local\ElectronAPIDemos\Electron API Demos.exe
2017-10-16 12:22:48> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\Administrator.MS-20171007QKTN\AppData\Local\ElectronAPIDemos\app-1.3.0\Electron API Demos.exe]
2017-10-16 12:22:49> ApplyReleasesImpl: Starting fixPinnedExecutables
2017-10-16 12:22:49> ApplyReleasesImpl: Examining Pin: Mozilla Firefox.lnk
2017-10-16 12:22:49> ApplyReleasesImpl: Examining Pin: Windows Explorer.lnk
2017-10-16 12:22:49> ApplyReleasesImpl: Fixing up tray icons
2017-10-16 12:22:49> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__13_0(RegistryView view)
2017-10-16 12:22:49> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__13_0(RegistryView view)
2017-10-16 12:22:49> ApplyReleasesImpl: cleanDeadVersions: for version 1.3.0
2017-10-16 12:22:49> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.3.0
2017-10-16 13:20:53> Program: Starting Squirrel Updater: --install .
2017-10-16 13:20:53> Program: Starting install, writing to C:\Users\Administrator.MS-20171007QKTN\AppData\Local\SquirrelTemp
2017-10-16 13:20:53> Program: About to install to: C:\Users\Administrator.MS-20171007QKTN\AppData\Local\ElectronAPIDemos
2017-10-16 13:20:53> Program: Install path C:\Users\Administrator.MS-20171007QKTN\AppData\Local\ElectronAPIDemos already exists, burning it to the ground
2017-10-16 13:20:55> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Administrator.MS-20171007QKTN\AppData\Local\ElectronAPIDemos\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2017-10-16 13:20:55> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Administrator.MS-20171007QKTN\AppData\Local\ElectronAPIDemos\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2017-10-16 13:20:55> CheckForUpdateImpl: Reading RELEASES file from C:\Users\Administrator.MS-20171007QKTN\AppData\Local\SquirrelTemp
2017-10-16 13:20:55> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2017-10-16 13:20:55> ApplyReleasesImpl: Writing files to app directory: C:\Users\Administrator.MS-20171007QKTN\AppData\Local\ElectronAPIDemos\app-1.3.0
2017-10-16 13:20:55> LogHost: Rigging execution stub for lib/net45/Electron API Demos_ExecutionStub.exe to C:\Users\Administrator.MS-20171007QKTN\AppData\Local\ElectronAPIDemos\Electron API Demos.exe
2017-10-16 13:21:44> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\Administrator.MS-20171007QKTN\AppData\Local\ElectronAPIDemos\app-1.3.0\Electron API Demos.exe]
2017-10-16 13:21:45> ApplyReleasesImpl: Starting fixPinnedExecutables
2017-10-16 13:21:45> ApplyReleasesImpl: Examining Pin: Mozilla Firefox.lnk
2017-10-16 13:21:45> ApplyReleasesImpl: Examining Pin: Windows Explorer.lnk
2017-10-16 13:21:45> ApplyReleasesImpl: Fixing up tray icons
2017-10-16 13:21:45> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__13_0(RegistryView view)
2017-10-16 13:21:45> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__13_0(RegistryView view)
2017-10-16 13:21:45> ApplyReleasesImpl: cleanDeadVersions: for version 1.3.0
2017-10-16 13:21:45> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.3.0

**Comment by Inzanit** [comment]
I'm having a bit of trouble dissecting exactly what's wrong here? Looks like this could be closed unless there's some more information that could be provided by @songsammy @shiftkey
