### ISSUE TITLE
Can't write execution stub, probably in use: System.UnauthorizedAccessException: Access to the path is denied

### ISSUE THREAD

**Issue by ascot21** [Squirrel/Squirrel.Windows#1183]
I have a handful of customers that are getting an error when the installation process is trying to write one of the execution stubs.

The weird thing is that it seems to be successful for a few of these and then begins to fail.

I've tried clearing out the `AppData\Local\App` folder a few times and still get this issue.

SquirrelSetup.log is below.  What could be causing this?

```
2017-10-24 13:19:08> Program: Starting Squirrel Updater: --install .
2017-10-24 13:19:08> Program: Starting install, writing to C:\Users\holly\AppData\Local\SquirrelTemp
2017-10-24 13:19:08> Program: About to install to: C:\Users\holly\AppData\Local\Zinc
2017-10-24 13:19:08> Program: Install path C:\Users\holly\AppData\Local\Zinc already exists, burning it to the ground
2017-10-24 13:19:08> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\holly\AppData\Local\Zinc\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2017-10-24 13:19:08> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\holly\AppData\Local\Zinc\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2017-10-24 13:19:08> CheckForUpdateImpl: Reading RELEASES file from C:\Users\holly\AppData\Local\SquirrelTemp
2017-10-24 13:19:08> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2017-10-24 13:19:08> ApplyReleasesImpl: Writing files to app directory: C:\Users\holly\AppData\Local\Zinc\app-5.0.0
2017-10-24 13:19:09> LogHost: Rigging execution stub for lib/net45/Zinc_ExecutionStub.exe to C:\Users\holly\AppData\Local\Zinc\Zinc.exe
2017-10-24 13:19:09> LogHost: Rigging execution stub for lib/net45/resources/app.asar.unpacked/node_modules/node-notifier/vendor/toaster/toast_ExecutionStub.exe to C:\Users\holly\AppData\Local\Zinc\app-5.0.0\resources\app.asar.unpacked\node_modules\node-notifier\vendor\toast.exe
2017-10-24 13:19:09> LogHost: Rigging execution stub for lib/net45/resources/app.asar.unpacked/node_modules/node-notifier/vendor/notifu/notifu_ExecutionStub.exe to C:\Users\holly\AppData\Local\Zinc\app-5.0.0\resources\app.asar.unpacked\node_modules\node-notifier\vendor\notifu.exe
2017-10-24 13:19:09> LogHost: Rigging execution stub for lib/net45/resources/app.asar.unpacked/node_modules/node-notifier/vendor/notifu/notifu64_ExecutionStub.exe to C:\Users\holly\AppData\Local\Zinc\app-5.0.0\resources\app.asar.unpacked\node_modules\node-notifier\vendor\notifu64.exe
2017-10-24 13:19:10> LogHost: Can't write execution stub, probably in use: System.UnauthorizedAccessException: Access to the path 'C:\Users\holly\AppData\Local\Zinc\app-5.0.0\Zinc.exe' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at Squirrel.ReleasePackage.<>c__DisplayClass16_1.<ExtractZipForInstall>b__2()
   at Squirrel.Utility.<>c__DisplayClass8_0.<Retry>b__0()
   at Squirrel.Utility.Retry[T](Func`1 block, Int32 retries)
   at Squirrel.Utility.Retry(Action block, Int32 retries)
   at Squirrel.ReleasePackage.<>c__DisplayClass16_0.<ExtractZipForInstall>b__0(ZipEntry zipEntry)
2017-10-24 13:19:10> LogHost: Can't write execution stub, probably in use: System.UnauthorizedAccessException: Access to the path 'C:\Users\holly\AppData\Local\Zinc\app-5.0.0\resources\app.asar' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at Squirrel.ReleasePackage.<>c__DisplayClass16_1.<ExtractZipForInstall>b__2()
   at Squirrel.Utility.<>c__DisplayClass8_0.<Retry>b__0()
   at Squirrel.Utility.Retry[T](Func`1 block, Int32 retries)
   at Squirrel.Utility.Retry(Action block, Int32 retries)
   at Squirrel.ReleasePackage.<>c__DisplayClass16_0.<ExtractZipForInstall>b__0(ZipEntry zipEntry)
2017-10-24 13:19:10> LogHost: Rigging execution stub for lib/net45/resources/app.asar.unpacked/node_modules/7zip-bin-win/ia32/7za_ExecutionStub.exe to C:\Users\holly\AppData\Local\Zinc\app-5.0.0\resources\app.asar.unpacked\node_modules\7zip-bin-win\7za.exe
2017-10-24 13:19:10> LogHost: Can't write execution stub, probably in use: System.UnauthorizedAccessException: Access to the path 'C:\Users\holly\AppData\Local\Zinc\app-5.0.0\resources\app.asar.unpacked\node_modules\7zip-bin-win\package.json' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at Squirrel.ReleasePackage.<>c__DisplayClass16_1.<ExtractZipForInstall>b__2()
   at Squirrel.Utility.<>c__DisplayClass8_0.<Retry>b__0()
   at Squirrel.Utility.Retry[T](Func`1 block, Int32 retries)
   at Squirrel.Utility.Retry(Action block, Int32 retries)
   at Squirrel.ReleasePackage.<>c__DisplayClass16_0.<ExtractZipForInstall>b__0(ZipEntry zipEntry)
2017-10-24 13:19:11> IEnableLogger: Failed to install package to app dir: System.UnauthorizedAccessException: Access to the path 'C:\Users\holly\AppData\Local\Zinc\app-5.0.0\resources\app.asar' is denied.
   at Squirrel.ReleasePackage.<>c__DisplayClass16_0.<ExtractZipForInstall>b__0(ZipEntry zipEntry)
   at Squirrel.Utility.<>c__DisplayClass12_1`1.<ForEachAsync>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.ReleasePackage.<ExtractZipForInstall>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass7_0.<<installPackageToAppDir>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__36`1.MoveNext()
2017-10-24 13:19:11> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.UnauthorizedAccessException: Access to the path 'C:\Users\holly\AppData\Local\Zinc\app-5.0.0\resources\app.asar' is denied.
   at Squirrel.ReleasePackage.<>c__DisplayClass16_0.<ExtractZipForInstall>b__0(ZipEntry zipEntry)
   at Squirrel.Utility.<>c__DisplayClass12_1`1.<ForEachAsync>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.ReleasePackage.<ExtractZipForInstall>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass7_0.<<installPackageToAppDir>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__36`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<FullInstall>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.UnauthorizedAccessException: Access to the path 'C:\Users\holly\AppData\Local\Zinc\app-5.0.0\resources\app.asar' is denied.
   at Squirrel.ReleasePackage.<>c__DisplayClass16_0.<ExtractZipForInstall>b__0(ZipEntry zipEntry)
   at Squirrel.Utility.<>c__DisplayClass12_1`1.<ForEachAsync>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.ReleasePackage.<ExtractZipForInstall>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass7_0.<<installPackageToAppDir>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__36`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<FullInstall>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()<---
```

**Comment by zjsyd** [comment]
Same issue here. Any update?

**Comment by januszc** [comment]
I found solution for this

Go to C:\Users\<YourUserName>\AppData\Local\

Create Folder

Zinc

And inside this folder create folder

packages

And run installation again.

**Comment by pettys** [comment]
I have a user experiencing the same issue. The solution @januszc proposed did not work for this one.

**Comment by pettys** [comment]
Some more details from my research on this issue - really interested if anyone can shed some light on what Windows is doing here.

- The problematic file was trying to write to `c:\users\<me>\AppData\Local\<us>\MyApp.exe`
- The logs were
   - `LogHost: Rigging execution stub for MyApp_ExecutionStub.exe to C:\...\<us>\MyApp.exe`
   - `LogHost: Can't write execution stub, probably in use: System.UnauthorizedAccessException: Access to the path 'C:\Users\<me>\AppData\Local\<us>\MyApp.exe' is denied.
- I manually extracted MyApp_ExecutionStub.exe from the package, and I could put it in the folder **no problem**.
- I manually extracted the file, renamed it to MyApp.exe, tried to place it in the <us> folder: *Access Denied*.
- I grabbed a random text file, renamed it to MyApp.exe, tried to place in <us> folder: *Access Denied.*
- I deleted the <us> folder, manually recreated it, and the behavior was the same.
- I renamed <us> to <us2>, and then I **could** create a MyApp.exe in <us2>. I could even rename <us2> back to <us> and it was fine.
- Delete MyApp.exe, then try to put it back: *Access Denied.*
- Restart the computer, problem is gone. Everything's fine now.

**Anyone know what kind of lock Windows would be doing that you can't create a file with a certain name in a certain folder?**

**Comment by lukeskinner** [comment]
@pettys I've seen BitDefender do this on around 5 different pcs. A reboot is the only fix, manually adding exclusions or disabling the AV does not fix it. The solution for me was to reboot, disable BitDefender and then continue with the install.

**Comment by pettys** [comment]
@lukeskinner Big thanks for noting this - we are also experiencing problems on PC's with BitDefender, and I don't think I would have realized the connection for quite a while. Now I know where to start looking - thanks a bunch!

**Comment by paulcbetts** [comment]
Unfortunately, because of what Squirrel inherently is, a way to install and update executables, Antivirus is always going to be a problem. Make sure to sign your installers, which helps a ton against this.

**Comment by pettys** [comment]
Thanks for the tip on signing, @paulcbetts - we haven't gotten that far yet, and your having mentioned that will make this a higher priority for us.
