### ISSUE TITLE
msi machine-wide installer doesn't create any links

### ISSUE THREAD

**Issue by media4learning** [Squirrel/Squirrel.Windows#1196]
Hi,

I am using squirrel to create an msi installer. I run the installer and it dies half way through. I restart the machine and the app pops up after a few minutes. It is located in %APPDATA%/local/appName but there is no way for an average user to start the app. Nothing pinned to start menu, nothing in taskbar and nothing on desktop.

Log file for install is 👍 
2017-11-06 18:11:21> Program: Starting Squirrel Updater: --install . --checkInstall --silent
2017-11-06 18:11:21> Program: Starting install, writing to C:\Users\chris\AppData\Local\SquirrelTemp
2017-11-06 18:11:21> Program: About to install to: C:\Users\chris\AppData\Local\AVCPG
2017-11-06 18:11:21> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\chris\AppData\Local\AVCPG\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2017-11-06 18:11:21> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\chris\AppData\Local\AVCPG\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2017-11-06 18:11:21> CheckForUpdateImpl: Reading RELEASES file from C:\Users\chris\AppData\Local\SquirrelTemp
2017-11-06 18:11:21> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2017-11-06 18:11:21> ApplyReleasesImpl: Writing files to app directory: C:\Users\chris\AppData\Local\AVCPG\app-0.0.1
2017-11-06 18:11:24> LogHost: Rigging execution stub for AVCPG_ExecutionStub.exe to C:\Users\chris\AppData\Local\AVCPG\AVCPG.exe
2017-11-06 18:12:40> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\chris\AppData\Local\AVCPG\app-0.0.1\AVCPG.exe]
2017-11-06 18:12:56> ApplyReleasesImpl: Couldn't run Squirrel hook, continuing: C:\Users\chris\AppData\Local\AVCPG\app-0.0.1\AVCPG.exe: System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Squirrel.Utility.<>c__DisplayClass11_0.<InvokeProcessAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<InvokeProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass10_0.<<invokePostInstall>b__0>d.MoveNext()
2017-11-06 18:12:56> ApplyReleasesImpl: Starting fixPinnedExecutables
2017-11-06 18:12:56> ApplyReleasesImpl: Examining Pin: Atom.lnk
2017-11-06 18:12:56> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2017-11-06 18:12:56> ApplyReleasesImpl: Examining Pin: Internet Explorer.lnk
2017-11-06 18:12:56> ApplyReleasesImpl: Fixing up tray icons
2017-11-06 18:12:56> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__13_0(RegistryView view)
2017-11-06 18:12:56> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__13_0(RegistryView view)
2017-11-06 18:12:56> ApplyReleasesImpl: cleanDeadVersions: for version 0.0.1
2017-11-06 18:12:56> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.0.1

Any thoughts?

**Comment by paulcbetts** [comment]
You uninstalled the app, then installed the MSI. Delete `%LocalAppData%\YOURAPP` and try again

**Comment by media4learning** [comment]
Ok so I did that. I now have a link in the task bar (bottom bar - sorry not a Windows user anymore).

Can I just confirm that the following steps are intended behaviour.

1. Run MSI - it flashes up like it is installing then closes midway through progress bar. Nothing happens'
2. User finally restarts their machine, app installs and runs automatically. App the closes automatically after staying open for about 10 seconds. 
3. There is now an icon in the task bar. No icon in start menu and search start menu for the app name does not show any result for the app.

I feel like this is very clunky but if it is intended behaviour then so be it. 
Is there a way to create an installer that runs like a normal Windows installer most applications have - that adds a desktop icon and installs the program in the Program Files folder?

**Comment by paulcbetts** [comment]
> I feel like this is very clunky but if it is intended behaviour then so be it.

Yep, the MSI that Squirrel generates is specifically *only* for the group policy deployment scenario, where the user running the MSI file is an Admin account (i.e. not the person actually using the computer day-to-day).  For a standard installer, you want to use the EXE file.
