### ISSUE TITLE
How does --install work?

### ISSUE THREAD

**Issue by vadi2** [Squirrel/Squirrel.Windows#1202]
I'm doing the following:

```
C:\Users\User\AppData\Local\Mudlet>Update.exe --install=raah --silent
```

But it doesn't quite work:

```
2017-11-10 17:19:30> Program: Starting Squirrel Updater: --install=raah --silent
2017-11-10 17:19:30> Program: Starting install, writing to C:\Users\User\AppData\Local\Mudlet\raah
2017-11-10 17:19:30> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()
```

I do have the package in this folder as it expects:

```
C:\Users\User\AppData\Local\Mudlet>dir raah
 Volume in drive C is OS
 Volume Serial Number is B00C-E021

 Directory of C:\Users\User\AppData\Local\Mudlet\raah

10-11-2017  17:19    <DIR>          .
10-11-2017  17:19    <DIR>          ..
09-11-2017  18:18        25.493.171 Mudlet-3.5.7-full.nupkg
10-11-2017  17:08                 3 RELEASES
               2 File(s)     25.493.174 bytes
               2 Dir(s)  144.752.164.864 bytes free

C:\Users\User\AppData\Local\Mudlet>
```

What am I doing wrong?

**Comment by vadi2** [comment]
Looks like it wants the `RELEASES` file that was generated as well.
