### ISSUE TITLE
Unable to find file/create a delta file as a result

### ISSUE THREAD

**Issue by lenigod** [Squirrel/Squirrel.Windows#1216]
When running a new release, i'm getting caught up on this error. I have always run these releases the same way, by running a deploy script in my project folder, and it's always worked fine this way, for some reason it's breaking now....

2017-12-11 16:45:46> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.ComponentModel.Win32Exception: The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Squirrel.Utility.<InvokeProcessAsync>d__11.MoveNext()

there is a bit more, but it's cascading from this with more file not founds

**Comment by Thieum** [comment]
@lenigod is this still an issue with the latest version of Squirrel?

**Comment by lenigod** [comment]
I'll have to double check on this sorry. I haven't used squirrel in a while
