### ISSUE TITLE
Issues with updating

### ISSUE THREAD

**Issue by stefanolson** [Squirrel/Squirrel.Windows#122]
I am getting error reports with a couple of issues when updating.  

First one is:

```
[Exception]:[System.UnauthorizedAccessException: Access to the path 'C:\Users\[...]\AppData\Local\LegacyDocs\app-1.0.195\ICSharpCode.SharpZipLib.dll' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at Squirrel.Utility.<DeleteDirectory>b__29(String file)
   at Squirrel.Utility.<>c__DisplayClass16`1.<>c__DisplayClass18.<ForEachAsync>b__15()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass1c`1.<>c__DisplayClass1e.<<ForEachAsync>b__1b>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<DeleteDirectory>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<installPackageToAppDir>d__85.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__45`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__5b.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<ApplyReleases>d__a.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at [...]
[OccurrenceDate]:[Mon, 03 Nov 2014 15:12:18 GMT] [AppVersion]:[1.0.195.0] 
```

That weird thing is that the user is already running the latest version 1.0.195.0!

Here is the code that I use to do the update:

``` csharp
using (var updateManager = new UpdateManager(LoginStatus.Current.CurrentUser.BaseAddress.TrimEnd('/') + "/setup",
    "LegacyDocs", FrameworkVersion.Net45))
{
    UpdateInfo updateInfo;
    using (StatusBarTrayManager.CreateNewStatusItem("Checking for application updates"))
    {
        // then update the app
        updateInfo = await updateManager.CheckForUpdate();

        if (updateInfo == null)
        {
            return false;
        }
        if (!updateInfo.ReleasesToApply.Any())
        {
            return false;
        }
    }

    MainWindow.G_MainWindow.IsInstallingUpdate = true;

    using (var updateStatusBarItem = StatusBarTrayManager.CreateNewStatusItem("Updating application"))
    {
        updateStatusBarItem.Maximum = 100;
        var releases = updateInfo.ReleasesToApply;

        await updateManager.DownloadReleases(releases, p => updateStatusBarItem.CurrentValue = p);

        string results = await updateManager.ApplyReleases(updateInfo);

        // setup uninstall
        await updateManager.CreateUninstallerRegistryEntry();
        _updateChecked = true;
        MainWindow.G_MainWindow.IsInstallingUpdate = false;
        MainWindow.G_MainWindow.HasInstalledUpdate = true;
        // do nothing with results?
        return true;
    }
}
```

So I am not clear why it is even trying to update...

Second one is:

```
[Exception]:[System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Squirrel.Utility.FindCurrentVersion(IEnumerable`1 localReleases)
   at Squirrel.UpdateManager.CheckForUpdateImpl.determineUpdateInfo(IEnumerable`1 localReleases, IEnumerable`1 remoteReleases, Boolean ignoreDeltaUpdates)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at OlsonSoftware.LegacyDocumentSystem.DomainClasses.ApplicationUpdater.<UpdateApplication>d__4.MoveNext()]
[OccurrenceDate]:[Mon, 03 Nov 2014 11:24:21 GMT] [AppVersion]:[1.0.194.0] 
```

This person isn't running the latest version, but given that other people have upgraded correctly I don't know why it says there is more than one matching element?

Stefan

**Comment by plinehan** [comment]
FWIW the "Sequence contains more than one matching element" error could be related to #578.

**Comment by Thieum** [comment]
@stefanolson was virtualbox involved in the process? You have some duplication:

4A70EDE1B57F081AEA3CF983BD301900581AC44B LegacyDocs-1.0.194-delta.nupkg 32134
4A70EDE1B57F081AEA3CF983BD301900581AC44B LegacyDocs-1.0.194-delta.nupkg 32134
2BFC88826E7DE4002B074381114CB106BD3927E8 LegacyDocs-1.0.194-full.nupkg 16298214
2BFC88826E7DE4002B074381114CB106BD3927E8 LegacyDocs-1.0.194-full.nupkg 16298214

like reported in #578

**Comment by stefanolson** [comment]
No, built on a Windows machine,  but I'm still having the problems with files being unable to be written to, but I think the best thing to do at this point is close this one because there are multiple issues involved most of which are fixed. I can reopen a new one later.
