### ISSUE TITLE
Releasify fails if -i specified

### ISSUE THREAD

**Issue by Esardes** [Squirrel/Squirrel.Windows#1256]
I'm trying to releasify my nuspec (via package manager console). Works smoothly without an icon, but when I specify it it fails with stack:
```
Squirrel : System.AggregateException: One or more errors occurred. ---> System.Exception: Failed to modify resources, command invoked was: 'C:\Users\john\Documents\Repos\Win\MyAppWindows\packages\squirrel.windows.1.6.0\tools\rcedit.exe 
"C:\Users\john\Documents\Repos\Win\MyAppWindows\Releases\Setup.exe" --set-version-string "CompanyName" "authors" --set-version-string "LegalCopyright" "Copyright 2016" --set-version-string "FileDescription" "description" --set-version-string 
"ProductName" "description" --set-file-version 0.2.1 --set-product-version
0.2.1 --set-icon "C:\Users\john\Documents\Repos\Win\MyAppWindows\MyAppWindows\Resources\my_launcher.ico"'
At line:1 char:1
+ Squirrel --releasify .\MyAppWindows\bin\Release\MyApp.$ve ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (System.Aggregat..._launcher.ico"':String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 

Output was:
Fatal error: Unable to set icon
   at Squirrel.Update.Program.<setPEVersionInfoAndIcon>d__20.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Squirrel.Update.Program.<>c__DisplayClass10_0.<Releasify>b__14()
   at Squirrel.Utility.<>c__DisplayClass8_0.<Retry>b__0()
   at Squirrel.Utility.Retry[T](Func`1 block, Int32 retries)
   at Squirrel.Utility.Retry(Action block, Int32 retries)
   at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon, Boolean generateMsi, String frameworkVersion)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)
---> (Inner Exception #0) System.Exception: Failed to modify resources, command invoked was: 'C:\Users\john\Documents\Repos\Win\MyAppWindows\packages\squirrel.windows.1.6.0\tools\rcedit.exe 
"C:\Users\john\Documents\Repos\Win\MyAppWindows\Releases\Setup.exe" --set-version-string "CompanyName" "authors" --set-version-string "LegalCopyright" "Copyright 2016" --set-version-string "FileDescription" "description" --set-version-string 
"ProductName" "description" --set-file-version 0.2.1 --set-product-version
0.2.1 --set-icon "C:\Users\john\Documents\Repos\Win\MyAppWindows\MyAppWindows\Resources\my_launcher.ico"'

Output was:
Fatal error: Unable to set icon
   at Squirrel.Update.Program.<setPEVersionInfoAndIcon>d__20.MoveNext()<--
```

**Comment by MrBjorn** [comment]
I got the same problem. Did you get any solution to this?

**Comment by Esardes** [comment]
@MrBjorn no I had to give up on using the proper icon for the installer

**Comment by Thieum** [comment]
@Esardes @MrBjorn Are you still experiencing this issue with the latest version of Squirrel?
