### ISSUE TITLE
Couldn't aquire lock, is another instance running?

### ISSUE THREAD

**Issue by roh85** [Squirrel/Squirrel.Windows#1258]
I am implementing squirrel into a win forms application. I get an exception when installing or updating the application.

```
Args:--squirrel-install
Args:4.3.4
System.AggregateException: One or more errors occurred. ---> System.Exception: Couldn't acquire lock, is another instance running
   at Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut)
   at Squirrel.UpdateManager.<acquireUpdateLock>b__32_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Dynafix.UserPortal.Program.Main(String[] args)
---> (Inner Exception #0) System.Exception: Couldn't acquire lock, is another instance running
   at Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut)
   at Squirrel.UpdateManager.<acquireUpdateLock>b__32_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()<---
Args:--squirrel-firstrun
EnableVisualStylesSkinmanager
Init config
Check folder rights
Creating dirs
```

The implementation is currently done in the program.cs

```
                    //check if application is running with squirrel
                    var assm = Assembly.GetEntryAssembly();
                    var updateDotExe = Path.Combine(Path.GetDirectoryName(assm.Location), "..", "Update.exe");
                    var isSquirrelInstall = File.Exists(updateDotExe);

                    if (isSquirrelInstall)
                    {
                        // Check for Squirrel application update
                        ReleaseEntry release = null;
                        
                        using (var mgr = new UpdateManager("C:\\Projects\\MyApp\\Releases"))
                        {
                            var updates = mgr.CheckForUpdate().Result;
                            if (updates.ReleasesToApply.Any()) // Check if we have any update
                            {
                                System.Reflection.Assembly assembly =
                                    System.Reflection.Assembly.GetExecutingAssembly();
                                FileVersionInfo fvi = FileVersionInfo.GetVersionInfo(assembly.Location);

                                string msg = "New version available!" +
                                             "\n\nCurrent version: " +
                                             updates.CurrentlyInstalledVersion.Version +
                                             "\nNew version: " + updates.FutureReleaseEntry.Version +
                                             "\n\nUpdate application now?";
                                DialogResult dialogResult = MessageBox.Show(msg, fvi.ProductName, MessageBoxButtons.YesNo, MessageBoxIcon.Question);
                                if (dialogResult == DialogResult.Yes)
                                {
                                    var lastversion = updates.ReleasesToApply.OrderBy(x => x.Version).Last();
                                    File.AppendAllText("D:\\up.log", "LastVersion: " + lastversion + System.Environment.NewLine);
                                    var entry =  mgr.DownloadReleases(new[] { lastversion });
                                    File.AppendAllText("D:\\up.log", "Entry: " + entry.ToString() + System.Environment.NewLine);
                                    var result = mgr.ApplyReleases(updates).Result;
                                    release = mgr.UpdateApp().Result;
                                }
                            }
                        }

                        // Restart the app
                        if (release != null)
                        {
                            File.AppendAllText("D:\\up.log", "Restart App" + System.Environment.NewLine);
                            UpdateManager.RestartApp();
                        }  

```
The errors are thrown when executing the mgr.UpdateApp. I see that squirrel is able to create the lock file in the temp directory, but the lock file does not contain any content. I suspect  that squirrel is not able to write content the this file and throws an exception. 
Using ProcessExplorer and procmon I see that the application is started 2 times with different arguments. 
The above code is executed first thing in the main method of the program.cs.

I do not have this issue on my surface tablet, but only on my development machine. It worked great the first few runs and at some point I started received these errors and I cannot pinpoint the exact cause. 

Squirrel used splat logging, maybe this logging can show some more info on the exact cause. where are the logs located?

**Comment by paulcbetts** [comment]
Don't check for updates during your initial install
