### ISSUE TITLE
Error while releasifying - Squirrel : System.ArgumentException: Part URI is not valid per rules defined in the Open Packaging Conventions specification. At line:1 char:1 + Squirrel --releasify RiverFox1.0.0.nupkg

### ISSUE THREAD

**Issue by joelybahh** [Squirrel/Squirrel.Windows#1266]
Get this error now when trying to releasify.

**Comment by joelybahh** [comment]
CategoryInfo          : NotSpecified: (System.Argument... specification.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
   at System.IO.Packaging.PackUriHelper.ValidatePartUri(Uri partUri)
   at System.IO.Packaging.ZipPackage.ContentTypeHelper.ProcessOverride
TagAttributes(XmlTextReader reader)
   at System.IO.Packaging.ZipPackage.ContentTypeHelper.ParseContentTypesFile(ZipFileInfoCollection zipFiles)
   at System.IO.Packaging.ZipPackage.ContentTypeHelper..ctor(ZipArchive zipArchive, IgnoredItemHelper ignoredItemHelper)
   at System.IO.Packaging.ZipPackage..ctor(Stream s, FileMode mode, FileAccess access, Boolean streaming)
   at System.IO.Packaging.Package.Open(Stream stream, FileMode packageMode, FileAccess packageAccess, Boolean streaming)
   at System.IO.Packaging.Package.Open(Stream stream)
   at NuGet.ZipPackage.EnsureManifest()
   at NuGet.ZipPackage..ctor(String filePath, Boolean enableCaching)
   at Squirrel.ReleasePackage.get_SuggestedReleaseFileName()
   at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon, Boolean 
generateMsi, String frameworkVersion, Boolean generateDeltas)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)

**Comment by joelybahh** [comment]
Ok so I've also identified that releasifying is only failing while I have the Unity build in there, which Is required. I have realisified like this before, same structure etc. And I can't find anything in the build that could be causing this. 

But releasifies fine when I remove everything except the Updater.exe and associated dlls. 
Any ideas on how to get it releasifying with everything again?

**Comment by AlecBoutin** [comment]
How would you rename the file after releasifying? Custom squirrel events don't seem like an option because there's no way to run code in unity before the resolution picker dialog, which relies on that file.

**Comment by bddckr** [comment]
You'll need to ship another executable that starts your Unity executable. That way that new executable can be a SquirrelAware app and just do the needed rename back to the original name in the Squirrel install handler.

Additionally if you're using Unity 2017 or later they changed the way a standalone player works:
>Windows: The player executable has been split into two parts: a signed UnityPlayer.dll that has all the engine code, and a wrapper executable that merely calls into this DLL at startup. The source code for the executable can be found under Editor\Data\WindowsStandaloneSupport\Source\WindowsPlayer. It can be rebuilt with VS2015 as long as you have "Common Tools for Visual C++ 2015" and "Windows XP Support for C++" installed.

So I'd guess you probably just can edit that wrapper executable already and handle the Squirrel installation event yourself in C++ using [Custom Squirrel Events (Non-C# Apps)](https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/custom-squirrel-events-non-cs.md).

**Comment by paulcbetts** [comment]
I would actually just ship a C# "SquirrelHelper.exe" that is marked as Squirrel-aware and creates shortcuts for the Unity app instead of itself. Your helper doesn't have to create shortcuts for itself

**Comment by Thieum** [comment]
@joelybahh did the solution proposed by @anaisbetts fixed your issue? if so, you can close this.

**Comment by Goxiaoy** [comment]
#414

**Comment by bddckr** [comment]
We're using Squirrel 1.8.0 which still has this issue of escaping spaces in (some?) file paths.

One would think the linked #414 is related and therefore #650 fixed it, as was assumed and therefore closed... This is an ongoing issue still, which is also visible by the fact that this issue was opened **two years after** the PR that is supposedly fixing the issue was merged.

**Comment by Thieum** [comment]
could be related to #1141

**Comment by paulrahme** [comment]
I'm getting this error when including files without an extension which are part of a Unity build. In the ..._Data subfolder, are 2 files, "level0" and "level0.resS"; including the level0 without extension causes Squirrel.exe to quit out with this error.

Using Squirrel 1.9.1.
