### ISSUE TITLE
Squirrel not launching app

### ISSUE THREAD

**Issue by donnib** [Squirrel/Squirrel.Windows#1269]
Hi,
1. Shortcuts are being created
2. I can launch app from shortcuts.

However -> the application does not get launched after installation. Here is the log :

```
2018-03-12 09:42:45> Program: Starting Squirrel Updater: --install .
2018-03-12 09:42:45> Program: Starting install, writing to C:\Users\USERNAME\AppData\Local\SquirrelTemp
2018-03-12 09:42:45> Program: About to install to: C:\Users\USERNAME\AppData\Local\My_Company_App_beta
2018-03-12 09:42:45> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\USERNAME\AppData\Local\My_Company_App_beta\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2018-03-12 09:42:45> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\USERNAME\AppData\Local\My_Company_App_beta\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2018-03-12 09:42:45> CheckForUpdateImpl: Reading RELEASES file from C:\Users\USERNAME\AppData\Local\SquirrelTemp
2018-03-12 09:42:45> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2018-03-12 09:42:45> ApplyReleasesImpl: Writing files to app directory: C:\Users\USERNAME\AppData\Local\My_Company_App_beta\app-0.1.0
2018-03-12 09:42:45> LogHost: Rigging execution stub for CoreOffice_ExecutionStub.exe to C:\Users\USERNAME\AppData\Local\My_Company_App_beta\MyCompanyApp.exe
2018-03-12 09:42:45> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\USERNAME\AppData\Local\My_Company_App_beta\app-0.1.0\MyCompanyApp.exe]
2018-03-12 09:42:46> ApplyReleasesImpl: Starting fixPinnedExecutables
2018-03-12 09:42:46> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2018-03-12 09:42:46> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2018-03-12 09:42:46> ApplyReleasesImpl: Examining Pin: Outlook 2016.lnk
2018-03-12 09:42:46> ApplyReleasesImpl: Examining Pin: SourceTree.lnk
2018-03-12 09:42:46> ApplyReleasesImpl: Examining Pin: Visual Studio 2017.lnk
2018-03-12 09:42:46> ApplyReleasesImpl: Examining Pin: Visual Studio Code.lnk
2018-03-12 09:42:46> ApplyReleasesImpl: Examining Pin: VNC® Viewer.lnk
2018-03-12 09:42:46> ApplyReleasesImpl: Fixing up tray icons
2018-03-12 09:42:46> ApplyReleasesImpl: cleanDeadVersions: for version 0.1.0
2018-03-12 09:42:46> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.1.0
```

**Comment by donnib** [comment]
Never mind, it seems like it did but there was an fatal exception in the app at launch i did not see.
