### ISSUE TITLE
Signing w/ Certificate errors

### ISSUE THREAD

**Issue by tygor** [Squirrel/Squirrel.Windows#1307]
`Squirrel --releasify` errors when using the `--signWithParams` option. It seems to operate normally without signing.

When signing with `releasify` it fails to even create the `tempa` and `tempb` folders in `SquirrelTemp`. This is likely why the `DeltaCompressionDotNet.dll` file can not be signed (it's not there). Previous failures with other DLLs higher up the alphanumeric sorting scale would show first, so it's probably just the first file being attempted that fails.

I've tried fresh install of Squirrel.Windows, cleaning out the .nupkg files, cleaning the `Release` folder, restarting Visual Studio, etc. Any other advice?

SquirrelSetup.log:
```
2018-05-01 10:50:46> Program: Starting Squirrel Updater: --releasify .\bin\Release\MyApp.2.0.10.nupkg --signWithParams /a /f .\Certificate.pfx /p REDACTED /fd sha256 /tr http://timestamp.digicert.com /td sha256
2018-05-01 10:50:46> Program: Bootstrapper EXE found at:%UserProfile%\.nuget\packages\squirrel.windows\1.8.0\tools\Setup.exe
2018-05-01 10:50:46> Program: Creating release package: .\Release\MyApp.2.0.10.nupkg
2018-05-01 10:50:47> ReleasePackage: Creating release package: .\Release\MyApp.2.0.10.nupkg => .\Release\MyApp-2.0.10-full.nupkg
2018-05-01 10:50:47> ReleasePackage: Extracting dependent packages: []
2018-05-01 10:50:47> ReleasePackage: Removing unnecessary data
2018-05-01 10:50:47> Program: About to sign %UserProfile%\AppData\Local\SquirrelTemp\tempa\lib\net45\DeltaCompressionDotNet.dll
2018-05-01 10:50:48> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.Exception: Failed to sign, command invoked was: '%UserProfile%\.nuget\packages\squirrel.windows\1.8.0\tools\signtool.exe sign /a /f .\Certificate.pfx /p ******** %UserProfile%\AppData\Local\SquirrelTemp\tempa\lib\net45\DeltaCompressionDotNet.dll'
   at Squirrel.Update.Program.<signPEFile>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<>c__DisplayClass10_1.<<Releasify>b__9>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Squirrel.Update.Program.<>c__DisplayClass10_1.<Releasify>b__2(String pkgPath)
   at Squirrel.ReleasePackage.CreateReleasePackage(String outputFile, String packagesRootDir, Func`2 releaseNotesProcessor, Action`1 contentsPostProcessHook)
   at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon, Boolean generateMsi, String frameworkVersion, Boolean generateDeltas)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.Exception: Failed to sign, command invoked was: '%UserProfile%\.nuget\packages\squirrel.windows\1.8.0\tools\signtool.exe sign /a /f .\Certificate.pfx /p ******** %UserProfile%\AppData\Local\SquirrelTemp\tempa\lib\net45\DeltaCompressionDotNet.dll'
   at Squirrel.Update.Program.<signPEFile>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<>c__DisplayClass10_1.<<Releasify>b__9>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()<---
```

**Comment by paulcbetts** [comment]
What happens when you run the command in the call stack directly?

**Comment by tygor** [comment]
The folder `%UserProfile%\AppData\Local\SquirrelTemp\tempa\` is empty. It's as if the .nupkg was never extracted to the SquirrelTemp folder. Running the signtool.exe directly would fail too.

**Comment by paulcbetts** [comment]
Do you have 3rd-party Antivirus and can you disable it

**Comment by tygor** [comment]
That'll require some assistance. I'll have to get back to you.

**Comment by tygor** [comment]
Ok, anti-virus disabled and yet the same results. This would make sense from what I know of how Squirrel works since without the -n flag --releasify works as expected; I even see the tempa and tempb folders for a second.

Still not working with -n flag. It's odd since this all worked on the 30th with a different application.

**Comment by tygor** [comment]
Well, I've found an alternative that seems to be working. I've scripted the whole nuget pack and squirrel --releasify in PowerShell and will run it from PowerShell.

**Comment by rajbos** [comment]
Hi @tygor,

we are hitting the same issue today. Can you indicate how you fixed this then? 

Are you running the nuget pack command by hand first?

**Comment by rajbos** [comment]
@tygor . We first found an issue with the passing of the password (Visible in PowerShell by only being obfuscated partially, so 'Pass@w0rd' became '*****@w0rd'.

Then we found an issue with the certificate we were using: it wasn't generated with CodeSigning as the usage, so the signtool would give an error indicating so.

The problem lies with the calls to the signtool: errors aren't shown back to the caller, thus not helpful at all.

**Comment by craigburtonAJB** [comment]
I'm still getting this with squirrel.windows v1.9.1 - without -n, --releasify is fine, with -n no joy (VS Nuget Package Manager console). The signtool command looking for the unpacked files in SQUIRREL_TEMP\tempa\etc, but the files aren't there. Is the solution _don't do that, use a script like @tygor 's_ ?
