### ISSUE TITLE
Desktop shortcut - System.ArgumentException: Illegal characters in path

### ISSUE THREAD

**Issue by zJesusJavier** [Squirrel/Squirrel.Windows#1319]
Hi! I'm installing my Electron app but I have this problem, the desktop shortcut is no longer being created, It was working fine a couple of hours before, but now I'm getting this error:

## **SquirrelSetup.log**

```
2018-05-16 19:43:22> Program: Starting Squirrel Updater: --createShortcut ERCGK.exe
2018-05-16 19:43:22> ApplyReleasesImpl: About to create shortcuts for ERCGK.exe, rootAppDir C:\Users\SoulO\AppData\Local\ercgk
2018-05-16 19:43:23> Unhandled exception: System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2, String path3)
   at Squirrel.UpdateManager.ApplyReleasesImpl.getLinkTarget(ShortcutLocation location, String title, String applicationName, Boolean createDirectoryIfNecessary)
   at Squirrel.UpdateManager.ApplyReleasesImpl.linkTargetForVersionInfo(ShortcutLocation location, IPackage package, FileVersionInfo versionInfo)
   at Squirrel.UpdateManager.ApplyReleasesImpl.CreateShortcutsForExecutable(String exeName, ShortcutLocation locations, Boolean updateOnly, String programArguments, String icon)
   at Squirrel.Update.Program.Shortcut(String exeName, String shortcutArgs, String processStartArgs, String icon)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
```

## **main.js**

```
const electron = require('electron')
const app = electron.app

if (handleSquirrelEvent(app)) 
{
    return;
}

const BrowserWindow = electron.BrowserWindow
const path = require('path')
const url = require('url')

let mainWindow

function createWindow() 
{
    mainWindow = new BrowserWindow(
	{
        movable: false,
        transparent: true,
        icon: path.join(__dirname, 'img/favicon.png'),
        
	})

    mainWindow.maximize()
    mainWindow.show()
    mainWindow.loadURL(`file://${__dirname}/load.html`)
	mainWindow.on('closed', function() 
	{
        mainWindow = null
    })
}

app.on('ready', createWindow)

app.on('window-all-closed', function() 
{
	if (process.platform !== 'darwin') 
	{
        app.quit()
    }
})

app.on('activate', function() 
{
	if (mainWindow === null) 
	{
        createWindow()
    }
})

function handleSquirrelEvent(application) {
    if (process.argv.length === 1) {
        return false;
    }

    const ChildProcess = require('child_process');
    const path = require('path');

    const appFolder = path.resolve(process.execPath, '..');
    const rootAtomFolder = path.resolve(appFolder, '..');
    const updateDotExe = path.resolve(path.join(rootAtomFolder, 'Update.exe'));
    const exeName = path.basename(process.execPath);

    const spawn = function(command, args) {
        let spawnedProcess, error;

        try {
            spawnedProcess = ChildProcess.spawn(command, args, {
                detached: true
            });
        } catch (error) {}

        return spawnedProcess;
    };

    const spawnUpdate = function(args) {
        return spawn(updateDotExe, args);
    };

    const squirrelEvent = process.argv[1];
    switch (squirrelEvent) {
        case '--squirrel-install':
        case '--squirrel-updated':

            spawnUpdate(['--createShortcut', exeName]);

            setTimeout(application.quit, 1000);
            return true;

        case '--squirrel-uninstall':

            spawnUpdate(['--removeShortcut', exeName]);

            setTimeout(application.quit, 1000);
            return true;

        case '--squirrel-obsolete':

            application.quit();
            return true;
    }
};
```

## **build.js**

```
var electronInstaller = require('electron-winstaller');

resultPromise = electronInstaller.createWindowsInstaller({
    appDirectory: './ERCGK-win32-x64',
    outputDirectory: './ERCGK-Installers',
    authors: 'ERCGK',
    exe: './ERCGK.exe',
    setupExe: 'ERCGK.exe',
    noMsi: true,
    loadingGif: './ERCGK-win32-x64/resources/app/img/load.gif',
    setupIcon: './ERCGK-win32-x64/resources/app/img/icon.ico'
  });

resultPromise.then(() => console.log("Instalador creado."), (e) => console.log(`Error: ${e.message}`));
```

What am I doing wrong?

**Comment by Thieum** [comment]
@zJesusJavier do you still have this issue with the latest version of Squirrel?

**Comment by zJesusJavier** [comment]
Hi.

I'm retaking my project because I need it again for college, but i'm still having this issue, I just can't figure what I'm doing wrong.

### SquirrelSetup.txt

```
2019-10-03 22:35:26> Program: Starting Squirrel Updater: --createShortcut=ERCGK.exe
2019-10-03 22:35:26> ApplyReleasesImpl: About to create shortcuts for ERCGK.exe, rootAppDir C:\Users\SoulO\AppData\Local\ercgk
2019-10-03 22:35:27> Unhandled exception: System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2, String path3)
   at Squirrel.UpdateManager.ApplyReleasesImpl.getLinkTarget(ShortcutLocation location, String title, String applicationName, Boolean createDirectoryIfNecessary)
   at Squirrel.UpdateManager.ApplyReleasesImpl.linkTargetForVersionInfo(ShortcutLocation location, IPackage package, FileVersionInfo versionInfo)
   at Squirrel.UpdateManager.ApplyReleasesImpl.CreateShortcutsForExecutable(String exeName, ShortcutLocation locations, Boolean updateOnly, String programArguments, String icon)
   at Squirrel.Update.Program.Shortcut(String exeName, String shortcutArgs, String processStartArgs, String icon)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
```

### main.js
```
if (require('electron-squirrel-startup')) return;
const electron = require('electron')
const app = electron.app

if (handleSquirrelEvent(app)) {
    return;
}

function handleSquirrelEvent() {
    if (process.argv.length === 1) {
      return false;
    }
  
    const ChildProcess = require('child_process');
    const path = require('path');
  
    const appFolder = path.resolve(process.execPath, '..');
    const rootAtomFolder = path.resolve(appFolder, '..');
    const updateDotExe = path.resolve(path.join(rootAtomFolder, 'Update.exe'));
    const exeName = path.basename(process.execPath);
  
    const spawn = function(command, args) {
      let spawnedProcess, error;
  
      try {
        spawnedProcess = ChildProcess.spawn(command, args, {detached: true});
      } catch (error) {}
  
      return spawnedProcess;
    };
  
    const spawnUpdate = function(args) {
      return spawn(updateDotExe, args);
    };
  
    const squirrelEvent = process.argv[1];
    switch (squirrelEvent) {
      case '--squirrel-install':
      case '--squirrel-updated':
        // Optionally do things such as:
        // - Add your .exe to the PATH
        // - Write to the registry for things like file associations and
        //   explorer context menus
  
        // Install desktop and start menu shortcuts
        spawnUpdate(['--createShortcut', exeName]);
  
        setTimeout(app.quit, 1000);
        return true;
  
      case '--squirrel-uninstall':
        // Undo anything you did in the --squirrel-install and
        // --squirrel-updated handlers
  
        // Remove desktop and start menu shortcuts
        spawnUpdate(['--removeShortcut', exeName]);
  
        setTimeout(app.quit, 1000);
        return true;
  
      case '--squirrel-obsolete':
        // This is called on the outgoing version of your app before
        // we update to the new version - it's the opposite of
        // --squirrel-updated
  
        app.quit();
        return true;
    }
  };

const BrowserWindow = electron.BrowserWindow
const path = require('path')
const url = require('url')

let mainWindow

function createWindow() {
    mainWindow = new BrowserWindow({
        icon: path.join(__dirname, 'img/favicon.png'),
        webPreferences: {
            nodeIntegration: true
        }
    })

    mainWindow.removeMenu()
    mainWindow.maximize()
    mainWindow.show()
    mainWindow.loadURL(`file://${__dirname}/load.html`)
    //mainWindow.webContents.openDevTools({
    //    mode: 'detach'
    //});
    mainWindow.on('closed', function () {
        mainWindow = null
    })
}

app.on('ready', createWindow)

app.on('window-all-closed', function () {
    if (process.platform !== 'darwin') {
        app.quit()
    }
})

app.on('activate', function () {
    if (mainWindow === null) {
        createWindow()
    }
})
```

### build32.js

```
var electronInstaller = require('electron-winstaller');

var settings = 
{
    appDirectory: './ERCGK-win32-ia32',
    outputDirectory: './ERCGK_Installers',
    authors: 'Pabón Klaifer & Ramírez Jesús | IPTAI - SID4A | 2019',
    exe: './ERCGK.exe',
    noMsi: true,
    setupExe: 'ercgk-installer-x32.exe',
    loadingGif: './img/load.gif',
    setupIcon: './img/icon.ico'
};

resultPromise = electronInstaller.createWindowsInstaller(settings);
 
resultPromise.then(() => 
{
    console.log("Instalador creado.");
}, (e) => {
    console.log(`Error: ${e.message}`)
});
```

### package.json

```
{
  "name": "ercgk",
  "version": "2.0.0",
  "description": "Escuela de Reinas Celebrity Gipsy's Kingdom",
  "main": "main.js",
  "scripts": {
    "start": "electron main.js",
    "package-win32": "electron-packager . ERCGK --overwrite --asar --platform=win32 --arch=ia32 --icon=img/icon.ico",
    "package-win64": "electron-packager . ERCGK --overwrite --asar --platform=win32 --arch=x64 --icon=img/icon.ico"
  },
  "author": "Pabón Klaifer & Ramírez Jesús | IPTAI - SID4A | 2019",
  "license": "ISC",
  "dependencies": {
    "audit": "0.0.6",
    "debug": "^4.1.1",
    "electron-squirrel-startup": "^1.0.0",
    "fix": "0.0.6",
    "highcharts": "^7.2.0",
    "jquery": "^3.4.1",
    "module-alias": "^2.2.2",
    "mysql": "^2.17.1",
    "pdfkit": "^0.10.0",
    "sweetalert": "^2.1.2",
    "underscore.string": "^3.3.5",
    "voilab-pdf-table": "^0.5.0"
  },
  "devDependencies": {
    "electron": "^5.0.11",
    "electron-packager": "^14.0.6",
    "electron-winstaller": "^3.0.4"
  },
  "_moduleAliases": {
    "@lib": "lib",
    "@models": "lib"
  }
}
```

**Comment by anaisbetts** [comment]
Do you possibly have a corrupted shortcut to your app on this machine?

**Comment by PaulOrlov** [comment]
It looks like the Squirrel tries to make a shortcut for your app inside the specific folder (inside the C:\Users\userName\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\HERE). And it gets the name of the folder from the author/company of your project. As I see, you have "author": "Pabón Klaifer & Ramírez Jesús | IPTAI - SID4A | 2019", and there is a problem. 

Try something like:

```
"author": {
    "name": "Name without special symbols or Illegal characters",
    "email": "you@gmail.com"
  },   
```


I've spent a day to find the reason for the same problem in my setup!
