### ISSUE TITLE
Update failing with Mono.Cecil 0.10.0

### ISSUE THREAD

**Issue by ondrasvoboda** [Squirrel/Squirrel.Windows#1337]
I encountered a problem when updating my app using squirrel 1.8.0 and Mono.Cecil 0.10.0. I'm getting this exception:
`The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
  at Squirrel.SquirrelAwareExecutableDetector.GetAssemblySquirrelAwareVersion(String executable)
   at Squirrel.SquirrelAwareExecutableDetector.<>c__DisplayClass1_0.<GetPESquirrelAwareVersion>b__0() in C:\Users\paulb\code\Squirrel\squirrel.windows\src\Squirrel\SquirrelAwareExecutableDetector.cs:line 33
   at Squirrel.Utility.Retry[T](Func`1 block, Int32 retries) in C:\Users\paulb\code\Squirrel\squirrel.windows\src\Squirrel\Utility.cs:line 158
   at Squirrel.SquirrelAwareExecutableDetector.GetPESquirrelAwareVersion(String executable) in C:\Users\paulb\code\Squirrel\squirrel.windows\src\Squirrel\SquirrelAwareExecutableDetector.cs:line 32
   at Squirrel.SquirrelAwareExecutableDetector.<>c__DisplayClass0_0.<GetAllSquirrelAwareApps>b__2(String x) in C:\Users\paulb\code\Squirrel\squirrel.windows\src\Squirrel\SquirrelAwareExecutableDetector.cs:line 23
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Squirrel.SquirrelAwareExecutableDetector.GetAllSquirrelAwareApps(String directory, Int32 minimumVersion) in C:\Users\paulb\code\Squirrel\squirrel.windows\src\Squirrel\SquirrelAwareExecutableDetector.cs:line 20
   at Squirrel.UpdateManager.ApplyReleasesImpl.<invokePostInstall>d__10.MoveNext() in C:\Users\paulb\code\Squirrel\squirrel.windows\src\Squirrel\UpdateManager.ApplyReleases.cs:line 377`

When reverting Mono.Cecil to previous version 0.9.6.4 all works fine. Maybe it is a bug in Mono.Cecil. I just wanted to inform you, because it took me some time to find out where the problem is.

**Comment by themightylc** [comment]
I can confirm this - had the same problem and reverting Mono to 0.9.6.4 fixed it

**Comment by Thieum** [comment]
@shiftkey we could close this in favor of #897 , unless we want to track each dependency independently?

**Comment by shiftkey** [comment]
@Thieum 👍 we should keep this in one issue for simplicity sake currently
