### ISSUE TITLE
Install Fails for Certain Username

### ISSUE THREAD

**Issue by lehne** [Squirrel/Squirrel.Windows#1349]
We have a user that is having problems using our software (installed via Squirrel Installer). SquirrelSetup.log entry with exception:
```
2018-07-10 14:01:50> LogHost: Rigging execution stub for pvPlayer_ExecutionStub.exe to C:\Users\Carol's Computer\AppData\Local\pvPlayer\pvPlayer.exe
2018-07-10 14:01:51> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\Carol's Computer\Apped to invoke post-install: System.ComponentModel.Win32Exception (0x80004005): The directory name is invalid
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c.<invokePostInstall>b__10_6(ProcessStartInfo info)
   at Squirrel.EnumerableExtensions.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<invokePostInstall>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__42.MoveNext()
```
Of note the user's name is "Carol's Computer". My guess is the Process.Start does not like the apostrophe in the username.

**Comment by shiftkey** [comment]
This seems to be the relevant code:

https://github.com/Squirrel/Squirrel.Windows/blob/de5baa93a134ac24fd5bf9172d3e457ac27e0b7a/src/Squirrel/UpdateManager.ApplyReleases.cs#L413-L415

> Edit: Have found other cases of the install failing. A space in the username and ampersands have both been issues.

I thought `Process.Start` would encode these values fine, but maybe we also need to set `UseShellExecute=true` here:

https://stackoverflow.com/a/5255335/1363815
