### ISSUE TITLE
How do I get more details about an error

### ISSUE THREAD

**Issue by revington** [Squirrel/Squirrel.Windows#1375]
I'm trying to package my app and I'm getting the following error after running
`Squirrel --releasify ShoptimizaSalesFileExporter.1.0.0.nupkg` in Visual Studio 2017
 Is there a way to get more information? The app works so all the deps are in place.

```
Squirrel.com : System.Exception: Couldn't find file for package in .: AeroWizard
At line:1 char:9
+ Squirrel <<<<  --releasify ShoptimizaSalesFileExporter.1.0.0.nupkg --help
    + CategoryInfo          : NotSpecified: (System.Exceptio...n .: AeroWizard:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
   at Squirrel.ReleasePackage.<>c__DisplayClass20_0.<findAllDependentPackages>b__2(PackageDependency dependency)
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at 
System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Squirrel.ReleasePackage.findAllDependentPackages(IPackage package, IPackageRepository packageRepository, Ha
shSet`1 packageCache, Fr
ameworkName frameworkName)
   at Squirrel.ReleasePackage.CreateReleasePackage(String outputFile, String packagesRootDir, Func`2 releaseNotes
Processor, Action`1 contentsPostProcessHook)
   at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapper
Exe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon, Boolean generateMsi, String fram
eworkVersion, Boolean generateDeltas)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)
```

**Comment by antoineazar** [comment]
Did you ever find a solution? I'm blocked by the same thing.

**Comment by revington** [comment]
It was my fault. My nuspec package did not point to proper files or
something like that.

**Comment by Inzanit** [comment]
Looks like this is resolved, unless you wanted to follow up @antoineazar ?

**Comment by Thieum** [comment]
@shiftkey seems like it can be closed.
