### ISSUE TITLE
Update found, downloaded but thown error 404

### ISSUE THREAD

**Issue by tigierrei** [Squirrel/Squirrel.Windows#1376]
I'm developing an electron app that use electron-release-server to release updates. Squirrel seems to find, download and store the update inside the packages folder (.nupkg file of the newer version).
Even if squirrel find the update it throws an error 404 with the command failed error 4294967295. I was unable to find similar issues

Console log:
```
filip@DESKTOP-Q10836A MINGW64 ~/AppData/Local/SoulNetworkLauncher
$ ./SoulNetworkLauncher.exe

Feed url:
http://185.25.204.245:1337/update/win64/1.0.0/beta
checking-for-update

filip@DESKTOP-Q10836A MINGW64 ~/AppData/Local/SoulNetworkLauncher
$ update-available
Error: Command failed: 4294967295
System.AggregateException: Si sono verificati uno o pi� errori. ---> System.Net.WebException: Errore del server remoto: (404) Non trovato.
   in System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   in System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   in System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- Fine traccia dello stack da posizione precedente dove � stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in Squirrel.FileDownloader.<>c__DisplayClass2_2.<<DownloadFile>b__1>d.MoveNext()
--- Fine traccia dello stack da posizione precedente dove � stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in Squirrel.Utility.<LogIfThrows>d__42.MoveNext()
--- Fine traccia dello stack da posizione precedente dove � stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in Squirrel.FileDownloader.<DownloadFile>d__2.MoveNext()
--- Fine traccia dello stack da posizione precedente dove � stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in Squirrel.UpdateManager.DownloadReleasesImpl.<>c__DisplayClass2_0.<<DownloadReleases>b__1>d.MoveNext()
--- Fine traccia dello stack da posizione precedente dove � stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in Squirrel.Utility.<>c__DisplayClass13_1`1.<<ForEachAsync>b__1>d.MoveNext()
--- Fine traccia dello stack da posizione precedente dove � stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in Squirrel.UpdateManager.DownloadReleasesImpl.<DownloadReleases>d__2.MoveNext()
--- Fine traccia dello stack da posizione precedente dove � stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in Squirrel.UpdateManager.<DownloadReleases>d__8.MoveNext()
--- Fine traccia dello stack da posizione precedente dove � stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in Squirrel.Update.Program.<Update>d__5.MoveNext()
   --- Fine della traccia dello stack dell'eccezione interna ---
   in System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   in System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   in System.Threading.Tasks.Task.Wait()
   in Squirrel.Update.Program.executeCommandLine(String[] args)
   in Squirrel.Update.Program.main(String[] args)
   in Squirrel.Update.Program.Main(String[] args)
---> (Eccezione interna 0) System.Net.WebException: Errore del server remoto: (404) Non trovato.
   in System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   in System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   in System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- Fine traccia dello stack da posizione precedente dove � stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in Squirrel.FileDownloader.<>c__DisplayClass2_2.<<DownloadFile>b__1>d.MoveNext()
--- Fine traccia dello stack da posizione precedente dove � stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in Squirrel.Utility.<LogIfThrows>d__42.MoveNext()
--- Fine traccia dello stack da posizione precedente dove � stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in Squirrel.FileDownloader.<DownloadFile>d__2.MoveNext()
--- Fine traccia dello stack da posizione precedente dove � stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in Squirrel.UpdateManager.DownloadReleasesImpl.<>c__DisplayClass2_0.<<DownloadReleases>b__1>d.MoveNext()
--- Fine traccia dello stack da posizione precedente dove � stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in Squirrel.Utility.<>c__DisplayClass13_1`1.<<ForEachAsync>b__1>d.MoveNext()
--- Fine traccia dello stack da posizione precedente dove � stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in Squirrel.UpdateManager.DownloadReleasesImpl.<DownloadReleases>d__2.MoveNext()
--- Fine traccia dello stack da posizione precedente dove � stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in Squirrel.UpdateManager.<DownloadReleases>d__8.MoveNext()
--- Fine traccia dello stack da posizione precedente dove � stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in Squirrel.Update.Program.<Update>d__5.MoveNext()<---


    at AutoUpdater.emitError (C:\Users\filip\AppData\Local\SoulNetworkLauncher\app-1.0.0\resources\electron.asar\browser\api\auto-updater\auto-updater-win.js:70:24)
    at squirrelUpdate.update (C:\Users\filip\AppData\Local\SoulNetworkLauncher\app-1.0.0\resources\electron.asar\browser\api\auto-updater\auto-updater-win.js:55:23)
    at ChildProcess.<anonymous> (C:\Users\filip\AppData\Local\SoulNetworkLauncher\app-1.0.0\resources\electron.asar\browser\api\auto-updater\squirrel-update-win.js:71:14)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

**Comment by Inzanit** [comment]
This still an issue? I think it could probably be closed off? @tigierrei

**Comment by tigierrei** [comment]
Yea sorry, I forgot to close it
