### ISSUE TITLE
Installation fails, if the user name contains `lib`

### ISSUE THREAD

**Issue by SamvelRaja** [Squirrel/Squirrel.Windows#1391]
![capture](https://user-images.githubusercontent.com/5114052/46465225-bd2bc280-c7e5-11e8-8d98-02054199561f.PNG)

Cause:
https://github.com/Squirrel/Squirrel.Windows/commit/8885188996f8548e82e6df92ebf8d8da6443f9b1#diff-2637002ddbb1dfa2c58f1536d1caff6eR197

It is removing the path `lib\AppData\` from `C:\Users\samvellib\AppData\Local\Postman\app-6.3.0`
leads to invalid path  `C:\Users\samvelLocal\Postman\app-6.3.0`

Reported in:  https://github.com/postmanlabs/postman-app-support/issues/5301

Log
```
2018-10-04 14:53:33> CheckForUpdateImpl: Reading RELEASES file from C:\Users\samvellib\AppData\Local\SquirrelTemp
2018-10-04 14:53:33> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2018-10-04 14:53:33> ApplyReleasesImpl: Writing files to app directory: C:\Users\samvellib\AppData\Local\Postman\app-6.3.0
2018-10-04 14:53:33> IEnableLogger: Failed to install package to app dir: System.UnauthorizedAccessException: Access to the path 'C:\Users\samvelLocal\Postman\app-6.3.0\lib\net45' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at Squirrel.ReleasePackage.<>c__DisplayClass16_1.<ExtractZipForInstall>b__1()
   at Squirrel.Utility.Retry[T](Func`1 block, Int32 retries)
   at Squirrel.ReleasePackage.<>c__DisplayClass16_0.<ExtractZipForInstall>b__0(ZipEntry zipEntry)
   at Squirrel.Utility.<>c__DisplayClass12_1`1.<ForEachAsync>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.ReleasePackage.<ExtractZipForInstall>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass7_0.<<installPackageToAppDir>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext()
2018-10-04 14:53:33> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.UnauthorizedAccessException: Access to the path 'C:\Users\samvelLocal\Postman\app-6.3.0\lib\net45' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at Squirrel.ReleasePackage.<>c__DisplayClass16_1.<ExtractZipForInstall>b__1()
   at Squirrel.Utility.Retry[T](Func`1 block, Int32 retries)
   at Squirrel.ReleasePackage.<>c__DisplayClass16_0.<ExtractZipForInstall>b__0(ZipEntry zipEntry)
```

**Comment by Thieum** [comment]
I think the faulty line is:
https://github.com/Squirrel/Squirrel.Windows/blob/de5baa93a134ac24fd5bf9172d3e457ac27e0b7a/src/Squirrel/DeltaPackage.cs#L78

a quick fix would be to test for \lib\ instead of lib\ to narrow the fail cases, but that would leave possible issues.
