### ISSUE TITLE
Error while releasifying with Code Signing

### ISSUE THREAD

**Issue by jessiel-hacke** [Squirrel/Squirrel.Windows#1437]
**electron-forge**: 5.3.2
**electron-winstaller**: 2.7.0
**Squirrel.Windows**: 1.9

I am developing an application with Electron-Forge having Electron-Winstaller use Squirrel to package the .exe.

Before I added the code signing certificate everything worked smoothly, now that I added it I encountered an issue that I narrowed down to be in Squirrel.Windows.

I believe Squirrel.Windows is deleting the temporary folder that is used by the signtool before it finishes doing everything it needs to. Then it fails because the file doesn't exist anymore.

The stack bellow shows that it signed a few of the executables but failed to sign one of them. However it doesn't have in the same file all the time and sometimes it works for all the files.

```
Done Adding Additional Store
Successfully signed: C:\Users\myUser\AppData\Local\SquirrelTemp\tempa\lib\net45\MyApp.exe
Done Adding Additional Store
Successfully signed: C:\Users\myUser\AppData\Local\SquirrelTemp\tempa\lib\net45\MyApp_ExecutionStub.exe
Done Adding Additional Store
Successfully signed: C:\Users\myUser\AppData\Local\SquirrelTemp\tempa\lib\net45\ffmpeg.dll
Done Adding Additional Store
Successfully signed: C:\Users\myUser\AppData\Local\SquirrelTemp\tempa\lib\net45\libEGL.dll
Done Adding Additional Store
Successfully signed: C:\Users\myUser\AppData\Local\SquirrelTemp\tempa\lib\net45\libGLESv2.dll
Done Adding Additional Store
Successfully signed: C:\Users\myUser\AppData\Local\SquirrelTemp\tempa\lib\net45\node.dll
Done Adding Additional Store
Successfully signed: C:\Users\myUser\AppData\Local\SquirrelTemp\tempa\lib\net45\squirrel.exe
Done Adding Additional Store
Successfully signed: C:\Users\myUser\AppData\Local\SquirrelTemp\tempa\lib\net45\resources\app.asar.unpacked\app\vendor\win32\Perl\libgcc_s_seh-1.dll
System.AggregateException: One or more errors occurred. ---> System.Exception: Failed to sign, command invoked was: 'C:\Users\myUser\MyApp\node_modules\electron-winstaller\vendor\signtool.exe sign /a /f "C:\Users\myUser\MyApp\certificate\MyCertificate.pfx" /p "password" C:\Users\myUser\AppData\Local\SquirrelTemp\tempa\lib\net45\resources\app.asar.unpacked\app\vendor\win32\Perl\libstdc++-6.dll'
   at Squirrel.Update.Program.<signPEFile>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<>c__DisplayClass10_0.<<Releasify>b__14>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_1`1.<<ForEachAsync>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Squirrel.Update.Program.<>c__DisplayClass10_0.<Releasify>b__7(String pkgPath)
   at Squirrel.ReleasePackage.CreateReleasePackage(String outputFile, String packagesRootDir, Func`2 releaseNotesProcessor, Action`1 contentsPostProcessHook)
   at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon, Boolean generateMsi, String frameworkVersion, Boolean generateDeltas)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)
---> (Inner Exception #0) System.Exception: Failed to sign, command invoked was: 'C:\Users\myUser\MyApp\node_modules\electron-winstaller\vendor\signtool.exe sign /a /f "C:\Users\myUser\MyApp\certificate\EloSeqSorterCert.pfx" /p ",Juf1%$uAEjoy@5P" C:\Users\myUser\AppData\Local\SquirrelTemp\tempa\lib\net45\resources\app.asar.unpacked\app\vendor\win32\Perl\libstdc++-6.dll'
   at Squirrel.Update.Program.<signPEFile>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<>c__DisplayClass10_0.<<Releasify>b__14>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_1`1.<<ForEachAsync>b__1>d.MoveNext()<---
``` 

This happened first when I tried `electron-forge make`. I tried running Squirrel by itself using the `.nupkg` generated by `electron-forge package` but the same result(for a different file) happened.

Do you know what could be happening?

P.S.:
  - I have tried changing SQUIRREL_TEMP environment variable, got the same result;
  - The signtool doesn't fail if I try it by itself on all the files that failed while executing Squirrel;
  - Sometimes it doesn't fail at all, which makes the whole process extremely unpredictable.

**Comment by jessiel-hacke** [comment]
Alright, I was able to narrow down the issue even further and the error is in the SignTool failing randomly and in consequence, failing the build.

It took me a little while to figure out because of the lack of a more descriptive error message. I know there is another issue that is related to the error message so I will close this one for now.

**Comment by paulcbetts** [comment]
Signtool is super into failing randomly, especially if you invoke it concurrently :-/

**Comment by abdurrahmanekr** [comment]
Hi, We are still experiencing this problem. What exactly do you mean by concurrently? There is only one node instance running the createWindowsInstaller method.

node: **10.16.0**
electron-winstaller: **5.0.0**

Log:
```
Well, sometimes you are not so lucky: Failed with exit code: 255
Output:
System.AggregateException: One or more errors occurred. (Failed to sign, command invoked was: '/home/machine/App/node_modules/electron-winstaller/vendor/signtool.exe sign /a /f "/home/machine/App/electron/codesign.pfx" /p "password" /home/machine/.local/share/SquirrelTemp/tempa/lib/net45/ffmpeg.dll') ---> System.Exception: Failed to sign, command invoked was: '/home/machine/App/node_modules/electron-winstaller/vendor/signtool.exe sign /a /f "/home/machine/App/electron/codesign.pfx" /p "password" /home/machine/.local/share/SquirrelTemp/tempa/lib/net45/ffmpeg.dll'
  at Squirrel.Update.Program.signPEFile (System.String exePath, System.String signingOpts) [0x00117] in <1ffb1a5dca5b4f2f93386cec56fd9ec2>:0 
  at Squirrel.Update.Program+<>c__DisplayClass10_0.<Releasify>b__14 (System.IO.FileInfo x) [0x000d2] in <1ffb1a5dca5b4f2f93386cec56fd9ec2>:0 
  at Squirrel.Utility+<>c__DisplayClass13_1`1[T].<ForEachAsync>b__1 () [0x00089] in <1ffb1a5dca5b4f2f93386cec56fd9ec2>:0 
   --- End of inner exception stack trace ---
  at System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) [0x00011] in <533173d24dae460899d2b10975534bb0>:0 
  at System.Threading.Tasks.Task.Wait (System.Int32 millisecondsTimeout, System.Threading.CancellationToken cancellationToken) [0x00043] in <533173d24dae460899d2b10975534bb0>:0 
  at System.Threading.Tasks.Task.Wait () [0x00000] in <533173d24dae460899d2b10975534bb0>:0 
  at Squirrel.Update.Program+<>c__DisplayClass10_0.<Releasify>b__7 (System.String pkgPath) [0x00126] in <1ffb1a5dca5b4f2f93386cec56fd9ec2>:0 
  at Squirrel.ReleasePackage.CreateReleasePackage (System.String outputFile, System.String packagesRootDir, System.Func`2[T,TResult] releaseNotesProcessor, System.Action`1[T] contentsPostProcessHook) [0x001e6] in <1ffb1a5dca5b4f2f93386cec56fd9ec2>:0 
  at Squirrel.Update.Program.Releasify (System.String package, System.String targetDir, System.String packagesDir, System.String bootstrapperExe, System.String backgroundGif, System.String signingOpts, System.String baseUrl, System.String setupIcon, System.Boolean generateMsi, System.Boolean packageAs64Bit, System.String frameworkVersion, System.Boolean generateDeltas) [0x00214] in <1ffb1a5dca5b4f2f93386cec56fd9ec2>:0 
  at Squirrel.Update.Program.executeCommandLine (System.String[] args) [0x00116] in <1ffb1a5dca5b4f2f93386cec56fd9ec2>:0 
  at Squirrel.Update.Program.main (System.String[] args) [0x00113] in <1ffb1a5dca5b4f2f93386cec56fd9ec2>:0 
  at Squirrel.Update.Program.Main (System.String[] args) [0x00006] in <1ffb1a5dca5b4f2f93386cec56fd9ec2>:0 
---> (Inner Exception #0) System.Exception: Failed to sign, command invoked was: '/home/machine/App/node_modules/electron-winstaller/vendor/signtool.exe sign /a /f "/home/machine/App/electron/codesign.pfx" /p "password" /home/machine/.local/share/SquirrelTemp/tempa/lib/net45/ffmpeg.dll'
  at Squirrel.Update.Program.signPEFile (System.String exePath, System.String signingOpts) [0x00117] in <1ffb1a5dca5b4f2f93386cec56fd9ec2>:0 
  at Squirrel.Update.Program+<>c__DisplayClass10_0.<Releasify>b__14 (System.IO.FileInfo x) [0x000d2] in <1ffb1a5dca5b4f2f93386cec56fd9ec2>:0 
  at Squirrel.Utility+<>c__DisplayClass13_1`1[T].<ForEachAsync>b__1 () [0x00089] in <1ffb1a5dca5b4f2f93386cec56fd9ec2>:0 <---

```

**Comment by Achder** [comment]
I have this problem to. Is there a solution available?

**Comment by cdiddy77** [comment]
+1 seems lots of folks are [hitting this](https://github.com/electron/windows-installer/issues/32)

**Comment by anaisbetts** [comment]
The reason that it is closed is because the bug is in signtool.exe, which we can't really do much of anything about. Signtool seems to fail on new machines, when running in service accounts, when you breathe on it too hard, if it happens to be Tuesday...

**Comment by cah-eric-waight01** [comment]
I am currently facing this issue as well. Anyone establish a workaround?

**Comment by apatelatbigpoint** [comment]
Anyone have a fix or workaround this?
I am surprised how it can be signtool problem when actually it works when signing ALL  the files manually one by one.

So it has to be due to the the packager/maker step and probably another step which is probably deleting the temp folder before signing is finished.

It is always always the ffmpeg.dll for me that fails

**Comment by Dexus** [comment]
I struggeling also with this error, i don't have any Idear how i can fix this. It looks like it really deletes the files before it can sign it.

I have enabled ZIP and Squirrel  in forge.

**Comment by widavies** [comment]
I'm having this happen too, it looks like Squirrel is deleting the files before signing occurs. I shim signtool with a custom CLI - I check if each of the passed files exist. They exist at the beginning, but after `signtool.exe` fails they get removed. Is squirrel trying to concurrently remove or sign these files?

**Comment by jparismorgan** [comment]
+1 that this doesn't seem like a `signtool.exe` problem, and that I'm also running into this.
