### ISSUE TITLE
Squirrel Updater: --install  - Windows

### ISSUE THREAD

**Issue by T-makanaki** [Squirrel/Squirrel.Windows#1438]
We developed an electron application that installs and updates using electron windows installer. We configured a GPO to install or update the application to computers when users log in. In one of our locations, users get the error below everytime they log in to their computers. The full exception from the squirrel log file is also shown below. 

![image](https://user-images.githubusercontent.com/844556/51096418-735e5b00-178a-11e9-861b-234fc4051bfa.png)

2018-11-27 17:12:01> Program: Starting Squirrel Updater: --install .
2018-11-27 17:12:01> Program: Starting install, writing to C:\Users\adminBL\AppData\Local\SquirrelTemp
2018-11-27 17:12:01> Program: About to install to: C:\Users\adminBL\AppData\Local\myiiapp
2018-11-27 17:12:01> Program: Install path C:\Users\adminBL\AppData\Local\myiiapp already exists, burning it to the ground
2018-11-27 17:12:01> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Squirrel.UnsafeUtility.<>c__DisplayClass0_0.<EnumerateProcesses>b__0(Int32 i)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Squirrel.UnsafeUtility.EnumerateProcesses()
   at Squirrel.UpdateManager.InstallHelperImpl.KillAllProcessesBelongingToPackage()
   at Squirrel.Update.Program.<Install>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Squirrel.UnsafeUtility.<>c__DisplayClass0_0.<EnumerateProcesses>b__0(Int32 i)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Squirrel.UnsafeUtility.EnumerateProcesses()
   at Squirrel.UpdateManager.InstallHelperImpl.KillAllProcessesBelongingToPackage()
   at Squirrel.Update.Program.<Install>d__4.MoveNext()<---

Can you please help with this. Any help or pointers is greatly appreciated.
Thanks.

**Comment by Inzanit** [comment]
Is this still an issue? I believe there is an issue with running as admin and Squirrel attempting to reinstall in some cases.

**Comment by 120gr** [comment]
Hi everyone and hope you're doing well. I encountered the same issue on my computer (Windows 10). 

It's happened when I've updated to the latest version the program, and the messages weren't showing, after waiting during a very long time. So I've closed the program, uninstalled it and download it again. After this, it appears that everytime I'm launching the app, I have a similar log and warning pop-up. 

You'll find attached to this message the log. Thank you for your help. 

[SquirrelLog.txt](https://github.com/Squirrel/Squirrel.Windows/files/3728221/SquirrelLog.txt)

**Comment by ananddubey2020** [comment]
017-07-14 11:57:23> Program: Starting Squirrel Updater: --install .
2017-07-14 11:57:23> Program: Starting install, writing to C:\Users\Dubey\AppData\Local\SquirrelTemp
2017-07-14 11:57:24> Program: About to install to: C:\Users\Dubey\AppData\Local\Postman

**Comment by anaisbetts** [comment]
Build the MSI for your app via electron-winstaller and deploy that instead
