### ISSUE TITLE
While releasifying I'm getting duplicated dependency exception

### ISSUE THREAD

**Issue by quasarea** [Squirrel/Squirrel.Windows#1474]
Simple csharp .472 application with dependency on squirrel only (as it checks for update).

I'm getting below exemption due to SharpCompress having same depenency for differnet .net standard versions. Processing dependencies is done in forked of legacy nuget implementation in squirrel.windows\vendor\nuget\src\Core\Authoring\Manifest.cs

Can try to fix it, but I wonder if I'm not doing something wrong here as couldn't find this issue, my command after packaging app is 

>packages\Squirrel.Windows\tools\Squirrel.com  --releasify=MyApp.1.0.5-squirrel25.nupkg --packagesDir=C:\Jenkins\Workspace\MyApp\feature\squirrel\packages --framework-version=net472

and the exception:

>    System.InvalidOperationException: 'SharpCompress' already has a dependency defined for 'NETStandard.Library'.
        at NuGet.Manifest.ValidateDependencySets(IPackageMetadata metadata)
        at NuGet.Manifest.Validate(Manifest manifest)
        at NuGet.Manifest.ReadFrom(Stream stream, IPropertyProvider propertyProvider, Boolean validateSchema)
        at NuGet.LocalPackage.ReadManifest(Stream manifestStream)
        at NuGet.OptimizedZipPackage.EnsureManifest()
        at NuGet.OptimizedZipPackage..ctor(IFileSystem fileSystem, String packagePath)
        at NuGet.LocalPackageRepository.OpenPackage(String path)
        at NuGet.LocalPackageRepository.GetPackage(Func`2 openPackage, String path)
        at NuGet.LocalPackageRepository.<GetPackages>d__28.MoveNext()
        at NuGet.CollectionExtensions.AddRange[T](ICollection`1 collection, IEnumerable`1 items)
        at NuGet.LocalPackageRepository.FindPackagesById(Func`2 openPackage, String packageId)
        at NuGet.LocalPackageRepository.FindPackagesById(String packageId)
        at NuGet.PackageRepositoryExtensions.FindPackagesById(IPackageRepository repository, String packageId)
        at Squirrel.ReleasePackage.matchPackage(IPackageRepository packageRepository, String id, IVersionSpec version)
        at Squirrel.ReleasePackage.<>c__DisplayClass20_0.<findAllDependentPackages>b__2(PackageDependency dependency)
        at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
        at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
        at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
        at Squirrel.ReleasePackage.findAllDependentPackages(IPackage package, IPackageRepository packageRepository, HashSet`1 packageCache, FrameworkName frameworkName)
        at Squirrel.ReleasePackage.<>c__DisplayClass20_0.<findAllDependentPackages>b__2(PackageDependency dependency)
        at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
        at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
        at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
        at Squirrel.ReleasePackage.findAllDependentPackages(IPackage package, IPackageRepository packageRepository, HashSet`1 packageCache, FrameworkName frameworkName)
        at Squirrel.ReleasePackage.CreateReleasePackage(String outputFile, String packagesRootDir, Func`2 releaseNotesProcessor, Action`1 contentsPostProcessHook)
        at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon, Boolean generateMsi, String frameworkVersion, Boolean generateDeltas)
        at Squirrel.Update.Program.executeCommandLine(String[] args)
        at Squirrel.Update.Program.main(String[] args)
        at Squirrel.Update.Program.Main(String[] args)

![image](https://user-images.githubusercontent.com/10334982/57148188-fc90b080-6dc0-11e9-91ca-76d6eb60d859.png)

**Comment by Thieum** [comment]
@quasarea can you open MyApp.1.0.5-squirrel25.nupkg with NuGet Package Explorer, and check that there is no dependencies there?

**Comment by quasarea** [comment]
There is dependency on squirrel (as I need it to check for the update).

Have I wrongly assumed that squirrel can resolve dependencies while packaging and instead I have to provide dependencies directly as files in nuspec?

**Comment by shiftkey** [comment]
> Have I wrongly assumed that squirrel can resolve dependencies while packaging and instead I have to provide dependencies directly as files in nuspec?

@quasarea this is correct. It gets a mention on [this page](https://github.com/Squirrel/Squirrel.Windows/blob/develop/docs/getting-started/2-packaging.md) of the docs:

> **Dependencies** - Squirrel expects no dependencies in the package (all files should be explicitly added to the package)
