### ISSUE TITLE
squirrel keeps overwritting my executable to a stub in both app and root folder

### ISSUE THREAD

**Issue by bravepuzzle** [Squirrel/Squirrel.Windows#1532]
**Squirrel version(s)**
1.9.1

**Description**
I've looked thru a ton of issues here that seemed to be like mine but none of the answers helped me.

Would appreciate some guidance.
```cs
<Exec Command="nuget pack ..\AutoBooking.nuspec -Version %(myAssemblyInfo.Version) -Properties Configuration=Release -OutputDirectory $(OutDir) -BasePath $(OutDir)" />
<Exec Command="squirrel --no-msi --releasify $(OutDir)AutoBooking.$([System.Version]::Parse(%(myAssemblyInfo.Version)).ToString(3)).nupkg" />
```
When it runs releasify, it will overwrite the main application executable in the Release folder to a stub and the resulting package exe and nupkg will contain that stub in both the root and app-1.0.0 folder rendering my installation files unusable.

It is also creating a nupkg file in the bin\Release folder which differs in checksum from the one contained in the Releases folder.

Before running the build/rebuild I deleted both the bin\Release folder and Releases folder to make sure it was generating things from scratch.

**Steps to recreate**
Unhappily at this point in time I am unsure how to reproduce the issue.

I am running on windows 10 x64 1903 build 18362.295

**Expected behavior**
Not entirely sure squirrel should be overwriting my executable from the bin\Release folder and I would expected the executable inside the nupkg app-1.0.0 folder to be the original one.

**Actual behavior**
As explained in the description

**Additional information**
My project is set to build things to x86, however my platform itself is x64.
I have CefSharp in my project if that matters however I am renaming the `CefSharp.BrowserSubprocess.exe` to something else and renaming it back on the install/update events.
I have my main executable with `[assembly: AssemblyMetadata("SquirrelAwareVersion", "1")]` as well as:

```cs
SquirrelAwareApp.HandleEvents(
onInitialInstall: v =>
{
    if (File.Exists(browserSubprocess))
    {
        File.Move(browserSubprocess, browserSubprocess.Replace(".bin2", ".exe"));
    }
    manager.CreateShortcutForThisExe();
},
onAppUpdate: v =>
{
    if (File.Exists(browserSubprocess))
    {
        File.Move(browserSubprocess, browserSubprocess.Replace(".bin2", ".exe"));
    }
    manager.CreateShortcutForThisExe();
},
onAppUninstall: v => manager.RemoveShortcutForThisExe(),
onFirstRun: () => ShowTheWelcomeWizard = true);
```
Which makes no difference at all.

My logs
```
2019-08-23 16:32:30> Program: Starting Squirrel Updater: --install .
2019-08-23 16:32:30> Program: Starting install, writing to C:\Users\admin\AppData\Local\SquirrelTemp
2019-08-23 16:32:30> Program: About to install to: C:\Users\admin\AppData\Local\AutoBooking
2019-08-23 16:32:30> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\admin\AppData\Local\AutoBooking\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2019-08-23 16:32:30> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\admin\AppData\Local\AutoBooking\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2019-08-23 16:32:30> CheckForUpdateImpl: Reading RELEASES file from C:\Users\admin\AppData\Local\SquirrelTemp
2019-08-23 16:32:30> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2019-08-23 16:32:30> ApplyReleasesImpl: Writing files to app directory: C:\Users\admin\AppData\Local\AutoBooking\app-1.0.0
2019-08-23 16:32:32> ApplyReleasesImpl: Squirrel Enabled Apps: []
2019-08-23 16:32:32> ApplyReleasesImpl: No apps are marked as Squirrel-aware! Going to run them all
2019-08-23 16:32:32> ApplyReleasesImpl: About to create shortcuts for AutoBooking.exe, rootAppDir C:\Users\admin\AppData\Local\AutoBooking
2019-08-23 16:32:32> ApplyReleasesImpl: Creating shortcut for AutoBooking.exe => C:\Users\admin\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Microsoft Corporation\Microsoft® Visual Studio® 2015.lnk
2019-08-23 16:32:32> ApplyReleasesImpl: About to save shortcut: C:\Users\admin\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Microsoft Corporation\Microsoft® Visual Studio® 2015.lnk (target C:\Users\admin\AppData\Local\AutoBooking\AutoBooking.exe, workingDir C:\Users\admin\AppData\Local\AutoBooking\app-1.0.0, args , toastActivatorCSLID 00ce84a7-ce71-5068-892d-0ce64e247f2e)
2019-08-23 16:32:32> ApplyReleasesImpl: Creating shortcut for AutoBooking.exe => C:\Users\admin\Desktop\Microsoft® Visual Studio® 2015.lnk
2019-08-23 16:32:32> ApplyReleasesImpl: About to save shortcut: C:\Users\admin\Desktop\Microsoft® Visual Studio® 2015.lnk (target C:\Users\admin\AppData\Local\AutoBooking\AutoBooking.exe, workingDir C:\Users\admin\AppData\Local\AutoBooking\app-1.0.0, args , toastActivatorCSLID 00ce84a7-ce71-5068-892d-0ce64e247f2e)
2019-08-23 16:32:32> ApplyReleasesImpl: Examining Pin: Show Desktop.lnk
2019-08-23 16:32:32> IEnableLogger: Failed to invoke post-install: System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c.<invokePostInstall>b__10_6(ProcessStartInfo info)
   at Squirrel.EnumerableExtensions.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<invokePostInstall>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__42.MoveNext()
2019-08-23 16:32:32> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.ComponentModel.Win32Exception: The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c.<invokePostInstall>b__10_6(ProcessStartInfo info)
   at Squirrel.EnumerableExtensions.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<invokePostInstall>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<FullInstall>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c.<invokePostInstall>b__10_6(ProcessStartInfo info)
   at Squirrel.EnumerableExtensions.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<invokePostInstall>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<FullInstall>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()<---
```

**Comment by anaisbetts** [comment]
It seems like you probably want to set the output directory via the `-r` switch. This directory should have your previous releases in it (you can use `SyncReleases` to download them in CI)

>  have CefSharp in my project if that matters however I am renaming the CefSharp.BrowserSubprocess.exe to something else and renaming it back on the install/update events.

This is not a good strategy because Antivirus will fail this process on many user machines - you have to write an EXE to the final location the _first_ time or else you'll have Issues.

**Comment by bravepuzzle** [comment]
@anaisbetts When I have the cefsharp executable in, it will always generate a shortcut for both files.

I will try the -r, thanks.

**Comment by anaisbetts** [comment]
@bravepuzzle You need to follow the steps to make your app Squirrel-aware. This will let you create your own shortcuts, so your app can only create shortcuts for the main EXE

**Comment by bravepuzzle** [comment]
@anaisbetts have I done it wrong? I listed the steps I did in the first message for making it Aware.

Also -r didn't change anything the executable in the Release folder is still being overwritten some how...

**Comment by bravepuzzle** [comment]
without squirrel
![video](http://www.mediafire.com/view/70c2m19isdzstaz/2019-08-23_17-33-16.mp4)

with squirrel
![video](http://www.mediafire.com/view/rymgh8fyn8fnoye/2019-08-23_17-33-39.mp4)

And this 82kb file is what squirrel is using for the app-1.0.0 folder and its root folder.

**Comment by bravepuzzle** [comment]
I was able to some how fix?!?! the issue by doing the following:

- removed the squirrel settings from my csproj file
- then deleted bin\Release and Releases folders
- rebuild project
- re-added squirrel settings to my csproj file
- rebuild
- executable was now working and not being replaced

In order for the shortcut to work I had to use `CreateShortcutsForExecutable` instead.

So what I have noticed is that after I rebuild my project with the proper executable it should have, putting the squirrel settings back and running it, squirrel seems to use my original executable, then it replaces it, so on subsequent runs it never uses the original executable again, thus causing this whole issue.

I do not know why it replaces the executable like that so I am still unable to provide you guys with a reproducible way to my issue.

**Comment by bravepuzzle** [comment]
Finally figured the issue, it was as simple as this:

From:
```
<Target Name="AfterBuild" Condition=" '$(Configuration)' == 'Release'">
```
To:
```
<Target AfterTargets="AfterBuild" Name="AfterBuild" Condition=" '$(Configuration)' == 'Release'">
```
For whatever odd reason visual studio was not considering the AfterBuild and was stepping ahead, by adding the AfterTargets with AfterBuild my executable is now preserved and not modified and the setup works as expected and I no longer have to keep deleting things around to rebuild, etc.

Sorry about taking your time and hopefully this might help others with the same issue.
