### ISSUE TITLE
failure to install the app

### ISSUE THREAD

**Issue by uchchash786** [Squirrel/Squirrel.Windows#1533]
2019-08-25 15:26:44> Program: Starting Squirrel Updater: --install . --checkInstall --silent
2019-08-25 15:26:44> Program: Starting install, writing to C:\Users\Bismillah Computer\AppData\Local\SquirrelTemp
2019-08-25 15:26:45> Program: About to install to: C:\Users\Bismillah Computer\AppData\Local\GitHubDesktop
2019-08-25 15:26:45> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Bismillah Computer\AppData\Local\GitHubDesktop\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2019-08-25 15:26:45> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Bismillah Computer\AppData\Local\GitHubDesktop\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2019-08-25 15:26:45> CheckForUpdateImpl: Reading RELEASES file from C:\Users\Bismillah Computer\AppData\Local\SquirrelTemp
2019-08-25 15:26:45> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2019-08-25 15:26:46> ApplyReleasesImpl: Writing files to app directory: C:\Users\Bismillah Computer\AppData\Local\GitHubDesktop\app-2.1.2
2019-08-25 15:26:46> LogHost: Rigging execution stub for lib/net45/GitHubDesktop_ExecutionStub.exe to C:\Users\Bismillah Computer\AppData\Local\GitHubDesktop\GitHubDesktop.exe
2019-08-25 15:27:11> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\Bismillah Computer\AppData\Local\GitHubDesktop\app-2.1.2\GitHubDesktop.exe]
2019-08-25 15:27:11> ApplyReleasesImpl: Couldn't run Squirrel hook, continuing: C:\Users\Bismillah Computer\AppData\Local\GitHubDesktop\app-2.1.2\GitHubDesktop.exe: System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Squirrel.Utility.<InvokeProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass10_0.<<invokePostInstall>b__0>d.MoveNext()
2019-08-25 15:27:11> ApplyReleasesImpl: Starting fixPinnedExecutables
2019-08-25 15:27:12> ApplyReleasesImpl: Examining Pin: GOM.EXE.lnk
2019-08-25 15:27:12> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2019-08-25 15:27:12> ApplyReleasesImpl: Examining Pin: Internet Explorer.lnk
2019-08-25 15:27:12> ApplyReleasesImpl: Examining Pin: Windows Explorer.lnk
2019-08-25 15:27:12> ApplyReleasesImpl: Examining Pin: Windows Media Player.lnk
2019-08-25 15:27:12> ApplyReleasesImpl: Fixing up tray icons
2019-08-25 15:27:12> ApplyReleasesImpl: cleanDeadVersions: for version 2.1.2
2019-08-25 15:27:12> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-2.1.2
2019-08-25 15:27:18> InstallHelperImpl: Couldn't write uninstall icon, don't care: System.Net.WebException: The remote name could not be resolved: 'desktop.githubusercontent.com'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.InstallHelperImpl.<CreateUninstallerRegistryEntry>d__5.MoveNext()
how i can correct it

**Comment by anaisbetts** [comment]
This isn't a user support forum, please file an issue on desktop/desktop. That being said:

> System.Net.WebException: The remote name could not be resolved: 'desktop.githubusercontent.com'
