### ISSUE TITLE
RestartApp does not restart app, is looking for package\releases in version folder

### ISSUE THREAD

**Issue by skipfire** [Squirrel/Squirrel.Windows#1562]
**Squirrel version(s)**
1.8.0

**Description**
App does not restart after calling UpgradeManager.RestartApp(), even if I provide the filename to the non-version launcher it does not reopen.  The SquirrelSetup.log is in the version folder and indicates it is trying to find \app-x.y.z\packages\releases instead of \packages\releases so my guess is somehow the updater is running from the version directory instead of the parent.

**Expected behavior**
App closes with no displayed errors, nothing in event log, the old version of the app does not go into the catch() steps.  New version does not open, SquirrelSetup.log is created with an error inside.

**Actual behavior**
New version should launch.

**Additional information**
SquirrelSetup.log text:

`2019-11-14 14:17:26> Program: Starting Squirrel Updater: --processStartAndWait C:\Users\{user}\AppData\Local\{app}\{app}.exe
2019-11-14 14:17:26> Unhandled exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\{user}\AppData\Local\{app}\app-1.2.2\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at System.IO.File.ReadAllText(String path, Encoding encoding)
   at Squirrel.Update.Program.ProcessStart(String exeName, String arguments, Boolean shouldWait)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
`

**Comment by bertstomphorst** [comment]
Does your appname eventually contain spaces? Yesterday I came into that path, and found a solution by providing the exe-name surrounded with double-quotes:
```
UpdateManager.RestartApp($"\"{Path.GetFileName(Assembly.GetEntryAssembly().Location)}\"");
```
This works fine for me, maybe it could help you?

BTW: I made a [PR](https://github.com/Squirrel/Squirrel.Windows/pull/1592) to fix this in source.
