### ISSUE TITLE
Only dot "nupkg" file

### ISSUE THREAD

**Issue by PTassou** [Squirrel/Squirrel.Windows#1569]
I have a solution in TeamCity and a shared folder where the releases are stored and exported. I have automated the release cycle with a powershell script and inside there is the the command
`& $squirrelPath --releasify $PSScriptRoot\$ExePath\$NugetName.$Version.nupkg --releaseDir $ReleaseFolder --no-msi`
Suddenly, it stopped export of "full" and "delta" packages, also it stopped updating the "setup.exe" and it only produces "$name-$version.nupkg" in the shared folder. I didn't change the code, neither the build steps in TeamCity.
Any ideas?

**Comment by anaisbetts** [comment]
I would check the SquirrelSetup log on the CI server to see what's going on

**Comment by rayanalsubhi-feenics** [comment]
Make sure you wait for the process to finish. Squirrel session might still be running.
I have something like 
```pwsh
Start-Process -FilePath Squirrel.exe -ArgumentList ("--releasify", "package.nupkg", "-r", '"folder"', "--framework-version=net46") -PassThru | Wait-Process
```

**Comment by PTassou** [comment]
> I would check the SquirrelSetup log on the CI server to see what's going on

I already done that and nothing there 😢

**Comment by PTassou** [comment]
> Make sure you wait for the process to finish. Squirrel session might still be running.
> I have something like
> 
> ```powershell
> Start-Process -FilePath Squirrel.exe -ArgumentList ("--releasify", "package.nupkg", "-r", '"folder"', "--framework-version=net46") -PassThru | Wait-Process
> ```

Thanks. I will try it right away! Thanks a lot!!

**Comment by PTassou** [comment]
So an update. 
I modified the powershell script and now is something like that:
`$ArgumentsForSquirrelToRun = '--releasify ' + $PSScriptRoot+'\'+$ExePath+'\'+$NugetName+'.'+$Version+'.nupkg' + ' --releaseDir ' + $ReleaseFolder + ' --no-msi'
& Start-Process $squirrelPath $ArgumentsForSquirrelToRun -NoNewWindow -Wait`
Unfortunately with no luck.
But, i checked the log file needed ( now I got it, sorry for previous wrong response @anaisbetts )
and i found out that message:
`2020-01-22 18:57:00> Program: Creating release package: ....releasedir.......nupkg
2020-01-22 19:06:05> Unhandled exception: System.IO.FileFormatException: File contains corrupted data.
   at MS.Internal.IO.Zip.ZipIOEndOfCentralDirectoryBlock.FindPosition(Stream archiveStream)
   at MS.Internal.IO.Zip.ZipIOEndOfCentralDirectoryBlock.SeekableLoad(ZipIOBlockManager blockManager)
   at MS.Internal.IO.Zip.ZipArchive..ctor(Stream archiveStream, FileMode mode, FileAccess access, Boolean streaming, Boolean ownStream)
   at MS.Internal.IO.Zip.ZipArchive.OpenOnStream(Stream stream, FileMode mode, FileAccess access, Boolean streaming)
   at System.IO.Packaging.ZipPackage..ctor(Stream s, FileMode mode, FileAccess access, Boolean streaming)
   at System.IO.Packaging.Package.Open(Stream stream, FileMode packageMode, FileAccess packageAccess, Boolean streaming)
   at System.IO.Packaging.Package.Open(Stream stream)
   at NuGet.ZipPackage.EnsureManifest()
   at NuGet.ZipPackage..ctor(String filePath, Boolean enableCaching)
   at Squirrel.ReleasePackage.get_SuggestedReleaseFileName()
   at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon, Boolean generateMsi, String frameworkVersion, Boolean generateDeltas)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)`

**Comment by anaisbetts** [comment]
Well, is your NuGet package a corrupted zip file then?

**Comment by PTassou** [comment]
How can I evaluate that?

**Comment by PTassou** [comment]
Well. I couldn't find what's wrong and I couldn't trace back. So a solution I did was to clear all previous versions in release folder we had and tell "squirel" to start releases from the begging.

**Comment by klnmi97** [comment]
Hello, I faced the same problem. I have one large file (16 GB) inside the .nupkg file which causes the same exception:
`Squirrel : System.IO.FileFormatException: File contains corrupted data.
At line:1 char:1
+ Squirrel --releasify .\Pack.1.0.0.nupkg
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (System.IO.FileF...corrupted data.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
   at MS.Internal.IO.Zip.ZipIOLocalFileBlock.Validate(String fileName, ZipIOCentralDirectoryBlock centralDir, ZipIOCentralDirectoryFileHeader centralDirFileHeader)
   at MS.Internal.IO.Zip.ZipIOLocalFileBlock.SeekableLoad(ZipIOBlockManager blockManager, String fileName)
   at MS.Internal.IO.Zip.ZipIOBlockManager.LoadLocalFileBlock(String zipFileName)
   at MS.Internal.IO.Zip.ZipArchive.GetFile(String zipFileName)
   at MS.Internal.IO.Zip.ZipArchive.GetFiles()
   at System.IO.Packaging.ZipPackage.ContentTypeHelper..ctor(ZipArchive zipArchive, IgnoredItemHelper ignoredItemHelper)
   at System.IO.Packaging.ZipPackage..ctor(Stream s, FileMode mode, FileAccess access, Boolean streaming)
   at System.IO.Packaging.Package.Open(Stream stream, FileMode packageMode, FileAccess packageAccess, Boolean streaming)
   at NuGet.ZipPackage.EnsureManifest()
   at Squirrel.ReleasePackage.get_SuggestedReleaseFileName()
   at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon, Boolean generateMsi, Boolean 
packageAs64Bit, String frameworkVersion, Boolean generateDeltas)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)`
If I delete this file, it works fine. I have also tried other large files (of the same type) and it worked the same way. However it worked for 4 GB files ok. Is there any file size limit? Any ideas how to fix it? Thank you

**Comment by anaisbetts** [comment]
@klnmi97 so, even if we could fix this crash, I don't think this is a workable solution - even if we could create a 16GB executable, Windows will have to scan the entire 16GB in order to verify the signature when users download it. I think you'll have to download this file as part of your app's startup routine instead

**Comment by klnmi97** [comment]
@anaisbetts Thank you for your reply. I have also tried to create an installer with nupckg which contained a binary file which was a bit larger than 4GB and I got a different error. 
```
Squirrel : System.AggregateException: One or more errors occurred. ---> System.NotSupportedException: Unknown header: 688
At line:1 char:1
 Squirrel --releasify .\Package.1.0.0.nupkg
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : NotSpecified: (System.Aggregat...own header: 688:String) [], RemoteException
     FullyQualifiedErrorId : NativeCommandError
 
   at SharpCompress.Common.Zip.ZipHeaderFactory.ReadHeader(UInt32 headerBytes, BinaryReader reader, Boolean zip64)
   at SharpCompress.Common.Zip.StreamingZipHeaderFactory.<ReadStreamHeader>d__1.MoveNext()
   at SharpCompress.Readers.Zip.ZipReader.<GetEntries>d__6.MoveNext()
   at SharpCompress.Readers.AbstractReader`2.MoveToNextEntry()
   at Squirrel.ReleasePackage.<>c__DisplayClass14_0.<extractZipWithEscaping>b__0()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Squirrel.ReleasePackage.CreateReleasePackage(String outputFile, String packagesRootDir, Func`2 releaseNotesProcessor, Action`1 contentsPostProcessHook)
   at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon, Boolean generateMsi, Boolean 
packageAs64Bit, String frameworkVersion, Boolean generateDeltas)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)
```
Could you please elaborate on the maximum size of a single file inside the nuget package if such is known. I have not found any information about it. Thank you.
