### ISSUE TITLE
Realisify could not find file setup.exe

### ISSUE THREAD

**Issue by ThomasAllan** [Squirrel/Squirrel.Windows#1583]
I'm new to squirrel so there is probably a bit of user error in here. I'm guessing its something local to my enviroment but I'm struggling to find the issue. I'm trying to use Squirrel with a legacy VB.net WinForm application but I can see from #460 that it should work with VB.net

I've tried following both the [quick start guide](https://github.com/Squirrel/Squirrel.Windows/blob/develop/docs/getting-started/2-packaging.md) and this [youtube tutorial](https://www.youtube.com/watch?v=W8Qu4qMJyh4). 

Here is my nuget pacakage that I'm saving to my solution folder. 

![2020-01-29 17_27_58-NuGet Package Explorer - FITWallboard 1 0 0](https://user-images.githubusercontent.com/40633051/73380976-da2eb380-42bc-11ea-8f81-67823867a643.png)

Then in the Pacakage Manager Consol i'm running `squirrel --releasify FITWallboard.1.0.0.nupkg`

I'm getting the following error:
```
squirrel : System.IO.FileNotFoundException: Could not find file 
'C:\Users\allant\Repos\fit-wallboard\packages\squirrel.windows.1.9.1\tools\Setup.exe'.
At line:1 char:1
+ squirrel --releasify FITWallboard.1.0.0.nupkg
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (System.IO.FileN...ols\Setup.exe'.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
File name: 'C:\Users\allant\Repos\fit-wallboard\packages\squirrel.windows.1.9.1\tools\Setup.exe'
   at System.IO._
_Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, 
String signingOpts, String baseUrl, String setupIcon, Boolean generateMsi, String frameworkVersion, Boolean generateDeltas)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)
```

I have a 'C:\Users\allant\AppData\Local\SquirrelTemp' folder being created but is completly empty. 

I have an old SquirrelSetup.log file from 04/11/2019 form when I have tried this before but got stuck in the same place. The last entry in that log file was this:

```
2019-11-04 11:15:26> Program: Starting Squirrel Updater: --install .
2019-11-04 11:15:26> Program: Starting install, writing to C:\Users\allant\AppData\Local\SquirrelTemp
2019-11-04 11:15:26> Program: About to install to: C:\Users\allant\AppData\Local\Fork
2019-11-04 11:15:26> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\allant\AppData\Local\Fork\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2019-11-04 11:15:26> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\allant\AppData\Local\Fork\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2019-11-04 11:15:26> CheckForUpdateImpl: Reading RELEASES file from C:\Users\allant\AppData\Local\SquirrelTemp
2019-11-04 11:15:26> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2019-11-04 11:15:27> ApplyReleasesImpl: Writing files to app directory: C:\Users\allant\AppData\Local\Fork\app-1.41.1
2019-11-04 11:15:27> LogHost: Rigging execution stub for Fork_ExecutionStub.exe to C:\Users\allant\AppData\Local\Fork\Fork.exe
2019-11-04 11:15:28> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\allant\AppData\Local\Fork\app-1.41.1\Fork.exe]
2019-11-04 11:15:30> ApplyReleasesImpl: Starting fixPinnedExecutables
2019-11-04 11:15:30> ApplyReleasesImpl: Examining Pin: Android Studio.lnk
2019-11-04 11:15:30> ApplyReleasesImpl: Examining Pin: baretailpro.lnk
2019-11-04 11:15:30> ApplyReleasesImpl: Examining Pin: CMS Supervisor R18 -- English.lnk
2019-11-04 11:15:30> ApplyReleasesImpl: Examining Pin: Console Emulator (x64).lnk
2019-11-04 11:15:30> ApplyReleasesImpl: Examining Pin: Emit Support System.lnk
2019-11-04 11:15:30> ApplyReleasesImpl: Examining Pin: Emit Whirlpool Corporation Mail (1).lnk
2019-11-04 11:15:30> ApplyReleasesImpl: Examining Pin: File Explorer (2).lnk
2019-11-04 11:15:30> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2019-11-04 11:15:30> ApplyReleasesImpl: Examining Pin: Firefox Nightly.lnk
2019-11-04 11:15:30> ApplyReleasesImpl: Examining Pin: Firefox Personal.lnk
2019-11-04 11:15:30> ApplyReleasesImpl: Examining Pin: Firefox.lnk
2019-11-04 11:15:30> ApplyReleasesImpl: Examining Pin: Git Extensions.lnk
2019-11-04 11:15:30> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2019-11-04 11:15:30> ApplyReleasesImpl: Examining Pin: Internet Explorer.lnk
2019-11-04 11:15:30> ApplyReleasesImpl: Examining Pin: Notepad2.lnk
2019-11-04 11:15:30> ApplyReleasesImpl: Examining Pin: Priority Drive (1).lnk
2019-11-04 11:15:30> ApplyReleasesImpl: Examining Pin: Remote Desktop Connection.lnk
2019-11-04 11:15:30> ApplyReleasesImpl: Examining Pin: Samsung DeX.lnk
2019-11-04 11:15:30> ApplyReleasesImpl: Examining Pin: scrcpy-noconsole.lnk
2019-11-04 11:15:30> ApplyReleasesImpl: Examining Pin: Whirlpool Corporation Mail (1).lnk
2019-11-04 11:15:30> ApplyReleasesImpl: Fixing up tray icons
2019-11-04 11:15:30> ApplyReleasesImpl: cleanDeadVersions: for version 1.41.1
2019-11-04 11:15:30> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.41.1
2019-11-04 11:15:55> Program: Starting Squirrel Updater: --install .
2019-11-04 11:15:55> Program: Starting install, writing to C:\Users\allant\AppData\Local\SquirrelTemp
2019-11-04 11:15:55> Program: About to install to: C:\Users\allant\AppData\Local\Fork
2019-11-04 11:15:55> Program: Install path C:\Users\allant\AppData\Local\Fork already exists, burning it to the ground
2019-11-04 11:15:55> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\allant\AppData\Local\Fork\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2019-11-04 11:15:55> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\allant\AppData\Local\Fork\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2019-11-04 11:15:55> CheckForUpdateImpl: Reading RELEASES file from C:\Users\allant\AppData\Local\SquirrelTemp
2019-11-04 11:15:55> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2019-11-04 11:15:56> ApplyReleasesImpl: Writing files to app directory: C:\Users\allant\AppData\Local\Fork\app-1.41.1
2019-11-04 11:15:56> LogHost: Rigging execution stub for Fork_ExecutionStub.exe to C:\Users\allant\AppData\Local\Fork\Fork.exe
2019-11-04 11:15:57> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\allant\AppData\Local\Fork\app-1.41.1\Fork.exe]
2019-11-04 11:15:58> ApplyReleasesImpl: Starting fixPinnedExecutables
2019-11-04 11:15:58> ApplyReleasesImpl: Examining Pin: Android Studio.lnk
2019-11-04 11:15:58> ApplyReleasesImpl: Examining Pin: baretailpro.lnk
2019-11-04 11:15:58> ApplyReleasesImpl: Examining Pin: CMS Supervisor R18 -- English.lnk
2019-11-04 11:15:58> ApplyReleasesImpl: Examining Pin: Console Emulator (x64).lnk
2019-11-04 11:15:58> ApplyReleasesImpl: Examining Pin: Emit Support System.lnk
2019-11-04 11:15:58> ApplyReleasesImpl: Examining Pin: Emit Whirlpool Corporation Mail (1).lnk
2019-11-04 11:15:58> ApplyReleasesImpl: Examining Pin: File Explorer (2).lnk
2019-11-04 11:15:58> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2019-11-04 11:15:58> ApplyReleasesImpl: Examining Pin: Firefox Nightly.lnk
2019-11-04 11:15:58> ApplyReleasesImpl: Examining Pin: Firefox Personal.lnk
2019-11-04 11:15:58> ApplyReleasesImpl: Examining Pin: Firefox.lnk
2019-11-04 11:15:58> ApplyReleasesImpl: Examining Pin: Git Extensions.lnk
2019-11-04 11:15:58> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2019-11-04 11:15:58> ApplyReleasesImpl: Examining Pin: Internet Explorer.lnk
2019-11-04 11:15:58> ApplyReleasesImpl: Examining Pin: Notepad2.lnk
2019-11-04 11:15:58> ApplyReleasesImpl: Examining Pin: Priority Drive (1).lnk
2019-11-04 11:15:58> ApplyReleasesImpl: Examining Pin: Remote Desktop Connection.lnk
2019-11-04 11:15:58> ApplyReleasesImpl: Examining Pin: Samsung DeX.lnk
2019-11-04 11:15:58> ApplyReleasesImpl: Examining Pin: scrcpy-noconsole.lnk
2019-11-04 11:15:58> ApplyReleasesImpl: Examining Pin: Whirlpool Corporation Mail (1).lnk
2019-11-04 11:15:58> ApplyReleasesImpl: Fixing up tray icons
2019-11-04 11:15:58> ApplyReleasesImpl: cleanDeadVersions: for version 1.41.1
2019-11-04 11:15:58> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.41.1
```

**Comment by anaisbetts** [comment]
Well, does that file exist? My psychic debugger says that your 3rd party Antivirus "helpfully" removed it

**Comment by ThomasAllan** [comment]
The file does not exist... Latest log shows this. 
```
2020-01-30 10:36:07> Program: Starting Squirrel Updater: --releasify FITWallboard.1.0.0.nupkg
2020-01-30 10:36:07> Program: Bootstrapper EXE found at:C:\Users\allant\Repos\fit-wallboard\packages\squirrel.windows.1.9.1\tools\Setup.exe
2020-01-30 10:36:07> Program: Creating release package: C:\Users\allant\Repos\fit-wallboard\Releases\FITWallboard.1.0.0.nupkg
2020-01-30 10:36:07> ReleasePackage: Creating release package: C:\Users\allant\Repos\fit-wallboard\Releases\FITWallboard.1.0.0.nupkg => C:\Users\allant\Repos\fit-wallboard\Releases\FITWallboard-1.0.0-full.nupkg
2020-01-30 10:36:08> ReleasePackage: Extracting dependent packages: []
2020-01-30 10:36:08> ReleasePackage: Removing unnecessary data
2020-01-30 10:36:08> ReleasePackage: No release notes found in C:\Users\allant\AppData\Local\SquirrelTemp\tempa\FITWallboard.nuspec
2020-01-30 10:36:08> Utility: The file .\StubExecutable.exe does not exist
2020-01-30 10:36:09> Unhandled exception: System.IO.FileNotFoundException: Could not find file 'C:\Users\allant\Repos\fit-wallboard\packages\squirrel.windows.1.9.1\tools\Setup.exe'.
File name: 'C:\Users\allant\Repos\fit-wallboard\packages\squirrel.windows.1.9.1\tools\Setup.exe'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon, Boolean generateMsi, String frameworkVersion, Boolean generateDeltas)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
```

The 3rd party antivirus doesn't say that anything has been removed but I'm going to assume your right. As it is a work laptop, I'm guessing it has been deleted by something behind the scenes. 

Thanks for your help
