### ISSUE TITLE
Is anyone having problems installing?

### ISSUE THREAD

**Issue by Guyz1** [Squirrel/Squirrel.Windows#1610]
**Squirrel version(s)**
_Which version(s) of the project are you using?_
The latest version available on nuget

**Description**
I am using visual studio 2015. My project properties targets .net framework 4.7.2 

**Steps to recreate**
1. Right click on solution and go to manage nuget packages 
2. Search for squirrel windows
3. click install
4. I'm getting error..it fails to install.

**Expected behavior**
Install squirrel windows

**Actual behavior**
I get the error message:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Invalid static method invocation syntax: "[MSBuild]::NormalizePath('$(MSBuildThisFileDirectory)..\tools')". Method '[MSBuild]::NormalizePath' not found. Static method invocation should be of the form: $([FullTypeName]::Method()), e.g. $([System.IO.Path]::Combine(`a`, `b`)).   E:\College\·Diploma\Semester 6\FYP\Coding\Final\after SQLITE\after UI changes\after setup\convert to materialskin\Library Management System\packages\squirrel.windows.1.9.1\build\squirrel.windows.props			0	

**Additional information**
Here is the output while installing:

Attempting to gather dependency information for package 'squirrel.windows.1.9.1' with respect to project 'Library Management System', targeting '.NETFramework,Version=v4.7.2'
Attempting to resolve dependencies for package 'squirrel.windows.1.9.1' with DependencyBehavior 'Lowest'
Resolving actions to install package 'squirrel.windows.1.9.1'
Resolved actions to install package 'squirrel.windows.1.9.1'
Adding package 'DeltaCompressionDotNet.1.1.0' to folder 'E:\College\·Diploma\Semester 6\FYP\Coding\Final\after SQLITE\after UI changes\after setup\convert to materialskin\Library Management System\packages'
Added package 'DeltaCompressionDotNet.1.1.0' to folder 'E:\College\·Diploma\Semester 6\FYP\Coding\Final\after SQLITE\after UI changes\after setup\convert to materialskin\Library Management System\packages'
Added package 'DeltaCompressionDotNet.1.1.0' to 'packages.config'
Successfully installed 'DeltaCompressionDotNet 1.1.0' to Library Management System
Adding package 'Mono.Cecil.0.9.6.1' to folder 'E:\College\·Diploma\Semester 6\FYP\Coding\Final\after SQLITE\after UI changes\after setup\convert to materialskin\Library Management System\packages'
Added package 'Mono.Cecil.0.9.6.1' to folder 'E:\College\·Diploma\Semester 6\FYP\Coding\Final\after SQLITE\after UI changes\after setup\convert to materialskin\Library Management System\packages'
Added package 'Mono.Cecil.0.9.6.1' to 'packages.config'
Successfully installed 'Mono.Cecil 0.9.6.1' to Library Management System
Adding package 'SharpCompress.0.17.1' to folder 'E:\College\·Diploma\Semester 6\FYP\Coding\Final\after SQLITE\after UI changes\after setup\convert to materialskin\Library Management System\packages'
Added package 'SharpCompress.0.17.1' to folder 'E:\College\·Diploma\Semester 6\FYP\Coding\Final\after SQLITE\after UI changes\after setup\convert to materialskin\Library Management System\packages'
Added package 'SharpCompress.0.17.1' to 'packages.config'
Successfully installed 'SharpCompress 0.17.1' to Library Management System
Adding package 'Splat.1.6.2' to folder 'E:\College\·Diploma\Semester 6\FYP\Coding\Final\after SQLITE\after UI changes\after setup\convert to materialskin\Library Management System\packages'
Added package 'Splat.1.6.2' to folder 'E:\College\·Diploma\Semester 6\FYP\Coding\Final\after SQLITE\after UI changes\after setup\convert to materialskin\Library Management System\packages'
Added package 'Splat.1.6.2' to 'packages.config'
Successfully installed 'Splat 1.6.2' to Library Management System
Adding package 'squirrel.windows.1.9.1' to folder 'E:\College\·Diploma\Semester 6\FYP\Coding\Final\after SQLITE\after UI changes\after setup\convert to materialskin\Library Management System\packages'
Added package 'squirrel.windows.1.9.1' to folder 'E:\College\·Diploma\Semester 6\FYP\Coding\Final\after SQLITE\after UI changes\after setup\convert to materialskin\Library Management System\packages'
Install failed. Rolling back...
Package 'squirrel.windows.1.9.1 : DeltaCompressionDotNet [1.1.0, 2.0.0), Mono.Cecil [0.9.6.1, ), SharpCompress [0.17.1, 0.17.1], Splat [1.6.2, )' does not exist in project 'Library Management System'
Removed package 'Splat.1.6.2' from 'packages.config'
Removed package 'SharpCompress.0.17.1' from 'packages.config'
Removed package 'Mono.Cecil.0.9.6.1' from 'packages.config'
Removed package 'DeltaCompressionDotNet.1.1.0' from 'packages.config'
Removing package 'squirrel.windows.1.9.1 : DeltaCompressionDotNet [1.1.0, 2.0.0), Mono.Cecil [0.9.6.1, ), SharpCompress [0.17.1, 0.17.1], Splat [1.6.2, )' from folder 'E:\College\·Diploma\Semester 6\FYP\Coding\Final\after SQLITE\after UI changes\after setup\convert to materialskin\Library Management System\packages'
Removed package 'squirrel.windows.1.9.1 : DeltaCompressionDotNet [1.1.0, 2.0.0), Mono.Cecil [0.9.6.1, ), SharpCompress [0.17.1, 0.17.1], Splat [1.6.2, )' from folder 'E:\College\·Diploma\Semester 6\FYP\Coding\Final\after SQLITE\after UI changes\after setup\convert to materialskin\Library Management System\packages'
Removing package 'Splat.1.6.2' from folder 'E:\College\·Diploma\Semester 6\FYP\Coding\Final\after SQLITE\after UI changes\after setup\convert to materialskin\Library Management System\packages'
Removed package 'Splat.1.6.2' from folder 'E:\College\·Diploma\Semester 6\FYP\Coding\Final\after SQLITE\after UI changes\after setup\convert to materialskin\Library Management System\packages'
Removing package 'SharpCompress.0.17.1' from folder 'E:\College\·Diploma\Semester 6\FYP\Coding\Final\after SQLITE\after UI changes\after setup\convert to materialskin\Library Management System\packages'
Removed package 'SharpCompress.0.17.1' from folder 'E:\College\·Diploma\Semester 6\FYP\Coding\Final\after SQLITE\after UI changes\after setup\convert to materialskin\Library Management System\packages'
Removing package 'Mono.Cecil.0.9.6.1' from folder 'E:\College\·Diploma\Semester 6\FYP\Coding\Final\after SQLITE\after UI changes\after setup\convert to materialskin\Library Management System\packages'
Removed package 'Mono.Cecil.0.9.6.1' from folder 'E:\College\·Diploma\Semester 6\FYP\Coding\Final\after SQLITE\after UI changes\after setup\convert to materialskin\Library Management System\packages'
Removing package 'DeltaCompressionDotNet.1.1.0' from folder 'E:\College\·Diploma\Semester 6\FYP\Coding\Final\after SQLITE\after UI changes\after setup\convert to materialskin\Library Management System\packages'
Removed package 'DeltaCompressionDotNet.1.1.0' from folder 'E:\College\·Diploma\Semester 6\FYP\Coding\Final\after SQLITE\after UI changes\after setup\convert to materialskin\Library Management System\packages'
Microsoft.Build.Exceptions.InvalidProjectFileException: Invalid static method invocation syntax: "[MSBuild]::NormalizePath('$(MSBuildThisFileDirectory)..\tools')". Method '[MSBuild]::NormalizePath' not found. Static method invocation should be of the form: $([FullTypeName]::Method()), e.g. $([System.IO.Path]::Combine(`a`, `b`)).   E:\College\·Diploma\Semester 6\FYP\Coding\Final\after SQLITE\after UI changes\after setup\convert to materialskin\Library Management System\packages\squirrel.windows.1.9.1\build\squirrel.windows.props
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Shared.ProjectErrorUtilities.VerifyThrowInvalidProject(Boolean condition, String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object arg0, Object arg1)
   at Microsoft.Build.Evaluation.Expander`2.Function`1.Execute(Object objectInstance, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation)
   at Microsoft.Build.Evaluation.Expander`2.PropertyExpander`1.ExpandPropertyBody(String propertyBody, Object propertyValue, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation, UsedUninitializedProperties usedUninitializedProperties)
   at Microsoft.Build.Evaluation.Expander`2.PropertyExpander`1.ExpandPropertiesLeaveTypedAndEscaped(String expression, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation, UsedUninitializedProperties usedUninitializedProperties)
   at Microsoft.Build.Evaluation.Expander`2.PropertyExpander`1.ExpandPropertiesLeaveEscaped(String expression, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation, UsedUninitializedProperties usedUninitializedProperties)
   at Microsoft.Build.Evaluation.Expander`2.ExpandIntoStringLeaveEscaped(String expression, ExpanderOptions options, IElementLocation elementLocation)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluatePropertyElement(ProjectPropertyElement propertyElement)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluatePropertyGroupElement(ProjectPropertyGroupElement propertyGroupElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate()
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, ProjectRootElement root, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCache projectRootElementCache, BuildEventContext buildEventContext, ProjectInstance projectInstanceIfAnyForDebuggerOnly)
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation)
   at NuGet.PackageManagement.VisualStudio.MicrosoftBuildEvaluationProjectUtility.AddImportStatement(Project msBuildProject, String targetsPath, ImportLocation location)
   at NuGet.PackageManagement.VisualStudio.VSMSBuildNuGetProjectSystem.<>c__DisplayClass39_0.<<AddImport>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at NuGet.PackageManagement.VisualStudio.VSMSBuildNuGetProjectSystem.AddImport(String targetFullPath, ImportLocation location)
   at NuGet.ProjectManagement.MSBuildNuGetProject.<InstallPackageAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__54.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__54.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<ExecuteActionsAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<PerformActionImplAsync>d__6.MoveNext()
========== Finished ==========

**Comment by varKeytrap** [comment]
Seems to be a [VS2015 issue](https://github.com/kzu/GitInfo/issues/74#issuecomment-484910764). Can you upgrade to VS2019 ?

**Comment by owns** [comment]
Hello @Guyz1 .  I had this problem with vs2015.  I was lucky enough to upgrade, but I still remember my work-around.
1. manually download the nuget package
2. extract the package to your nuget cache accordingly (see how the other packages looks and follow the pattern).
    - if it's the older package style, you'll have a `packages` folder in your project.
    - if it's the new [PackageReference](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files) style, you'll want to extract to your nuget cache folder, usually `~\.nuget\packages`
3. in the package root, edit the file `builds/squirrel.windows.props`
    - replace `[MSBuild]::NormalizePath` with `[System.IO.Path]::GetFullPath`
4. Open your project and try adding the package.  It should use the cached version you made changes to.
