### ISSUE TITLE
Installing a full npkg from cli

### ISSUE THREAD

**Issue by MartinBeekhuizen** [Squirrel/Squirrel.Windows#1647]
We pre-released a new version of our executable and while testing we experienced some troubles with updating to the new version.
Unfortunately we didn't save the old version and are currently unable to test the scenario again.
We do have a list of nupkg files of previous releases.

I tried running the update.exe pointing to the full npkg file, resulting in the following error.
Is there by any chance a way to install the executable from one of these (full) nupkg files using the Update.exe cli?

```
2020-08-13` 11:29:25> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.IO.IOException: The directory name is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption)
   at System.IO.DirectoryInfo.GetFiles()
   at Squirrel.Update.Program.<Install>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.IO.IOException: The directory name is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption)
   at System.IO.DirectoryInfo.GetFiles()
   at Squirrel.Update.Program.<Install>d__4.MoveNext()<---
```

**Comment by anaisbetts** [comment]
Create a new RELEASES file with the new NuGet package and put both files in a folder, then run:

```sh
Update.exe --update \path\to\the\folder
```

The RELEASES file is easy to create by hand, you just need to be able to SHA1 files
