### ISSUE TITLE
Update fails with `Could not load file or assembly 'Mono.Cecil, Version=0.11.2.0` after updating to Squirrel 2.0.0

### ISSUE THREAD

**Issue by sanderaernouts** [Squirrel/Squirrel.Windows#1664]
**Squirrel version(s)**
2.0.0

**Description**
After updating to 2.0.0 out automatic update flow broke because Squirrel seems unable to load `Mono.Cecil 0.11.2`

**Steps to recreate**
1. Update to 2.0.0
2. Push an update with Squirrel
3. Push the 2nd update with Squirrel (so that the `UpdateManager` code is invoked on the version of the app using Squirrel 2.0.0)

**Expected behavior**
Once I updated to Squirrel 2.0.0 and had this version installed the automatic update process is failing with this error:
```
2020-09-25 16:08:47.635 +02:00 [INF] Downloading 1 updates
2020-09-25 16:09:01.314 +02:00 [INF] Updating to version 2.1.27
2020-09-25 16:09:23.696 +02:00 [ERR] An unexpected exception occured
System.IO.FileLoadException: Could not load file or assembly 'Mono.Cecil, Version=0.11.2.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'Mono.Cecil, Version=0.11.2.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e'
   at Squirrel.SquirrelAwareExecutableDetector.GetAssemblySquirrelAwareVersion(String executable)
   at Squirrel.SquirrelAwareExecutableDetector.<>c__DisplayClass1_0.<GetPESquirrelAwareVersion>b__0()
   at Squirrel.Utility.Retry[T](Func`1 block, Int32 retries)
   at Squirrel.SquirrelAwareExecutableDetector.GetPESquirrelAwareVersion(String executable)
   at Squirrel.SquirrelAwareExecutableDetector.<>c__DisplayClass0_0.<GetAllSquirrelAwareApps>b__2(String x)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Squirrel.SquirrelAwareExecutableDetector.GetAllSquirrelAwareApps(String directory, Int32 minimumVersion)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<invokePostInstall>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<ApplyReleases>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at KSimConnect.Launcher.Installer.Program.<RunUpdate>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at KSimConnect.Launcher.Installer.Program.<Main>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Actual behavior**
The app should update to `2.1.27`

**Additional information**
We are using `SquirrelAwareVersion 1`. Downgrading to the latest `1.9.x` release seems to fix the issue. But this does require a manual re-install of the app.

**Comment by anaisbetts** [comment]
This is fixed in 2.0.1

**Comment by sanderaernouts** [comment]
@anaisbetts that was fast! Thanks, I'll give that a try. We do already have people out there who have our app with Squirrel 2.0.0. Is there a graceful way to update them or is a manual update (re-install of setup.exe) required here?

**Comment by sanderaernouts** [comment]
In our case, a restart of the computer fixed it since we put a shortcut in the start-up folder. The update was a 100% completed but the next update we push will fix that 👍
