### ISSUE TITLE
app doesn't start after first installation

### ISSUE THREAD

**Issue by Alonzzzo2** [Squirrel/Squirrel.Windows#1675]
I must be doing something wrong...
After creating my setup.exe and installing the app, it just doesn't start.
I have multiple exe files in the installation dir but only one which is squirrel-aware (the logs also mention it)
When I try to manually run the app, it starts without any issues.

Here's the squirrel-install.log file from localappdata\squirreltemp\squirrel-install.log:
[02/11/20 15:25:52] info: Program: Starting Squirrel Updater: --install . --rerunningWithoutUAC
[02/11/20 15:25:52] info: Program: Starting install, writing to C:\Users\username\AppData\Local\SquirrelTemp
[02/11/20 15:25:52] info: Program: About to install to: C:\Users\username\AppData\Local\MyApp
[02/11/20 15:25:52] warn: Program: Install path C:\Users\username\AppData\Local\MyApp already exists, burning it to the ground
[02/11/20 15:25:53] info: CheckForUpdateImpl: Reading RELEASES file from C:\Users\username\AppData\Local\SquirrelTemp
[02/11/20 15:25:53] info: CheckForUpdateImpl: First run, starting from scratch
[02/11/20 15:25:54] info: ApplyReleasesImpl: Writing files to app directory: C:\Users\username\AppData\Local\MyApp\app-5.8.21
[02/11/20 15:25:54] info: LogHost: Rigging execution stub for ScopingToolWindow_ExecutionStub.exe to C:\Users\username\AppData\Local\MyApp\ScopingToolWindow.exe
[02/11/20 15:26:07] info: ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\username\AppData\Local\MyApp\app-5.8.21\MyApp.Desktop.Client.Launcher.exe]
[02/11/20 15:26:23] error: ApplyReleasesImpl: Couldn't run Squirrel hook, continuing: C:\Users\username\AppData\Local\MyApp\app-5.8.21\MyApp.Desktop.Client.Launcher.exe: System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Squirrel.Utility.<>c__DisplayClass11_0.<InvokeProcessAsync>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<InvokeProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass10_0.<<invokePostInstall>b__0>d.MoveNext()
[02/11/20 15:26:23] info: ApplyReleasesImpl: Starting fixPinnedExecutables
[02/11/20 15:26:23] info: ApplyReleasesImpl: Fixing up tray icons
[02/11/20 15:26:23] info: ApplyReleasesImpl: cleanDeadVersions: checking for version 5.8.21
[02/11/20 15:26:23] info: ApplyReleasesImpl: cleanDeadVersions: exclude new version folder app-5.8.21
[02/11/20 15:26:25] info: Program: Finished Squirrel Updater

From all of the documentation I read, the app should just start automatically after the first installation...
Any ideas?
Thanks!

**Comment by Alonzzzo2** [comment]
my bad. delete
