### ISSUE TITLE
autoUpdater Error: Command failed: 4294967295

### ISSUE THREAD

**Issue by plusflabby** [Squirrel/Squirrel.Windows#1677]
**Squirrel version(s)**
latest

**Description**
When checking for an update an error is thrown. The error logged is below.

**Steps to recreate**
1. use the auto update feed url `https:\updates.arma-server.com\download\arma-server\stable\x64\2.0.0`

**Expected behavior**
Update is downloaded

**Actual behavior**
error is thrown and update is not downloaded

**Additional information**
Here's the log generated by `autoUpdater.on('error'`

```
[2020-11-04 01:45:11.229] [error] Error: Command failed: 4294967295
System.AggregateException: One or more errors occurred. ---> System.Exception: The directory https:\updates.arma-server.com\download\arma-server\stable\x64\2.0.0 does not exist, something is probably broken with your application
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)
---> (Inner Exception #0) System.Exception: The directory https:\updates.arma-server.com\download\arma-server\stable\x64\2.0.0 does not exist, something is probably broken with your application
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()<---


    at AutoUpdater.emitError (electron/js2c/browser_init.js:17:1391)
    at electron/js2c/browser_init.js:17:968
    at electron/js2c/browser_init.js:21:1005
    at ChildProcess.<anonymous> (electron/js2c/browser_init.js:21:732)
    at ChildProcess.emit (events.js:310:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)

```

**Comment by anaisbetts** [comment]
I have no idea what you're saying, and you haven't specified what you actually passed in as the update URL, or what you expect to see.

**Comment by plusflabby** [comment]
@anaisbetts I've updated my comment

**Comment by anaisbetts** [comment]
I think your web URL has backspaces instead of forward spaces. Also, make sure that https://whatever.your.url/is/RELEASES exists and is downloadable via a regular GET request

**Comment by plusflabby** [comment]
@anaisbetts Yep! Using forward spaces eliminated the error. Thank you.
