### ISSUE TITLE
Certificate not found when code signing with a HSM token

### ISSUE THREAD

**Issue by chingchang** [Squirrel/Squirrel.Windows#1680]
**Squirrel version(s)**
2.0.0

**Description**
I am not able to code sign using a HSM token. The consequence is I have to write a script to `signtool` all our binaries and dependencies, but unfortunately that does not sign the Update.exe and MyApp.exe that are deployed to the LocalAppData folder, so we are running into some issues with AntiVirus.

**Steps to recreate**
1. Run `Squirrel.exe --releasify .\MyApp.nupkg -n "/tr http://timestamp.digicert.com /td sha256 /fd sha256 /n 'MyCertificateName'"` where `MyCertificateName` is an identifier for the cert into the HSM token.

**Expected behavior**
It should run successfully just like `signtool sign /tr http://timestamp.digicert.com /td sha256 /fd sha256 /n 'MyCertificateName'` does.

**Actual behavior**
```
System.AggregateException: One or more errors occurred. ---> System.Exception: Failed to sign, command invoked was: 'C:\MyApp\Release\squirrel.windows.2.0.0\tools\signtool.exe sign /tr http://timestamp.digicert.com /td sha256 /fd sha256 /n 'MyCertificateName' C:\Users\ching\AppData\Local\SquirrelTemp\tempa\lib\net46\MyApp_ExecutionStub.exe'
   at Squirrel.Update.Program.<signPEFile>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<>c__DisplayClass10_0.<<Releasify>b__14>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Squirrel.Utility.<>c__DisplayClass13_1`1.<<ForEachAsync>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Squirrel.Update.Program.<>c__DisplayClass10_0.<Releasify>b__7(String pkgPath)
   at Squirrel.ReleasePackage.CreateReleasePackage(String outputFile, String packagesRootDir, Func`2 releaseNotesProcessor, Action`1 contentsPostProcessHook)
   at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon, Boolean generateMsi, Boolean packageAs64Bit, String frameworkVersion, Boolean generateDeltas)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)
---> (Inner Exception #0) System.Exception: Failed to sign, command invoked was: 'C:\MyCertificateName\Release\squirrel.windows.2.0.0\tools\signtool.exe sign /tr http://timestamp.digicert.com /td sha256 /fd sha256 /n 'MyCertificateName' C:\Users\ching\AppData\Local\SquirrelTemp\tempa\lib\net46\MyApp_ExecutionStub.exe'
   at Squirrel.Update.Program.<signPEFile>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<>c__DisplayClass10_0.<<Releasify>b__14>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Squirrel.Utility.<>c__DisplayClass13_1`1.<<ForEachAsync>b__1>d.MoveNext()<---
```

**Comment by chingchang** [comment]
Debugging into the code, I found that the actual error message is "SignTool Error: No certificates were found that met all the given criteria." 

signtool is able to find the certificate correctly when I run it directly, and I verified that Squirrel.exe is running in the same user context. Squirrel.exe simply calls Process to launch signtool, what could be the difference?

**Comment by chingchang** [comment]
I found that this error is due to how single quotes are dealt with differently in PowerShell. 'MyCertificateName' works when it is invoked in Powershell, but not when invoked directly nor from the shell. Changing the command to the following works:
`Squirrel.exe --releasify .\MyApp.nupkg -n "/tr http://timestamp.digicert.com /td sha256 /fd sha256 /n \"MyCertificateName\""`
