### ISSUE TITLE
Update.exe on C++ app fails to checkForUpdate 

### ISSUE THREAD

**Issue by J0Nes90** [Squirrel/Squirrel.Windows#1688]
**Squirrel version(s)**
2.0.1

I am integration Squirrel.Windows in a C++ application. Neither `Update.exe --checkForUpdate` nor `Update.exe --update` does work as expected.
My app is flagged and detected as a SquirrelAwareVersion. The app responds to the Squirrel Startup commands by simply exiting with code 0 for all parameters but squirrel-firstrun.

I have a local Releases folder `C:\Users\jones\Downloads\Releases` that contains
```
MyApp-1.0.0-full.nupkg
MyApp-1.0.1-delta.nupkg
MyApp-1.0.1-full.nupkg
RELEASES
```
and the `RELEASES` file looks correct to my eyes.

From within my app I call `Update.exe --checkForUpdate C:\Users\jones\Downloads\Releases`, the working directory is the "AppData/Local/MyApp" aka the root of Update.exe.
The update process outputs some progress on stdout, e.g. `33\r\n66\r\n100\r\n` but fails to output a JSON file as I would expect it. I'd like to use this --checkForUpdate invocation to determine whether or not an update is available.

The log looks like this:
```
[16/12/20 19:30:13] info: Program: Starting Squirrel Updater: --checkForUpdate C:\Users\jones\Downloads\Releases
[16/12/20 19:30:13] info: Program: Fetching update information, downloading from C:\Users\jones\Downloads\Releases
[16/12/20 19:30:13] info: CheckForUpdateImpl: Using existing staging user ID: 0f186aae-de3a-5f3c-b5cd-849a4167590d
[16/12/20 19:30:13] info: CheckForUpdateImpl: Reading RELEASES file from C:\Users\jones\Downloads\Releases
[16/12/20 19:30:13] warn: UpdateInfo: Couldn't get release notes for:MyApp-1.0.1-delta.nupkg: System.IO.FileNotFoundException: Could not find file 'C:\Users\jones\AppData\Local\MyApp\packages\MyApp-1.0.1-delta.nupkg'.
File name: 'C:\Users\jones\AppData\Local\MyApp\packages\MyApp-1.0.1-delta.nupkg'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at NuGet.ZipPackage.<>c__DisplayClass9_0.<.ctor>b__0()
   at NuGet.ZipPackage.EnsureManifest()
   at Squirrel.ReleaseEntry.GetReleaseNotes(String packageDirectory)
   at Squirrel.UpdateInfo.<FetchReleaseNotes>b__19_0(ReleaseEntry x)
[16/12/20 19:30:13] info: Program: Finished Squirrel Updater
```

**Comment by anaisbetts** [comment]
"the operation was cancelled" means that your app took too long during the install hook. Are you using any single-instance type code in your app? Make sure that Squirrel runs before it

**Comment by J0Nes90** [comment]
Yeah, moving the hook code closer to the app entry fixes the update code! Thanks!
Still, the checkForUpdate seems to not work. Alternatively I could use —download and check if something new pops up in the packages folder and then use —update after that but it looks like it will download the packages twice then

**Comment by anaisbetts** [comment]
What happens if you run it from the commandline, do you see the expected output? You might not be reading the pipe right

**Comment by J0Nes90** [comment]
If I run Squirrel.com from CMD I get the very same output in the console.

**Comment by anaisbetts** [comment]
Hm, I'm not sure, I get the right output. I would delete the log file, then run the `.com` file from the command-line then see if there's a crash or not. Remember that the path you want to pass to `--checkForUpdates` is the path to the directory, not to the RELEASES file

**Comment by J0Nes90** [comment]
I've figured that Squirrel.com looks for the packages folder in C:\Users\jones\AppData\MyApp\packages\ whereas Update.exe seems to look in C:\Users\jones\AppData\Local\MyApp\packages\
Is that expected? I am always running Squirrel.com from Local\MyApp hence this cannot work.

It does report a crash, indeed:
```
[17/12/20 14:55:15] fatal: Finished with unhandled exception: System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()<---
```

That being said I copied MyApp from AppData/local to AppData and I run Squirrel.com from that new place - same issue.
No comes the fun part, if I run Squirrel.com from the original place AppData/Local it works as expected printing

```
33
66
100
{"currentVersion":"1.0.0","futureVersion":"1.0.1","releasesToApply":[{"version":"1.0.1","releaseNotes":""}]}
```

so something seems to be off with the Squirrel.exe

**Comment by anaisbetts** [comment]
This is expected, Squirrel uses the directory that it's in to determine all kinds of stuff like the app name and current version

**Comment by J0Nes90** [comment]
Update.com does the trick! Nice, this is great!
Thank you so much for your help and in general for this project!
