### ISSUE TITLE
Cannot run "releasify" due to needing FIPS enabled

### ISSUE THREAD

**Issue by mattpadgett** [Squirrel/Squirrel.Windows#1689]
**Squirrel version(s)**
2.0.1

**Description**
While following tutorial in getting started for the example project I came across the problem when calling "Squirrel --releasify..." regarding FIPS

**Steps to recreate**
1. Follow "Getting Started"

**Expected behavior**
Candle.exe is erroring on the fact that FIPS is enabled on my machine per requirement. There should be a mechanism within Squirrel such as a flag to enable FIPS but I am unable to find one. Maybe I'm just not seeing this?

**Actual behavior**
Successfully run the "releasify" procedure with the fips flag.

**Additional information**
Error log for context:

```
Output was:
candle.exe : error CNDL0308 : The Federal Information Processing Standard (FIPS) appears to be enabled on the machine. You must either disable FIPS or use FIPS-compliant security algorithms to generate IDs by passing the -fips command-line switch or by setting <FipsCompliant>true</FipsCompliant> in your .wixproj project.
   at Squirrel.Update.Program.<createMsiPackage>d__21.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon, Boolean generateMsi, Boolean packageAs64Bit, String frameworkVersion, Boolean generateDeltas)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.Exception: Failed to compile WiX template, command invoked was: 'candle.exe -nologo -ext WixNetFxExtension -out "C:\Users\[Removed]\Downloads\MyApp\Releases\Setup.wixobj" "C:\Users\[Removed]\Downloads\MyApp\Releases\Setup.wxs"'
```

**Comment by runehalfdan** [comment]
Looks quite trivial to fix (in code), but requires some testing: 


https://stackoverflow.com/questions/56467603/how-to-enforce-candle-exe-fips-with-fips-or-fipscomplianttrue-fipscompliant
