### ISSUE TITLE
Cannot use package to update application (Github)

### ISSUE THREAD

**Issue by GENERALFAME** [Squirrel/Squirrel.Windows#1695]
**Squirrel version(s)**
Squirrel.Windows 1.9.0

**Description**
I'm tring to update my application with:
`UpdateManager.GitHubUpdateManager`

but since a few day i am unable to do this, because of the following exception:

```
2021-01-14 14:04:16.202 +01:00 [ERR] Error { ExceptionDetail: [("Type": "System.InvalidOperationException"), ("HResult": -2146233079), ("Message": "Sequence contains no elements"), ("Source": "System.Linq")], MemoryUsage: 9461640 }
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Squirrel.UpdateManager.GitHubUpdateManager(String repoUrl, String applicationName, String rootDirectory, IFileDownloader urlDownloader, Boolean prerelease, String accessToken)
   at MyNamespace.UpdateModule.Initialize(ICore appCore)
```

maybe i'm doing something wrong

**Steps to recreate**
No recreation succesfull

**Additional information**
My Code looks the following (the exception occurs afert the first if ):

```
if(Debugger.IsAttached)
{
    return;
}

UpdateManager updateManager = await UpdateManager.GitHubUpdateManager("https://github.com/myorg/myProject", "myProgramName");

if (!Environment.GetCommandLineArgs().Contains("--squirrel-updated"))
{
    SquirrelAwareApp.HandleEvents(
        v => updateManager.CreateShortcutForThisExe(),
        v => updateManager.RemoveShortcutForThisExe());
}

UpdateInfo updateInfo = updateManager.CheckForUpdate(true).Result;

var progress = new ProgressBar.Contracts.ProgressBar();

if (updateInfo.CurrentlyInstalledVersion.Version < updateInfo.FutureReleaseEntry.Version)
{
    if (MessageBox.Show($"New Version is available {updateInfo.FutureReleaseEntry.Version}",
        "New version",
        MessageBoxButton.YesNo,
        MessageBoxImage.Information) == MessageBoxResult.Yes)
    {
        progress.Show();

        updateManager.DownloadReleases(updateInfo.ReleasesToApply, x => progress.SetProgress(x))
            .ContinueWith((t) =>
            {
                updateManager.ApplyReleases(updateInfo, progress.SetProgress)
                    .ContinueWith(x =>
                    {
                        UpdateManager.RestartApp();
                        return false;
                    });
            }).RunSynchronously();
    }
}

progress.Close();
```

**Comment by GENERALFAME** [comment]
fixed this bug by myself. Problem was that i had no offical release on my github (only prelease) and that was the problem
