### ISSUE TITLE
Renamed the electron app and now cannot update the old app.

### ISSUE THREAD

**Issue by Mansidialpad** [Squirrel/Squirrel.Windows#1726]
We recently updated our app name, therefore changing the executable as well as the nupkg names. The update failed with the following error (HIDING the name for privacy reasons), could you please help me with the possible reasons? The RELEASES file contains the new app name, the nupkg also exists in the path. I do not see any log about a download of the package but I see an error that it was not found.
> 2021-07-01 13:25:17> Program: Starting Squirrel Updater: --checkForUpdate https://hiddenblobpath
2021-07-01 13:25:17> Program: Fetching update information, downloading from https://hiddenblobpath
2021-07-01 13:25:17> CheckForUpdateImpl: Using existing staging user ID: 248d47aa-ca23-5a48-b36f-3877e81d54d7
2021-07-01 13:25:17> CheckForUpdateImpl: Downloading RELEASES file from https://hiddenblobpath
2021-07-01 13:25:17> FileDownloader: Downloading url: https://hiddenblobpath/RELEASES?id=oldname&localVersion=2.2.1&arch=amd64
2021-07-01 13:25:17> UpdateInfo: Couldn't get release notes for:newname-3.0.2-delta.nupkg: System.IO.FileNotFoundException: Could not find file 'C:\Users\Shash\AppData\Local\oldname\packages\newname-3.0.2-delta.nupkg'.
File name: 'C:\Users\Shash\AppData\Local\oldname\packages\newname-3.0.2-delta.nupkg'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at NuGet.ZipPackage.<>c__DisplayClass9_0.<.ctor>b__0()
   at NuGet.ZipPackage.EnsureManifest()
   at NuGet.ZipPackage..ctor(String filePath, Boolean enableCaching)
   at Squirrel.ReleaseEntry.GetReleaseNotes(String packageDirectory)
   at Squirrel.UpdateInfo.<FetchReleaseNotes>b__19_0(ReleaseEntry x)

**Comment by anaisbetts** [comment]
Ya I mean, you can't really do that. A separate Nuget Package ID is a separate app to Squirrel. You need to do an explicit migration and write your own code to move everything over, which for an Electron app is going to be pretty non-trivial to get right

**Comment by Mansidialpad** [comment]
I have made all the changes on electron end to make sure the name is different. I want to understand why the download is not happening? Is there anything in the release file that I can change?

**Comment by anaisbetts** [comment]
There is no easy way to make this scenario work, sorry

**Comment by Mansidialpad** [comment]
It actually worked for me.
