### ISSUE TITLE
Getting System.Exception: Invalid release entry

### ISSUE THREAD

**Issue by woophi** [Squirrel/Squirrel.Windows#1734]
**Squirrel version(s)**
Squirrel.Windows 2.0.1 - not sure

**Description**
So, I have an electron application which using update-electron-app to download a new release from github repo. Then it uses Squirrel to update an application. But I getting error - Invalid release entry. What release type should be? To bundle electron app into release I use @electron-forge/maker-squirrel

```
Command failed: 4294967295
System.AggregateException: One or more errors occurred. ---> System.Exception: Invalid release entry: {"name":"1.0.9","notes":"","url":"https://github.com/woophi/el-test/releases/download/1.0.9/win32-x64.zip"}
```

**Additional information**

```
Command failed: 4294967295
System.AggregateException: One or more errors occurred. ---> System.Exception: Invalid release entry: {"name":"1.0.9","notes":"","url":"https://github.com/woophi/el-test/releases/download/1.0.9/win32-x64.zip"}
   at Squirrel.ReleaseEntry.ParseReleaseEntry(String entry)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Squirrel.ReleaseEntry.ParseReleaseFileAndApplyStaging(String fileContents, Nullable`1 userToken)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<CheckForUpdate>d__7.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)
---> (Inner Exception #0) System.Exception: Invalid release entry: {"name":"1.0.9","notes":"","url":"https://github.com/woophi/el-test/releases/download/1.0.9/win32-x64.zip"}
   at Squirrel.ReleaseEntry.ParseReleaseEntry(String entry)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Squirrel.ReleaseEntry.ParseReleaseFileAndApplyStaging(String fileContents, Nullable`1 userToken)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<CheckForUpdate>d__7.MoveNext()<---

```

**Comment by wimurk** [comment]
I got the same issue. Anyone know how to fix this? Already took 4 days to even set the publisher up. It's error after error.

**Comment by anaisbetts** [comment]
Well, is your release entry invalid? Open up the `RELEASES` file and find out, it is an extremely simple format

**Comment by caesay** [comment]
@wimurk  I had a look at your repository `singlequote/scum-bot`. 

Github release v1.0.0 has `Setup.exe`, the `*1.0.0-full.nupkg`, and the file `RELEASES` uploaded as assets. This is correct. From your comment, it looks like you are trying to update to v1.0.1 - but the only file uploaded as asset to release v1.0.1 is `Simply-Scum-Bot-win32-x64-1.0.1.zip`. You need to upload the -full.nupkg and RELEASES file to every GitHub release. 

Additionally, you should upload `-delta.nupkg` files to each release too, if you wish to enable small/fast delta updates, but these are optional.

**Comment by wimurk** [comment]
@caesay i added all the files and still gives an error
```
System.Exception: Invalid release entry: {"name":"v1.0.1","notes":null,"url":"https://github.com/singlequote/scum-bot/releases/download/v1.0.1/Simply-Scum-Bot-win32-x64-1.0.1.zip"}
   bij Squirrel.ReleaseEntry.ParseReleaseEntry(String entry)
   bij System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   bij System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   bij System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   bij System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   bij Squirrel.ReleaseEntry.ParseReleaseFileAndApplyStaging(String fileContents, Nullable`1 userToken)
   bij Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Squirrel.UpdateManager.<CheckForUpdate>d__8.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()
   --- Einde van intern uitzonderingsstackpad ---
   bij System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   bij Squirrel.Update.Program.executeCommandLine(String[] args)
   bij Squirrel.Update.Program.main(String[] args)
   bij Squirrel.Update.Program.Main(String[] args)
---> (Interne uitzondering #0) System.Exception: Invalid release entry: {"name":"v1.0.1","notes":null,"url":"https://github.com/singlequote/scum-bot/releases/download/v1.0.1/Simply-Scum-Bot-win32-x64-1.0.1.zip"}
   bij Squirrel.ReleaseEntry.ParseReleaseEntry(String entry)
   bij System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   bij System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   bij System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   bij System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   bij Squirrel.ReleaseEntry.ParseReleaseFileAndApplyStaging(String fileContents, Nullable`1 userToken)
   bij Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Squirrel.UpdateManager.<CheckForUpdate>d__8.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()<---


```

**Comment by caesay** [comment]
Glad this solves your issue. I see the same problem on the repository of the original poster. The way to close this would be to  improve the error messages from Squirrel or migrate electron-winstaller to my fork which already has these improvements.
