### ISSUE TITLE
Suboptimal behavior when the hook application fails to run

### ISSUE THREAD

**Issue by sredna** [Squirrel/Squirrel.Windows#1786]
**Squirrel version(s)**
Unknown

**Description**

I tried to install the GitHub Desktop application on 32-bit Windows even though the application turns out to be a 64-bit application. At some point during the Squirrel splash screen a "installation failed" error dialog pops up. Clicking on "Open Setup Log" does nothing!

Manually inspecting `%LocalAppData%\SquirrelTemp\Squirrel-Install.log` reveals
````
<--- Snipped --->
error: ApplyReleasesImpl: Couldn't run Squirrel hook, continuing: C:\Users\Anders\AppData\Local\GitHubDesktop\app-2.9.6\GitHubDesktop.exe: System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Squirrel.Utility.<InvokeProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass10_0.<<invokePostInstall>b__0>d.MoveNext()
<--- Snipped --->
````

This is perhaps not that surprising but I would at least expect it to create a Start menu shortcut or something. Neither does it manage to create a uninstall entry. The uninstaller (`update.exe --uninstall`) executes (silently) without errors but leaves several files behind:
````
C:\Users\Anders\AppData\Local\GitHubDesktop\.dead
C:\Users\Anders\AppData\Local\GitHubDesktop\Update.exe
C:\Users\Anders\AppData\Local\GitHubDesktop\app-2.9.6\squirrel.exe
C:\Users\Anders\AppData\Local\GitHubDesktop\app-2.9.6\v8_context_snapshot.bin
````

`%Temp%\Squirrel-Uninstall.log` has the same 0x80004005 exception as the installer.

**Steps to recreate**
 - Download and run GitHub Desktop on 32-bit Windows 10.

**Expected behavior**
- Failing to run the hook application is perhaps the package authors fault but Squirrel could be more helpful instead of staying silent. 
- Create a start menu entry?
- Create uninstall entry?
- Uninstalling should not leave junk behind!

**Actual behavior**
- Uninstalling leaves junk behind!

---

I realize this is mostly a issue the packager (GitHub Desktop in this case) needs to fix but Squirrel should at least be able to install and uninstall correctly even though the hook application fails to run.

**Comment by caesay** [comment]
A hook failing to run will not break Squirrel, technically, but inside the hook is usually where the start menu and uninstall entry get created. `GitHubDesktop.exe` would be the process responsible for creating shortcuts etc. 

Poor error handling during setup, and not cleaning up files after uninstalling, are both issues in this version of Squirrel which are improved in [the fork I maintain](https://github.com/clowd/Clowd.Squirrel).

I also think it's a great idea for the installer to check the bitness of the Squirrel Aware binaries, and refuse to install if the package is incompatible with the current OS - so I have created an [issue to track this](https://github.com/clowd/Clowd.Squirrel/issues/35) and it will implemented in my fork shortly.
