### ISSUE TITLE
squirrel --releasify throws 'File is not a PE image' exception

### ISSUE THREAD

**Issue by teamboyd** [Squirrel/Squirrel.Windows#1832]
**Squirrel version(s)**
2.0.1

**Description**
squirrel --releasify throws 'File is not a PE image' exception

**Steps to recreate**
1. I have a myapp.nuspec file I created via the  documentation in [Visual Studio Packaging](https://github.com/Squirrel/Squirrel.Windows/blob/develop/docs/using/visual-studio-packaging.md)
2. I execute nuget pack to create the .nupkg file (nuget pack myapp.nuspec -Version 1.0.0.0 -Properties Configuration=Release -OutputDirectory bin\Release\ -BasePath bin\Release\
3. I then execute the squirrel --releasify myapp.1.0.0.nupkg and this throws the exception.

**Expected behavior**
I expect squirrel to build my release files.

**Actual behavior**
When executing the 'squirrel --releasify myapp.1.0.0.nupkg' it throws the 'File is not a PE image' exception.

**Additional information**
Here's the call stack...
    + CategoryInfo          : NotSpecified: (System.Aggregat... not a PE image:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
   at Squirrel.Utility.ExecutableUsesWin32Subsystem(String peImage)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Concurrent.Partitioner.DynamicPartitionerForIEnumerable`1.InternalPartitionEnumerable.GrabChunk_Buffered(KeyValuePair`2[] destArray, Int32 requestedChunkSize, Int32& actualNumElementsGrabbed)
   at System.Collections.Concurrent.Partitioner.DynamicPartitionerForIEnumerable`1.InternalPartitionEnumerator.GrabNextChunk(Int32 requestedChunkSize)
   at System.Collections.Concurrent.Partitioner.DynamicPartitionEnumerator_Abstract`2.MoveNext()
   at Squirrel.Utility.<>c__DisplayClass13_1`1.<<ForEachAsync>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Squirrel.Update.Program.<>c__DisplayClass10_0.<Releasify>b__7(String pkgPath)
   at Squirrel.ReleasePackage.CreateReleasePackage(String outputFile, String packagesRootDir, Func`2 releaseNotesProcessor, Action`1 contentsPostProcessHook)
   at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon, Boolean generateMsi, Boolean packageAs64Bit, String 
frameworkVersion, Boolean generateDeltas)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)
---> (Inner Exception #0) System.Exception: File is not a PE image
   at Squirrel.Utility.ExecutableUsesWin32Subsystem(String peImage)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Concurrent.Partitioner.DynamicPartitionerForIEnumerable`1.InternalPartitionEnumerable.GrabChunk_Buffered(KeyValuePair`2[] destArray, Int32 requestedChunkSize, Int32& actualNumElementsGrabbed)
   at System.Collections.Concurrent.Partitioner.DynamicPartitionerForIEnumerable`1.InternalPartitionEnumerator.GrabNextChunk(Int32 requestedChunkSize)
   at System.Collections.Concurrent.Partitioner.DynamicPartitionEnumerator_Abstract`2.MoveNext()
   at Squirrel.Utility.<>c__DisplayClass13_1`1.<<ForEachAsync>b__1>d.MoveNext()<---

**Comment by teamboyd** [comment]
@jjeffery  do you possibly have more details on your solution to [issue #1034](https://github.com/Squirrel/Squirrel.Windows/issues/1034)

**Comment by teamboyd** [comment]
I found what the issue is.  In my .nuspec file, the <id/> node's text had a dash in it.  The documentation states no spaces or dots should be used but it states nothing about dashes.  For example, this causes releasify to fail  <id>My-App</id> and throws the "File is not a PE image" exception.  This happens because the logic falls through and makes it's way to that point in the source code.  The code should look for invalid characters in the Package ID and throw an exception (stating exactly the issue with the Package ID) before it falls through to the "File is not a PE image" exception.

**Comment by caesay** [comment]
Dashes and dots can be used in the package ID [in my fork of this project](https://github.com/clowd/Clowd.Squirrel), and any invalid / unsupported package id's will be validated and rejected if they are incorrect. It's one of many bugs which have been fixed there.

Also, in the fork, it is not required to create a nupkg yourself. You can just use the new `pack` command and give it a folder of files (eg. the output of your build) and it will create all the necessary packages for you.
