### ISSUE TITLE
Installation has failed version 2.0.1

### ISSUE THREAD

**Issue by CryptoMIS** [Squirrel/Squirrel.Windows#1834]
**Squirrel version(s)**
2.0.1
**Description**

When installing getting error Installation has failed, after checking the log there are two exception which are because of MS Teams. Even the MS teams installed error message indicate it unable to find the some logs and installation. 

![image](https://user-images.githubusercontent.com/45265141/201525853-d39c4334-c644-4999-b99e-b357ffe64655.png)

logs

2022-06-12 12:56:26> Program: Starting Squirrel Updater: --install . --checkInstall --source=PROPLUS --silent --exeName=Teams.exe
2022-06-12 12:56:26> RegistryService: TryGetRegKey: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\Configuration\ProductReleaseIds exists. Data - OneNoteFreeRetail,O365ProPlusRetail
2022-06-12 12:56:26> RegistryService: TryGetRegKey: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\Configuration\AudienceData exists. Data - Production::CC
2022-06-12 12:56:26> RegistryService: TryGetRegKey: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\LastScenario exists. Data - UPDATE
2022-06-12 12:56:26> RegistryService: RegKeyExists: HKEY_CURRENT_USER\Software\Policies\Microsoft\Cloud\Office\16.0\Teams does not exist
2022-06-12 12:56:26> Program: Registry value Software\Policies\Microsoft\Cloud\Office\16.0\Teams\PreventFirstLaunchAfterInstall does not exist
2022-06-12 12:56:26> RegistryService: RegKeyExists: HKEY_CURRENT_USER\Software\Policies\Microsoft\Office\16.0\Teams does not exist
2022-06-12 12:56:26> Program: Registry value Software\Policies\Microsoft\Office\16.0\Teams\PreventFirstLaunchAfterInstall does not exist
2022-06-12 12:56:26> RegistryService: RegKeyExists: HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Teams does not exist
2022-06-12 12:56:26> Program: Registry value Software\Microsoft\Office\16.0\Teams\PreventFirstLaunchAfterInstall does not exist
2022-06-12 12:56:26> Program: Registry flags are not set: proceed with default value NotConfigured
2022-06-12 12:56:26> RegistryService: RegKeyExists: HKEY_CURRENT_USER\Software\Microsoft\Office\Teams does not exist
2022-06-12 12:56:26> LogHost: Write failed.
2022-06-12 12:56:26> LogHost: Message: Scenario.Status: success, scenario: 780b972b-76d0-4fa1-9ff7-758903a5bd79, Scenario.Name: desktop_squirrel_install, Scenario.Step: start, sequence: 0, appversion: 1.5.00.8070, platformId: 27, DeviceInfo.OsName: Windows, DeviceInfo.CpuArchitecture: x64, DeviceInfo.OsVersion: 10.0.22000.0, AppInfo.ProcessArchitecture: x86, AppInfo.ClientType: desktop, dllSearchPathState: unset, clientType: desktop, source: msi, distSrc: PROPLUS_OneNoteFreeRetail,O365ProPlusRetail, breadcrumb: , ppChannel: Production::CC, ppInstallMode: UPDATE, autoStartGpoPolicy: NotConfigured, desktopSession: desktop-ebb3941d-fa2c-4a09-8e69-3ba2117f89df, installSessionId: 24887f3755a378cd6ca5585abfaafaff93d14222056ac24bc87ca7e9f82cd0cb, delta: 16, scenarioDelta: 16, elapsed: 1655034986592, stepDelta: 0, DeviceInfo.ComputerUuid: 09052220b3f4d401a5b2f4b301d4a5b6, DeviceInfo.OfficeMachineId: 23d8eb8196b4ec4c81b215931ab726c7, InstallerVersion: 1.10.84.0, eventpdclevel: 1, userpdclevel: 0
2022-06-12 12:56:26> LogHost: Stack trace: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\44740\AppData\Roaming\Microsoft\Teams\SquirrelTelemetry.log'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at Telemetry.AriaWrapper.LogToFile(String message)
2022-06-12 12:56:26> Program: Starting install, writing to C:\Users\44740\AppData\Local\SquirrelTemp
2022-06-12 12:56:26> Program: File does not contain contextual info: Teams.exe
2022-06-12 12:56:26> UpdateManager: using rootAppDirectory: C:\Users\44740\AppData\Local\Microsoft\Teams
2022-06-12 12:56:26> Program: About to install to: C:\Users\44740\AppData\Local\Microsoft\Teams
2022-06-12 12:56:26> Program: Setup.json exist, copying over
2022-06-12 12:56:26> RegistryService: RegKeyExists: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Run has TeamsMachineInstaller. Data - C:\Program Files (x86)\Teams Installer\Teams.exe --checkInstall --source=PROPLUS
2022-06-12 12:56:26> RegistryService: TrySetRegKey: HKEY_CURRENT_USER\Software\Microsoft\Office\Teams\InstallSource created
2022-06-12 12:56:26> RegistryService: TrySetRegKey: HKEY_CURRENT_USER\Software\Microsoft\Office\Teams\InstallSource set successfully as MSI
2022-06-12 12:56:26> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\44740\AppData\Local\Microsoft\Teams\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2022-06-12 12:56:26> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\44740\AppData\Local\Microsoft\Teams\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__7.MoveNext()
2022-06-12 12:56:26> CheckForUpdateImpl: Reading RELEASES file from C:\Users\44740\AppData\Local\SquirrelTemp
2022-06-12 12:56:26> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2022-06-12 12:56:26> RegistryService: RegKeyExists: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\Teams\ does not exist
2022-06-12 12:56:26> ApplyReleasesImpl: No delta packages found. Applying current release package.
2022-06-12 12:56:26> ApplyReleasesImpl: getting squirrel aware apps failed with exception Could not find a part of the path 'C:\Users\44740\AppData\Local\Microsoft\Teams\current'.
2022-06-12 12:56:26> ApplyReleasesImpl: Writing files to app directory: C:\Users\44740\AppData\Local\Microsoft\Teams\current
2022-06-12 12:56:30> RegistryService: RegKeyExists: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\Teams\ does not exist
2022-06-12 12:56:30> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\44740\AppData\Local\Microsoft\Teams\current\Teams.exe]
2022-06-12 12:56:33> ApplyReleasesImpl: About to RemoveOldShorcuts for Teams.exe, rootAppDir C:\Users\44740\AppData\Local\Microsoft\Teams
2022-06-12 12:56:33> RegistryService: RegKeyExists: HKEY_CURRENT_USER\Software\Policies\Microsoft\Cloud\Office\16.0\Teams does not exist
2022-06-12 12:56:33> ApplyReleasesImpl: Registry value Software\Policies\Microsoft\Cloud\Office\16.0\Teams\PreventFirstLaunchAfterInstall does not exist
2022-06-12 12:56:33> RegistryService: RegKeyExists: HKEY_CURRENT_USER\Software\Policies\Microsoft\Office\16.0\Teams does not exist
2022-06-12 12:56:33> ApplyReleasesImpl: Registry value Software\Policies\Microsoft\Office\16.0\Teams\PreventFirstLaunchAfterInstall does not exist
2022-06-12 12:56:33> RegistryService: RegKeyExists: HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Teams does not exist
2022-06-12 12:56:33> ApplyReleasesImpl: Registry value Software\Microsoft\Office\16.0\Teams\PreventFirstLaunchAfterInstall does not exist
2022-06-12 12:56:33> ApplyReleasesImpl: Registry flags are not set: proceed with default value NotConfigured
2022-06-12 12:56:33> ApplyReleasesImpl: Starting fixPinnedExecutables
2022-06-12 12:56:33> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2022-06-12 12:56:33> ApplyReleasesImpl: Examining Pin: Git Bash.lnk
2022-06-12 12:56:33> ApplyReleasesImpl: Examining Pin: Git Extensions.lnk
2022-06-12 12:56:33> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2022-06-12 12:56:33> ApplyReleasesImpl: Examining Pin: Microsoft Edge.lnk
2022-06-12 12:56:33> ApplyReleasesImpl: Examining Pin: Visual Studio 2022.lnk
2022-06-12 12:56:33> ApplyReleasesImpl: Fixing up tray icons
2022-06-12 12:56:33> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__34_0(RegistryView view)
2022-06-12 12:56:33> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__34_0(RegistryView view)
2022-06-12 12:56:33> MeetingAddinInstaller: System.ArgumentException: Cannot delete a subkey tree because the subkey does not exist.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at Microsoft.Win32.RegistryKey.DeleteSubKeyTree(String subkey, Boolean throwOnMissingSubKey)
   at Microsoft.Win32.RegistryKey.DeleteSubKeyTree(String subkey)
   at Squirrel.MeetingAddinInstaller.<InstallMeetingAddinAsync>d__15.MoveNext()
2022-06-12 12:56:33> MeetingAddinInstaller: StagedAppDirectory does not exist. Using Current
2022-06-12 12:56:33> MeetingAddinInstaller: There is no version.txt. Falling back to getting version from folder name
2022-06-12 12:56:33> MeetingAddinInstaller: Version: 1.0.22062.1; addinPackageDirectory: 1.0.22062.1
2022-06-12 12:56:33> MeetingAddinInstaller: .dead exists: False
2022-06-12 12:56:33> MeetingAddinInstaller: path to .dead: C:\Users\44740\AppData\Local\Microsoft\TeamsMeetingAddin\1.0.22062.1\.dead
2022-06-12 12:56:33> MeetingAddinInstaller: before cleanup unused versions
2022-06-12 12:56:33> MeetingAddinInstaller: Addin directory exists. Copy was successful
2022-06-12 12:56:33> MeetingAddinInstaller: Version 1.0.22062.1 of the meeting add-in is now installed
2022-06-12 12:56:33> PresenceAddinInstaller: Installing Teams Presence addin for Outlook...
2022-06-12 12:56:33> PresenceAddinInstaller: Copying C:\Users\44740\AppData\Local\Microsoft\Teams\current\resources\assets\tlb\Uc.tlb to C:\Users\44740\AppData\Local\Microsoft\TeamsPresenceAddin
2022-06-12 12:56:33> PresenceAddinInstaller: Copying C:\Users\44740\AppData\Local\Microsoft\Teams\current\resources\assets\tlb\Uc.win32.tlb to C:\Users\44740\AppData\Local\Microsoft\TeamsPresenceAddin
2022-06-12 12:56:33> PresenceAddinInstaller: check if UC TypeLib points to current\resources\assets\tlb\Uc.tlb
2022-06-12 12:56:33> PresenceAddinInstaller: Registering UC Typelib WIN32 under HKCU...
2022-06-12 12:56:33> PresenceAddinInstaller: UC Typelib WIN32 successfully registered to C:\Users\44740\AppData\Local\Microsoft\TeamsPresenceAddin\Uc.win32.tlb under HKCU!
2022-06-12 12:56:33> PresenceAddinInstaller: UC Typelib WIN64 is registered under HKLM and file exists. Registration not needed!
2022-06-12 12:56:33> PresenceAddinInstaller: IM Provider registry key already exists!
2022-06-12 12:56:33> ApplyReleasesImpl: cleanDeadVersions: for original version of  and current version of 1.5.00.8070
2022-06-12 12:56:33> ApplyReleasesImpl: cleanDeadVersions: exclude current folder stage
2022-06-12 12:56:34> RegistryService: TryDeleteRegKey: HKEY_CURRENT_USER\Software\Microsoft\Office\Teams\PreventInstallationFromMsi not found
2022-10-22 11:56:46> Program: Starting Squirrel Updater: --install . --exeName=MSTeamsSetup_c_l_.exe --bootstrapperMode
2022-10-22 11:56:46> Program: bootStrapperModeSettings: pdsEndpoint:https://teams.microsoft.com/desktopclient/installer/windows/
2022-10-22 11:56:46> Program: bootStrapperModeSettings: fallbackNextGenAppPayloadUrlX64:https://aka.ms/maglev-x64
2022-10-22 11:56:46> Program: bootStrapperModeSettings: fallbackNextGenAppPayloadUrlX86:https://aka.ms/maglev-x86
2022-10-22 11:56:46> Program: bootStrapperModeSettings: fallbackNextGenAppPayloadUrlARM64:https://aka.ms/maglev-arm64
2022-10-22 11:56:46> Program: bootStrapperModeSettings: getInstallerEndpointUrl:https://teams.live.com/downloads/getinstaller
2022-10-22 11:56:46> RegistryService: TryGetRegKey: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\CurrentMajorVersionNumber exists. Data - 10
2022-10-22 11:56:46> RegistryService: TryGetRegKey: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\CurrentMinorVersionNumber exists. Data - 0
2022-10-22 11:56:46> RegistryService: TryGetRegKey: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\CurrentBuildNumber exists. Data - 22000
2022-10-22 11:56:46> FileDownloader: Downloading url: https://teams.live.com/downloads/getinstaller?intent=Life&arch=x64&platVersion=10.0.22000
2022-10-22 11:56:46> BootstrapperInstallManager: getinstaller endpoint returned installer path https://statics.teams.cdn.office.net/production-windows-x64/22260.203.1605.4995/MicrosoftTeams-x64.msix
2022-10-22 11:56:46> BootstrapperInstallManager: No decoded deep link is returned from get installer endpoint. Continue install without deep link
2022-10-22 11:56:46> Program: Installing the Teams 2 client
2022-10-22 11:56:49> Program: Detected existing Teams 2 client installation.
2022-11-11 20:57:26> Program: Starting Squirrel Updater: --install . --checkInstall --source=PROPLUS --silent --exeName=Teams.exe
2022-11-11 20:57:26> RegistryService: TryGetRegKey: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\Configuration\ProductReleaseIds exists. Data - OneNoteFreeRetail,O365ProPlusRetail
2022-11-11 20:57:26> RegistryService: TryGetRegKey: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\Configuration\AudienceData exists. Data - Production::CC
2022-11-11 20:57:26> RegistryService: TryGetRegKey: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\LastScenario exists. Data - UPDATE
2022-11-11 20:57:26> RegistryService: RegKeyExists: HKEY_CURRENT_USER\Software\Policies\Microsoft\Cloud\Office\16.0\Teams does not exist
2022-11-11 20:57:26> Program: Registry value Software\Policies\Microsoft\Cloud\Office\16.0\Teams\PreventFirstLaunchAfterInstall does not exist
2022-11-11 20:57:26> RegistryService: RegKeyExists: HKEY_CURRENT_USER\Software\Policies\Microsoft\Office\16.0\Teams does not exist
2022-11-11 20:57:26> Program: Registry value Software\Policies\Microsoft\Office\16.0\Teams\PreventFirstLaunchAfterInstall does not exist
2022-11-11 20:57:26> RegistryService: RegKeyExists: HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Teams does not exist
2022-11-11 20:57:26> Program: Registry value Software\Microsoft\Office\16.0\Teams\PreventFirstLaunchAfterInstall does not exist
2022-11-11 20:57:26> Program: Registry flags are not set: proceed with default value NotConfigured
2022-11-11 20:57:26> RegistryService: RegKeyExists: HKEY_CURRENT_USER\Software\Microsoft\Office\Teams has PreventInstallationFromMsi. Data - 1
2022-11-11 20:57:26> Program: Ignored request to install from Teams Installer (MSI) because PreventInstallationFromMsi was found and is set in registry
2022-11-12 11:44:45> Program: Starting Squirrel Updater: --install . --checkInstall --source=PROPLUS --silent --exeName=Teams.exe
2022-11-12 11:44:45> RegistryService: TryGetRegKey: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\Configuration\ProductReleaseIds exists. Data - OneNoteFreeRetail,O365ProPlusRetail
2022-11-12 11:44:45> RegistryService: TryGetRegKey: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\Configuration\AudienceData exists. Data - Production::CC
2022-11-12 11:44:45> RegistryService: TryGetRegKey: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\LastScenario exists. Data - UPDATE
2022-11-12 11:44:45> RegistryService: RegKeyExists: HKEY_CURRENT_USER\Software\Policies\Microsoft\Cloud\Office\16.0\Teams does not exist
2022-11-12 11:44:45> Program: Registry value Software\Policies\Microsoft\Cloud\Office\16.0\Teams\PreventFirstLaunchAfterInstall does not exist
2022-11-12 11:44:45> RegistryService: RegKeyExists: HKEY_CURRENT_USER\Software\Policies\Microsoft\Office\16.0\Teams does not exist
2022-11-12 11:44:45> Program: Registry value Software\Policies\Microsoft\Office\16.0\Teams\PreventFirstLaunchAfterInstall does not exist
2022-11-12 11:44:45> RegistryService: RegKeyExists: HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Teams does not exist
2022-11-12 11:44:45> Program: Registry value Software\Microsoft\Office\16.0\Teams\PreventFirstLaunchAfterInstall does not exist
2022-11-12 11:44:45> Program: Registry flags are not set: proceed with default value NotConfigured
2022-11-12 11:44:45> RegistryService: RegKeyExists: HKEY_CURRENT_USER\Software\Microsoft\Office\Teams has PreventInstallationFromMsi. Data - 1
2022-11-12 11:44:45> Program: Ignored request to install from Teams Installer (MSI) because PreventInstallationFromMsi was found and is set in registry
2022-11-12 22:57:35> Program: Starting Squirrel Updater: --install . --checkInstall --source=PROPLUS --silent --exeName=Teams.exe
2022-11-12 22:57:35> RegistryService: TryGetRegKey: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\Configuration\ProductReleaseIds exists. Data - OneNoteFreeRetail,O365ProPlusRetail
2022-11-12 22:57:35> RegistryService: TryGetRegKey: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\Configuration\AudienceData exists. Data - Production::CC
2022-11-12 22:57:35> RegistryService: TryGetRegKey: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun\LastScenario exists. Data - UPDATE
2022-11-12 22:57:35> RegistryService: RegKeyExists: HKEY_CURRENT_USER\Software\Policies\Microsoft\Cloud\Office\16.0\Teams does not exist
2022-11-12 22:57:35> Program: Registry value Software\Policies\Microsoft\Cloud\Office\16.0\Teams\PreventFirstLaunchAfterInstall does not exist
2022-11-12 22:57:35> RegistryService: RegKeyExists: HKEY_CURRENT_USER\Software\Policies\Microsoft\Office\16.0\Teams does not exist
2022-11-12 22:57:35> Program: Registry value Software\Policies\Microsoft\Office\16.0\Teams\PreventFirstLaunchAfterInstall does not exist
2022-11-12 22:57:35> RegistryService: RegKeyExists: HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Teams does not exist
2022-11-12 22:57:35> Program: Registry value Software\Microsoft\Office\16.0\Teams\PreventFirstLaunchAfterInstall does not exist
2022-11-12 22:57:35> Program: Registry flags are not set: proceed with default value NotConfigured
2022-11-12 22:57:35> RegistryService: RegKeyExists: HKEY_CURRENT_USER\Software\Microsoft\Office\Teams has PreventInstallationFromMsi. Data - 1
2022-11-12 22:57:35> Program: Ignored request to install from Teams Installer (MSI) because PreventInstallationFromMsi was found and is set in registry

Windows 11, Visual Studio 2022

**Expected behavior**
Successful installation 

**Actual behavior**
Getting error, even though installation is successful and app working as expected.

**Comment by CryptoMIS** [comment]
Using version 2.0.1

**Comment by anaisbetts** [comment]
Teams uses a private fork of Squirrel.Windows with unknown changes, we unfortunately cannot support it
