### ISSUE TITLE
NullReferenceException in parseShortcutLocations

### ISSUE THREAD

**Issue by joshuawarner32** [Squirrel/Squirrel.Windows#226]
If I run `Update.exe --createShortcuts app/0.5.1/MyApp.exe`, I get the following exception:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.Update.Program.parseShortcutLocations(String shortcutArgs)
   at Squirrel.Update.Program.Shortcut(String exeName, String shortcutArgs)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)
```

I can't be completely confident, since I don't have an environment where I can effectively compile/debug Squirrel.Windows, but I'm going to hazard a guess that the following should fix the problem:

```
diff --git a/src/Update/Program.cs b/src/Update/Program.cs
index 7a845c9..dc45761 100644
--- a/src/Update/Program.cs
+++ b/src/Update/Program.cs
@@ -629,14 +629,17 @@ static string getAppNameFromDirectory(string path = null)
         static ShortcutLocation? parseShortcutLocations(string shortcutArgs)
         {
             var ret = default(ShortcutLocation?);
-            var args = shortcutArgs.Split(new[] { ',' });
-
-            foreach (var arg in args) {
-                var location = (ShortcutLocation)(Enum.Parse(typeof(ShortcutLocation), arg, false));
-                if (ret.HasValue) {
-                    ret |= location;
-                } else {
-                    ret = location;
+            if(shortcutArgs != null)
+            {
+                var args = shortcutArgs.Split(new[] { ',' });
+
+                foreach (var arg in args) {
+                    var location = (ShortcutLocation)(Enum.Parse(typeof(ShortcutLocation), arg, false));
+                    if (ret.HasValue) {
+                        ret |= location;
+                    } else {
+                        ret = location;
+                    }
                 }
             }
```

**Comment by paulcbetts** [comment]
@joshuawarner32 `createShortcuts` only takes an executable name, not a path.

**Comment by joshuawarner32** [comment]
@paulcbetts - Thanks, but that's not the issue here.

It doesn't matter what argument I pass to `--createShortcuts` (I've tried the executable name, path, and random strings), I get the same exception.
