### ISSUE TITLE
CheckForUpdate fails to establish SSL/TLS connection with GitHub

### ISSUE THREAD

**Issue by BarryThePenguin** [Squirrel/Squirrel.Windows#237]
Running CheckForUpdate against a RELEASES file in GitHub fails with the following:

```
20:31:59 | Update | Version check failed.: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Squirrel.Utility.<LogIfThrows>d__4b`1.MoveNext() in c:\Users\Paul\code\squirrel\squirrel.windows\src\Squirrel\Utility.cs:line 477
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Squirrel.FileDownloader.<DownloadUrl>d__13.MoveNext() in c:\Users\Paul\code\squirrel\squirrel.windows\src\Squirrel\FileDownloader.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__28.MoveNext() in c:\Users\Paul\code\squirrel\squirrel.windows\src\Squirrel\UpdateManager.CheckForUpdates.cs:line 70
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Squirrel.UpdateManager.<CheckForUpdate>d__0.MoveNext() in c:\Users\Paul\code\squirrel\squirrel.windows\src\Squirrel\UpdateManager.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SparkleShare.SparkleUpdater.<CheckForNewVersionAsync>d__25.MoveNext() in d:\Projects\SparkleShare\SparkleShare\Windows\SparkleUpdater.cs:line 185
```

The updateUrlOrPath = "https://github.com/BarryThePenguin/SparkleShare/releases/download/1.5.0"

**Comment by BarryThePenguin** [comment]
[TODO](http://stackoverflow.com/questions/28290571/intermittent-ssl-tls-error-using-azure-sdk-in-azure-website)

ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;

**Comment by BarryThePenguin** [comment]
Turns our SparkleShare is setting the ServicePointManager.ServerCertificateValidationCallback...

**Comment by C1rdec** [comment]
Some of my Windows 7 users are experiencing this Issue what's the best solution?

**Comment by anaisbetts** [comment]
https://kevinchalet.com/2019/04/11/forcing-an-old-net-application-to-support-tls-1-2-without-recompiling-it/
