### ISSUE TITLE
Squirrel fails to delete some folders

### ISSUE THREAD

**Issue by 50Wliu** [Squirrel/Squirrel.Windows#239]
So I was mucking around in `SquirrelSetup.log` today after wondering why Atom was taking so long to update (realized it was because I was a few versions behind and Squirrel had to create deltas for every newer version).

Anyway, I noticed that it threw a few errors near the end while deleting the old version of Atom:
First exception:

```
Utility: DeleteDirectory: could not delete - C:\Users\<User>\AppData\Local\atom\app-0.174.0\resources\app\node_modules\language-todo: System.IO.IOException: The directory is not empty.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Squirrel.Utility.<DeleteDirectory>d__36.MoveNext()
```

Second exception block:

```
Utility: DeleteDirectory: could not delete - C:\Users\<User>\AppData\Local\atom\app-0.174.0\resources\app\node_modules: System.IO.IOException: The directory is not empty.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Squirrel.Utility.<DeleteDirectory>d__36.MoveNext()
Utility: DeleteDirectory: could not delete - C:\Users\<User>\AppData\Local\atom\app-0.174.0\resources\app: System.IO.IOException: The directory is not empty.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Squirrel.Utility.<DeleteDirectory>d__36.MoveNext()
Utility: DeleteDirectory: could not delete - C:\Users\<User>\AppData\Local\atom\app-0.174.0\resources: System.IO.IOException: The directory is not empty.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Squirrel.Utility.<DeleteDirectory>d__36.MoveNext()
Utility: DeleteDirectory: could not delete - C:\Users\<User>\AppData\Local\atom\app-0.174.0: System.IO.IOException: The directory is not empty.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Squirrel.Utility.<DeleteDirectory>d__36.MoveNext()
```

So I checked, and obviously `app-0.174.0` was still there.  Went in a few folders and found that the only things remaining was `app-0.174.0\resources\app\node_modules\language-todo\`.  `language-todo` was 100% empty.
So now I'm wondering why Squirrel failed to delete `language-todo` even when it was in fact empty.

Unrelated: Would it be possible to add timestamps to the log? :)

**Comment by flagbug** [comment]
Is version 0.174 the version you were upgrading from?

**Comment by 50Wliu** [comment]
No, 0.179-->0.182.0.  0.174 was the version I upgraded from when going to 0.179.0.

**Comment by Thieum** [comment]
@50Wliu Is it something that is still happening with the latest version of Squirrel?

**Comment by 50Wliu** [comment]
Haven't used Squirrel in a _long_ time, so I don't know, unfortunately.

**Comment by shiftkey** [comment]
@50Wliu thanks for the follow up. Going to close this out because we don't have much else to go on.
