### ISSUE TITLE
Inconsistent data length

### ISSUE THREAD

**Issue by vegar** [Squirrel/Squirrel.Windows#245]
I get the following error when trying to install with the generated `setup.exe`:

```
IEnableLogger: Failed to install package to app dir: System.IO.FileFormatException: Compressed part has inconsistent data length.
   at MS.Internal.IO.Packaging.CompressStream.UpdateUncompressedDataLength(Int64 dataLength)
   at MS.Internal.IO.Packaging.CompressStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at MS.Internal.IO.Zip.ProgressiveCrcCalculatingStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at MS.Internal.IO.Zip.ZipIOModeEnforcingStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.InternalCopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Stream.CopyTo(Stream destination)
   at NuGet.StreamExtensions.ToStreamFactory(Stream stream)
   at NuGet.ZipPackageFile..ctor(PackagePart part)
   at NuGet.ZipPackage.<GetFilesNoCache>b__12(PackagePart part)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NuGet.ZipPackage.GetFilesNoCache()
   at NuGet.ZipPackage.GetFilesBase()
   at NuGet.LocalPackage.GetFiles()
   at NuGet.PackageExtensions.GetFiles(IPackage package, String directory)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<installPackageToAppDir>d__84.MoveNext()
```

The source package is read by nuget package explorer without problem, but the package generated by `squirrel --releasify` is not.

How should I go by to solve this issue?

**Comment by Thieum** [comment]
@vegar do you still have this issue with the latest version of Squirrel?

**Comment by vegar** [comment]
Have not tried the last four years...
