### ISSUE TITLE
Unable to update when RELEASES file contains multiple entries with the same version

### ISSUE THREAD

**Issue by eggapauli** [Squirrel/Squirrel.Windows#251]
When Squirrel releasifies the same version multiple times, the RELEASES file contains multiple entries with the same version. When updating the application, it crashes because at some point it only expected a single release entry.
A fix could be to remove existing entries with the same version from the RELEASES file when releasifying the app.
Here is the important part of the stack trace:

    System.InvalidOperationException: Sequence contains more than one matching element
       at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
       at Squirrel.Utility.FindCurrentVersion(IEnumerable`1 localReleases)
       at Squirrel.UpdateManager.CheckForUpdateImpl.determineUpdateInfo(IEnumerable`1 localReleases, IEnumerable`1 remoteReleases, Boolean ignoreDeltaUpdates)
       at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__28.MoveNext()

**Comment by paulcbetts** [comment]
@eggapauli Hm, legit. Wonder why we're not paving over the old entry.

**Comment by GeertvanHorrik** [comment]
When will this PR be accepted?

**Comment by paulcbetts** [comment]
This isn't a PR...

**Comment by GeertvanHorrik** [comment]
But https://github.com/Squirrel/Squirrel.Windows/pull/256 is that solves this issue?
