### ISSUE TITLE
ObjectDisposedException in Update.exe -  0.9.0.1

### ISSUE THREAD

**Issue by willdean** [Squirrel/Squirrel.Windows#257]
I've just had the attached crash during install.

This appears to be a race between the `using (var animatedGifWindowToken = new CancellationTokenSource())` being disposed and the thread in AnimatedGifWindow.ShowWindow running.  By the time the thread gets to token.Register (line 76 in the current source), the CTS has been disposed.

I think there needs to be some kind of Cancel/Join with with the ShowWindow thread before allowing the CTS to be disposed.

I have a vague feeling there might be a bunch of races in ShowWindow, but I haven't yet worked out what it all does - is the idea that it doesn't display anything for initialDelay, and only acts if update.exe runs for longer than that?  The `catch(Exception) { return}`  around the first Delay is a bit disconcerting, but given that the whole thing is on a background thread, a general exception catch around the whole lot would be a good idea to prevent the app crashing completely if there's a problem.

Could @eggapauli's final comment on #228 this morning be the same issue?

`Application: Update.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ObjectDisposedException
Stack:
   at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
   at System.Threading.CancellationTokenSource.InternalRegister(System.Action-1<System.Object>, System.Object, System.Threading.SynchronizationContext, System.Threading.ExecutionContext)
   at System.Threading.CancellationToken.Register(System.Action-1<System.Object>, System.Object, Boolean, Boolean)
   at System.Threading.CancellationToken.Register(System.Action)
   at Squirrel.Update.AnimatedGifWindow+<>c__DisplayClass8.<ShowWindow>b__1()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()`

**Comment by eggapauli** [comment]
I don't show a gif, so it might be something different.

**Comment by eggapauli** [comment]
Ohh you're right, I just attached a debugger to Update.exe and it's exactly the same exception.

**Comment by paulcbetts** [comment]
I just pushed v0.9.1, can someone verify this was fixed?

**Comment by willdean** [comment]
I've upgraded to 0.9.1 and successfully run an install, but it was a race condition anyway, so time will tell.  I think perhaps more robust fixes than this are possible without too much risk.  I will keep testing.
