### ISSUE TITLE
Running --install when already installed causes a crash

### ISSUE THREAD

**Issue by CharlieHess** [Squirrel/Squirrel.Windows#290]
When upgrading their app to a new version, users often grab the latest `Setup.exe` and run it, which simply calls `Update.exe --install`. If the app is already installed, this crash occurs:

```
Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\andrea.johnson\AppData\Local\SquirrelTemp
CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\andrea.johnson\AppData\Local\slack\packages\RELEASES'.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__28.MoveNext()
CheckForUpdateImpl: Reading RELEASES file from C:\Users\andrea.johnson\AppData\Local\SquirrelTemp
CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
ApplyReleasesImpl: Writing files to app directory: C:\Users\andrea.johnson\AppData\Local\slack\app-1.0.0
ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\andrea.johnson\AppData\Local\slack\app-1.0.0\slack.exe]
ApplyReleasesImpl: Starting fixPinnedExecutables
ApplyReleasesImpl: fixPinnedExecutables: oldAppDirectories is empty, this is pointless
ApplyReleasesImpl: cleanDeadVersions: for version 1.0.0
ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.0.0
```

**Comment by junjunruan** [comment]
Hi,

How do you know when run the Setup.exe, it will call Update.exe --install? It would be helpful if you can send me a link as references. Thanks.

**Comment by Thieum** [comment]
@CharlieHess is it an issue that is still happening with the most recent version of Squirrel?
