### ISSUE TITLE
Installations fail with "Given path format not supported"

### ISSUE THREAD

**Issue by paulcbetts** [Squirrel/Squirrel.Windows#291]
```
ApplyReleasesImpl: Writing files to app directory: C:\Users\mike.oconnor\AppData\Local\slack\app-1.0.0
IEnableLogger: Failed to update local releases file: System.NotSupportedException: The given path's format is not supported.
  at System.Security.Util.StringExpressionSet.CanonicalizePath(String path, Boolean needFullPath)
  at System.Security.Util.StringExpressionSet.CreateListFromExpressions(String[] str, Boolean needFullPath)
  at System.Security.Permissions.FileIOPermission.AddPathList(FileIOPermissionAccess access, AccessControlActions control, String[] pathListOrig, Boolean checkForDuplicates, Boolean needFullPath, Boolean copyPathList)
at System.Security.Permissions.FileIOPermission..ctor(FileIOPermissionAccess access, String[] pathList, Boolean checkForDuplicates, Boolean needFullPath)
  at System.IO.DirectoryInfo.Init(String path, Boolean checkHost)
  at System.IO.DirectoryInfo..ctor(String path)
  at Squirrel.Utility.WithTempFile(String& path)
  at Squirrel.ReleaseEntry.BuildReleasesFile(String releasePackagesDir)
  at Squirrel.UpdateManager.ApplyReleasesImpl.<updateLocalReleasesFile>b__ec()
  at System.Threading.Tasks.Task`1.InnerInvoke()
  at System.Threading.Tasks.Task.Execute()
```

**Comment by paulcbetts** [comment]
```cs
        internal static String CanonicalizePath( String path, bool needFullPath )
        {
 
#if !PLATFORM_UNIX
            if (path.IndexOf( '~' ) != -1)
            {
                string longPath = null;
                GetLongPathName(path, JitHelpers.GetStringHandleOnStack(ref longPath));
                path = (longPath != null) ? longPath : path;
            }
 
            if (path.IndexOf( ':', 2 ) != -1)
                throw new NotSupportedException( Environment.GetResourceString( "Argument_PathFormatNotSupported" ) );
#endif // !PLATFORM_UNIX               
 
            if (needFullPath)
            {
                String newPath = System.IO.Path.GetFullPathInternal( path );
                if (path.EndsWith( m_directorySeparator + ".", StringComparison.Ordinal ))
                {
                    if (newPath.EndsWith( m_directorySeparator ))
                    {
                        newPath += ".";
                    }
                    else
                    {
                        newPath += m_directorySeparator + ".";
                    }
                }                
                return newPath;
            }
            else
                return path;
        }
    }
```

**Comment by willdean** [comment]
Something odd about his TEMP environment variable?
