### ISSUE TITLE
Include path when PathTooLongException occurs

### ISSUE THREAD

**Issue by kevinsawicki** [Squirrel/Squirrel.Windows#304]
It would make debugging much easier if the path was included when a `PathTooLongException` exception is thrown.

```
>> System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
>>    at System.IO.PathHelper.GetFullPathName()
>>    at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
>>    at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength)
>>    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>>    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
>>    at Squirrel.DeltaPackageBuilder.createDeltaForSingleFile(FileInfo targetFile, DirectoryInfo workingDirectory, Dictionary`2 baseFileListing) in c:\Users\Paul\code\squirrel\squirrel.windows\src\Squirrel\DeltaPackage.cs:line 163
>>    at Squirrel.DeltaPackageBuilder.CreateDeltaPackage(ReleasePackage basePackage, ReleasePackage newPackage, String outputFile) in c:\Users\Paul\code\squirrel\squirrel.windows\src\Squirrel\DeltaPackage.cs:line 74
>>    at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon) in c:\Users\Paul\code\squirrel\squirrel.windows\src\Update\Program.cs:line 368
>>    at Squirrel.Update.Program.main(String[] args) in c:\Users\Paul\code\squirrel\squirrel.windows\src\Update\Program.cs:line 146
>>    at Squirrel.Update.Program.Main(String[] args) in c:\Users\Paul\code\squirrel\squirrel.windows\src\Update\Program.cs:line 36
```

**Comment by willdean** [comment]
The difficulty with this it that it's the framework throwing that exception, not Squirrel - even if it did lots of catching, modfying exception messages and rethrowing, Squirrel still may not have the exact path which caused the exception (because it's been modified by the framework).    

Do you have relative paths in the nuspec file which would become very long when converted to a full path name?

**Comment by kevinsawicki** [comment]
> Do you have relative paths in the nuspec file which would become very long when converted to a full path name?

I definitely had paths that were super long that were causing this exception.

**Comment by danceswithdolphin** [comment]
I am getting the error 
"The specified path, file name, or both are too long. The fully qualified file na
me must be less than 260 characters, and the directory name must be less than 248 characters."

before even getting to squirrel.  When I did "nuget pack" I got this:

C:\hello\staging>nuget pack Package.nuspec
Attempting to build package from 'Package.nuspec'.
Successfully created package 'C:\hello\staging\HelloPackage.1.0.0.nupkg'.
The specified path, file name, or both are too long. The fully qualified file na
me must be less than 260 characters, and the directory name must be less than 24
8 characters.

C:\hello\staging>

This is a simple hello world electron app.  I see no long path names! Any Clues?

**Comment by BarryThePenguin** [comment]
@danceswithdolphin if it's an electron app, are you using electron-packager or electron-builder? Sounds like you've got your node_modules involved somehow

**Comment by danceswithdolphin** [comment]
Thanks for the clue, electron-packager works well.

**Comment by danceswithdolphin** [comment]
@BarryThePenguin Thanks electron-packager works well.

**Comment by nathansobo** [comment]
:+1:

**Comment by gaelicgod** [comment]
I had this same problem, turns out on windows it was the unit test fixtures path was too long. It would be assume if it vomited out the path as to where it's choking :|

**Comment by Thieum** [comment]
LongPath should now be supported by default on .NET Framework 4.6.2+.
Not sure what would be the best course of action for older frameworks / OS:
- catch the LongPathException?
- check the path beforehand, and see if we can manage it with the current Framework / OS?

**Comment by shiftkey** [comment]
Long path support in Windows is supported by .NET 4.6.2+ but I don't believe it's enabled by default based on [this post](https://blogs.msdn.microsoft.com/jeremykuhne/2016/07/30/net-4-6-2-and-long-paths-on-windows-10/)).

From memory you need a specific Windows 10 kernel, and if you go and enable that and can live a happy life, all the better.

For those not able to do that, we need to entertain alternatives. `PathTooLongException` is raised by the .NET Framework, and not by Squirrel. As a "simplest thing that could possibly work" we could catch and rethrow a better exception with the file path included to help add context.

I don't think we can fix this in Squirrel, so I'd like to hear about interest in providing better error messaging here (this has mostly been quiet since 2015, so I'm not sure of the overall value).

**Comment by aelialper** [comment]
Catching and throwing a better exception would definitely be a very worthwhile improvement!

It's suddenly a big issue for me, as I can't update my node modules any longer and it's taking forever to find the culprit.
