### ISSUE TITLE
Downloaded Squirrel installer fails with max UAC protection

### ISSUE THREAD

**Issue by JohnThomson** [Squirrel/Squirrel.Windows#313]
We're still analyzing this one, but Chrome (at least, probably other browsers too) mark downloaded EXEs like Squirrel installers as suspicious. Windows Explorer/Properties on the file (General tab) shows a Security message at the bottom ("This file came from another computer and might be blocked to help protect this computer") and an Unblock button.

In some system states, the installer works fine without clicking Unblock. In others, possibly when the highest level of UAC safety is set, but there may be another factor, unless the Unblock button is clicked, running the installer fails. On some systems it fails without any message, in other cases it reports a crash and the log shows that the RELEASES file was not found in the expected place. A tentative hypothesis is that the system is in a state where a 'blocked' program can run but can't do whatever produces the unpacked files ready to be installed. Maybe can't write files at all? Surprisingly we don't get an error message when failing to write them, only when a later step finds they aren't there.

It probably isn't possible to just defeat this behavior, but it would be nice to give a helpful message, or even initiate a security elevation that would permit a successful install.

Details of what we've observed with our particular installer are at https://jira.sil.org/browse/BL-1247.

**Comment by paulcbetts** [comment]
Are you signing your installer? What you're describing isn't UAC, it's SmartScreen. There's nothing you can do about it at first, it's a reputation-based system; you just have to wait until enough people download the app

**Comment by paulcbetts** [comment]
Having a signed installer and app will greatly reduce the amount of time it takes for your app to be trusted

**Comment by JohnThomson** [comment]
Yes, we're signing it. There may be nothing we can do that will make our app be automatically trusted, but surely something could be done so that the user gets a helpful message saying the install has been blocked and what he can do about it if he does trust it.

**Comment by paulcbetts** [comment]
> Details of what we've observed with our particular installer are at https://jira.sil.org/browse/BL-1247.

This is behind a login screen

**Comment by paulcbetts** [comment]
>  On some systems it fails without any message, in other cases it reports a crash and the log shows that the RELEASES file was not found in the expected place. 

Can you gist a log of when this "Blocked" scenario happens? I don't think this is Generally A Thing in Windows, but you might have other problems (3rd party AV?)

**Comment by hatton** [comment]
What's going on isn't SmartScreen. I'm not totally clear, but it looks like it comes from something called the [Attachment Manager](https://support.microsoft.com/en-us/kb/883260) in Windows.

The Attachment Manager is included in Microsoft Windows to help protect your computer from unsafe attachments that you might receive with an e-mail message and from unsafe files that you might save from the Internet. 

> If the Attachment Manager identifies an attachment that might be unsafe, the Attachment Manager prevents you from opening the file, or it warns you before you open the file. 

Just what makes it trigger isn't clear yet. The article above discusses various registry settings that control the decision to mark a file. Here's a [discussion of how NTFS stores the blocking information](http://superuser.com/questions/38476/this-file-came-from-another-computer-how-can-i-unblock-all-the-files-in-a).

Here's [gist of the squirrel log](https://gist.github.com/hatton/5a60d1cc857a804485ef) we got from a user, the one who installed fine after we asked her to unblock the installer.

I think we need to figure out how to reproduce this on our end before we can expect to do anything with Squirrel. This [stackoverflow](http://stackoverflow.com/questions/135600/reproducing-the-blocked-exe-unblock-option-in-file-properties-in-windows-2003) gives an idea of how to add the blocking info to the alternative stream.

**Comment by hatton** [comment]
Using the method described [here](http://stackoverflow.com/questions/135600/reproducing-the-blocked-exe-unblock-option-in-file-properties-in-windows-2003), I got the installer to display the Security Warning in the Properties Dialog:

![image](https://cloud.githubusercontent.com/assets/8448/7327259/0277ae78-ea89-11e4-8479-cb46ea51dff8.png)

However the installer still works fine.  Note that the notice says it *might* be blocked. Sigh.

**Comment by hatton** [comment]
The log entry
> Could not find a part of the path 'C:\Users\john\AppData\Local\BloomSHRP\packages\RELEASES'.

Isn't actually a problem. The log shows that squirrel carries on.

**Comment by ricardopolo** [comment]
I want to add that if you sign your exe with a Code Signing with EV, it will automatically bypass the SmartScreen filter even if the file has not enough reputation

**Comment by hatton** [comment]
New [log ](https://gist.github.com/hatton/c110086a52e0a77061ce0874a8168cce) with this installation failure. 

```
2016-11-20 14:48:08> IEnableLogger: Failed to install package to app dir: System.AggregateException: One or more errors occurred. ---> System.IO.IOException: Access to the path 'BloomBrowserUI' is denied.
   at System.IO.DirectoryInfo.MoveTo(String destDirName)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassbc.<>c__DisplayClassc0.<>c__DisplayClassc2.<installPackageToAppDir>b__ba(DirectoryInfo subdir)

```
And [one from a different user](https://gist.github.com/hatton/9eacc5e50ac57cb618ae12f0952473b3).

2016-11-20 15:17:35> IEnableLogger: Failed to install package to app dir: System.AggregateException: 

```
One or more errors occurred. ---> System.IO.IOException: Access to the path 'factoryCollections' is denied.
   at System.IO.DirectoryInfo.MoveTo(String destDirName)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClassbc.<>c__DisplayClassc0.<>c__DisplayClassc2.<installPackageToAppDir>b__ba(DirectoryInfo subdir)
   at Squirrel.Utility.<>c__DisplayClass18`1.<>c__DisplayClass1a.<ForEachAsync>b__17()
```

As before, we do not have access to the machines, but reports are that five machines in a row failed this way, and the tech person on site says that disabling (UAC) User Access Control  fixes it.
