### ISSUE TITLE
Working update example.

### ISSUE THREAD

**Issue by artos027** [Squirrel/Squirrel.Windows#324]
Please, give me a working example of update.
I'm using updating code from this video https://www.youtube.com/watch?v=RggPWlfpT9I
but this code don't work.

**Comment by Vilmir** [comment]
Same problem for me after having watched the .Net 2015 conf.
It seems that Squirrel 0.9.5 assembly does not take into account the release directory given in UpdateManager.

Here is my update code:
```c#
using (var mgr =  new UpdateManager(@"C:\Users\11mvazquez\Documents\Visual Studio 2013\Projects\SquirrelExperiment\Releases", "SquirrelExperiment",               FrameworkVersion.Net45))
{
    await mgr.UpdateApp();
}
```
Product never gets updated, despites newer releases deployed to the folder.

Error from the logs:
2015-05-08 11:48:21> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\11mvazquez\AppData\Local\SquirrelExperiment\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__28.MoveNext()

**Comment by paulcbetts** [comment]
> C:\Users\11mvazquez\AppData\Local\SquirrelExperiment\packages\RELEASES

Does that folder exist?

**Comment by artos027** [comment]
Thanks, but i understood how to work with update install unistall and so on, all works good.
Now i don't know is it possible to create shortcut with another name?
After unistall in folder Update.exe remains...is it possible to clean everything after unistall???)

**Comment by paulcbetts** [comment]
> Now i don't know is it possible to create shortcut with another name?

Check out the Squirrel hooks docs

> After unistall in folder Update.exe remains...is it possible to clean everything after unistall???)

No

**Comment by Vilmir** [comment]
@paulcbetts at this place:
C:\Users\11mvazquez\AppData\Local\SquirrelExperiment\packages\RELEASES

There is a file containing the release information. But that is not a folder.
