### ISSUE TITLE
Update not running after install, works from visual studio

### ISSUE THREAD

**Issue by amweiss** [Squirrel/Squirrel.Windows#329]
For the past couple months, I've been having no issues with Squirrel.Windows, but recently (can't say for sure when it started, but I'm on 0.9.4 now), the application no longer updates after being installed.

When running from Visual Studio (in Release or Debug) it works fine.  The code in use is: https://github.com/amweiss/vigilant-cupcake/blob/master/VigilantCupcake/MainForm.cs#L507 which is nearly a copy/paste from the example posted here.  Any ideas what could cause the difference?  I'm trying to find a good way to attach a debugger and get symbols working post-install.

Fiddler shows the request going out to the releases URL, and no exceptions are bubbling up.

**Comment by paulcbetts** [comment]
You can just open a copy of Visual Studio and go "Attach to process", or go into Task manager's processes tab, right click => Create Dump File

**Comment by amweiss** [comment]
Found something, seems like a version mismatch somewhere for NuGet.Core.  I'll see if I can track it down 
![image](https://cloud.githubusercontent.com/assets/30146/7494212/5ed61b42-f3d4-11e4-998a-5417ba1aae48.png)

**Comment by amweiss** [comment]
Ah, appears related to https://github.com/Squirrel/Squirrel.Windows/pull/330.
I agree with @ricardopolo if we can get a nuget version of Squirrel to include that, it should fix it I think.

**Comment by paulcbetts** [comment]
This is fixed in 0.9.5

**Comment by amweiss** [comment]
Not quite, new one popped up:
```
System.IO.FileLoadException was caught
  HResult=-2146234304
  Message=Could not load file or assembly 'Mono.Cecil, Version=0.9.5.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
  Source=Squirrel
  FileName=Mono.Cecil, Version=0.9.5.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756
  FusionLog==== Pre-bind state information ===
LOG: DisplayName = Mono.Cecil, Version=0.9.5.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756
 (Fully-specified)
LOG: Appbase = file:///C:/Users/aweiss/AppData/Local/vigilantcupcake/app-1.0.5604.25563/
LOG: Initial PrivatePath = NULL
Calling assembly : Squirrel, Version=0.9.5.0, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in default load context.
LOG: No application configuration file found.
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: Mono.Cecil, Version=0.9.5.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756
LOG: Attempting download of new URL file:///C:/Users/aweiss/AppData/Local/vigilantcupcake/app-1.0.5604.25563/Mono.Cecil.DLL.
WRN: Comparing the assembly name resulted in the mismatch: Build Number
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.

  StackTrace:
       at Squirrel.SquirrelAwareExecutableDetector.GetAssemblySquirrelAwareVersion(String executable)
       at Squirrel.SquirrelAwareExecutableDetector.<>c__DisplayClass8.<GetPESquirrelAwareVersion>b__7()
       at Squirrel.Utility.Retry[T](Func`1 block, Int32 retries)
       at Squirrel.SquirrelAwareExecutableDetector.GetPESquirrelAwareVersion(String executable)
       at Squirrel.SquirrelAwareExecutableDetector.<>c__DisplayClass5.<GetAllSquirrelAwareApps>b__2(String x)
       at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
       at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
       at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
       at Squirrel.SquirrelAwareExecutableDetector.GetAllSquirrelAwareApps(String directory, Int32 minimumVersion)
       at Squirrel.UpdateManager.ApplyReleasesImpl.<invokePostInstall>d__bb.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Squirrel.Utility.<LogIfThrows>d__51.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
       at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__5e.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Squirrel.UpdateManager.<ApplyReleases>d__a.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at VigilantCupcake.MainForm.<<updateCheckTimer_Tick>b__33>d__3d.MoveNext()
  InnerException: 
```

**Comment by paulcbetts** [comment]
Oh my god fuck strong naming so hard

**Comment by stirno** [comment]
next project: nuget that refuses packages with strong-named dlls.

**Comment by paulcbetts** [comment]
Alright, give 0.9.5.1 a try

**Comment by amweiss** [comment]
Looks like the same issue still, I'll see if I can find anything else.

```
System.IO.FileLoadException was caught
  HResult=-2146234304
  Message=Could not load file or assembly 'Mono.Cecil, Version=0.9.5.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
  Source=Squirrel
  FileName=Mono.Cecil, Version=0.9.5.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756
  FusionLog==== Pre-bind state information ===
LOG: DisplayName = Mono.Cecil, Version=0.9.5.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756
 (Fully-specified)
LOG: Appbase = file:///C:/Users/aweiss/AppData/Local/vigilantcupcake/app-1.0.5604.26568/
LOG: Initial PrivatePath = NULL
Calling assembly : Squirrel, Version=0.9.5.1, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in default load context.
LOG: No application configuration file found.
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: Mono.Cecil, Version=0.9.5.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756
LOG: Attempting download of new URL file:///C:/Users/aweiss/AppData/Local/vigilantcupcake/app-1.0.5604.26568/Mono.Cecil.DLL.
WRN: Comparing the assembly name resulted in the mismatch: Build Number
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.

  StackTrace:
       at Squirrel.SquirrelAwareExecutableDetector.GetAssemblySquirrelAwareVersion(String executable)
       at Squirrel.SquirrelAwareExecutableDetector.<>c__DisplayClass8.<GetPESquirrelAwareVersion>b__7()
       at Squirrel.Utility.Retry[T](Func`1 block, Int32 retries)
       at Squirrel.SquirrelAwareExecutableDetector.GetPESquirrelAwareVersion(String executable)
       at Squirrel.SquirrelAwareExecutableDetector.<>c__DisplayClass5.<GetAllSquirrelAwareApps>b__2(String x)
       at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
       at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
       at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
       at Squirrel.SquirrelAwareExecutableDetector.GetAllSquirrelAwareApps(String directory, Int32 minimumVersion)
       at Squirrel.UpdateManager.ApplyReleasesImpl.<invokePostInstall>d__bb.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Squirrel.Utility.<LogIfThrows>d__51.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
       at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__5e.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Squirrel.UpdateManager.<ApplyReleases>d__a.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at VigilantCupcake.MainForm.<<updateCheckTimer_Tick>b__33>d__3d.MoveNext()
  InnerException: 
```
