### ISSUE TITLE
Releasify looking in the wrong place?

### ISSUE THREAD

**Issue by stirno** [Squirrel/Squirrel.Windows#332]
Upgraded from 0.9.2.1 -> 0.9.5.1 hoping to fix the nuget reference issue thats been breaking our updates.. and now I'm getting this during the releasify call on CI:

```
[21:20:58][Step 4/7] System.AggregateException: One or more errors occurred. ---> System.Exception: Failed to sign, command invoked was: 'C:\TeamCity\buildAgent\work\dbfc57ee86d8785c\packages\squirrel.windows.0.9.5.1\tools\signtool.exe sign /a /f <redacted> /p <redacted> C:\Windows\system32\config\systemprofile\AppData\Local\SquirrelTemp\tempa\lib\net45\Scrawl.exe
[21:20:58][Step 4/7]    at Squirrel.Update.Program.<signPEFile>d__93.MoveNext()
[21:20:58][Step 4/7] --- End of stack trace from previous location where exception was thrown ---
[21:20:58][Step 4/7]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[21:20:58][Step 4/7]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[21:20:58][Step 4/7]    at Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext()
[21:20:58][Step 4/7]    --- End of inner exception stack trace ---
[21:20:58][Step 4/7]    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
[21:20:58][Step 4/7]    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
[21:20:58][Step 4/7]    at Squirrel.Update.Program.<>c__DisplayClass71.<Releasify>b__63(String pkgPath)
[21:20:58][Step 4/7]    at Squirrel.ReleasePackage.CreateReleasePackage(String outputFile, String packagesRootDir, Func`2 releaseNotesProcessor, Action`1 contentsPostProcessHook)
[21:20:58][Step 4/7]    at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon)
[21:20:58][Step 4/7]    at Squirrel.Update.Program.executeCommandLine(String[] args)
[21:20:58][Step 4/7]    at Squirrel.Update.Program.main(String[] args)
[21:20:58][Step 4/7]    at Squirrel.Update.Program.Main(String[] args)
[21:20:58][Step 4/7] ---> (Inner Exception #0) System.Exception: Failed to sign, command invoked was: 'C:\TeamCity\buildAgent\work\dbfc57ee86d8785c\packages\squirrel.windows.0.9.5.1\tools\signtool.exe sign /a /f <redacted> /p <redacted> C:\Windows\system32\config\systemprofile\AppData\Local\SquirrelTemp\tempa\lib\net45\Scrawl.exe'
[21:20:58][Step 4/7]    at Squirrel.Update.Program.<signPEFile>d__93.MoveNext()
[21:20:58][Step 4/7] --- End of stack trace from previous location where exception was thrown ---
[21:20:58][Step 4/7]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[21:20:58][Step 4/7]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[21:20:58][Step 4/7]    at Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext()<---
[21:20:58][Step 4/7] 
```

Releasify just stops there so no new Setup.exe is generated and RELEASES isnt updated. I do get the .nupkg though.

**Comment by paulcbetts** [comment]
Failing to sign is usually because the binary is being signed twice

**Comment by stirno** [comment]
This is more than failing to sign. We've always had it 'fail' in the log even though it did actually sign properly. In those cases it still updated RELEASES and generated an installer. Neither of those things happen now.

Its also looking in a path that doesn't exist on our CI machine.

```
C:\Windows\system32\config\systemprofile\AppData\Local\SquirrelTemp\tempa\lib\net45
```

**Comment by stirno** [comment]
Looking back through our CI build logs, I see that it was somewhat indeterminately failing to sign but never failed to do the other things. The releasify call is literally the only thing we have that interacts with our cert/signing at all for Windows builds.

**Comment by paulcbetts** [comment]
@stirno Does this work on your machine?

**Comment by stirno** [comment]
Yes. On my dev box, the following command results in generation/updating RELEASES and a signed Setup.exe.

```
T:\Projects\fluentCODE\scrawl>packages\squirrel.windows.0.9.5.1\tools\Squirrel.exe -releasify Scrawl.App.Windows\Scrawl.0.1.460.nupkg -releaseDir sq\ -n "/a /f <redacted> /p <redacted>"
```

![screen shot 2015-05-08 at 4 09 50 pm](https://cloud.githubusercontent.com/assets/666175/7545690/9f7e334a-f59c-11e4-8038-8556029a993a.png)

**Comment by stirno** [comment]
Also, I ran a CI build and continually refreshed `C:\Windows\system32\config\systemprofile\AppData\Local` - no SquirrelTemp folder was ever created.

**Comment by stirno** [comment]
Anything I can look at or logs to try and get data from to help with this? We're basically stuck right now without being able to push updates to our users.

**Comment by paulcbetts** [comment]
> Anything I can look at or logs to try and get data from to help with this?

Yeah, look in the same directory as Squirrel.exe for a log file

**Comment by stirno** [comment]
Ok, here we go:

```
2015-05-08 20:47:45> Program: Starting Squirrel Updater: -releasify C:\Scrawl\artifacts\windows\Scrawl.0.1.456-alpha1.nupkg -releaseDir C:\Scrawl\channels\ci -setupIcon C:\Scrawl\scrawl.ico -n /a /f <redacted> /p <redacted>
2015-05-08 20:47:45> Program: Bootstrapper EXE found at:C:\TeamCity\buildAgent\work\dbfc57ee86d8785c\packages\squirrel.windows.0.9.5.1\tools\Setup.exe
2015-05-08 20:47:45> Program: Creating release package: C:\Scrawl\channels\ci\Scrawl.0.1.450-alpha1.nupkg
2015-05-08 20:47:46> ReleasePackage: Creating release package: C:\Scrawl\channels\ci\Scrawl.0.1.450-alpha1.nupkg => C:\Scrawl\channels\ci\Scrawl-0.1.450-alpha1-full.nupkg
2015-05-08 20:47:49> ReleasePackage: Extracting dependent packages: []
2015-05-08 20:47:49> ReleasePackage: Removing unnecessary data
2015-05-08 20:47:49> ReleasePackage: No release notes found in C:\Windows\system32\config\systemprofile\AppData\Local\SquirrelTemp\tempa\Scrawl.nuspec
2015-05-08 20:47:52> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.Exception: Failed to sign, command invoked was: 'C:\TeamCity\buildAgent\work\dbfc57ee86d8785c\packages\squirrel.windows.0.9.5.1\tools\signtool.exe sign /a /f <redacted> /p <redacted> C:\Windows\system32\config\systemprofile\AppData\Local\SquirrelTemp\tempa\lib\net45\Scrawl.exe'
   at Squirrel.Update.Program.<signPEFile>d__93.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Squirrel.Update.Program.<>c__DisplayClass71.<Releasify>b__63(String pkgPath)
   at Squirrel.ReleasePackage.CreateReleasePackage(String outputFile, String packagesRootDir, Func`2 releaseNotesProcessor, Action`1 contentsPostProcessHook)
   at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.Exception: Failed to sign, command invoked was: 'C:\TeamCity\buildAgent\work\dbfc57ee86d8785c\packages\squirrel.windows.0.9.5.1\tools\signtool.exe sign /a /f <redacted> /p <redacted> C:\Windows\system32\config\systemprofile\AppData\Local\SquirrelTemp\tempa\lib\net45\Scrawl.exe'
   at Squirrel.Update.Program.<signPEFile>d__93.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext()<---

---> (Inner Exception #1) System.Exception: Failed to sign, command invoked was: 'C:\TeamCity\buildAgent\work\dbfc57ee86d8785c\packages\squirrel.windows.0.9.5.1\tools\signtool.exe sign /a /f <redacted> /p <redacted> C:\Windows\system32\config\systemprofile\AppData\Local\SquirrelTemp\tempa\lib\net45\Squirrel.exe'
   at Squirrel.Update.Program.<signPEFile>d__93.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext()<---
```

**Comment by paulcbetts** [comment]
Gotta figure out why signing is failing, it's definitely a fatal error

**Comment by stirno** [comment]
As mentioned above.. the folder it appears to be looking for Scrawl.exe in.. doesn't exist. There is at no point during a build a `C:\Windows\system32\config\systemprofile\AppData\Local\SquirrelTemp`

**Comment by paulcbetts** [comment]
Why are your environment variables so weird and fucked up

**Comment by stirno** [comment]
its a default 2012R2 VM on Azure running TeamCity w/single agent. Same config that we've used for a few months.

**Comment by paulcbetts** [comment]
I'd build Squirrel.exe and then invoke it and step through on your CI machine with the debugger

**Comment by stirno** [comment]
So the actual directory the files are getting written to by the earlier steps is:

```
C:\Windows\SysWOW64\config\systemprofile\AppData\Local\SquirrelTemp
```

**Comment by paulcbetts** [comment]
lol perfect. Because they put `%LocalAppData%` under `C:\Windows\System32`, it's subject to `WOW64 File System Redirection`. Set the SQUIRREL_TEMP environment variable to somewhere not under a redirected folder

**Comment by stirno** [comment]
Indeed. that appears to have done the trick. Thanks for the help @paulcbetts!

**Comment by aclave1** [comment]
@stirno I know this is an old issue, but can you tell me how you set the environment variables? I'm running into the same issue. I used these commands:

```
[Environment]::SetEnvironmentVariable("SQUIRREL_TEMP ", "D:\Temp\")
.\Squirrel\nuget.exe pack Squirrel.nuspec -Prop Platform=x86
.\Squirrel\Squirrel --releasify $packageName -r $releasesDirectory --no-msi --icon $icon --setupIcon=$icon -n "/a /f <redacted> /p <redacted>"
```

and squirrel doesn't seem to be picking up the environment variables and it's still looking in ```C:\Windows\system32\config\systemprofile\AppData```

**Comment by aclave1** [comment]
I've figured it out. I needed to use ```$env:SQUIRREL_TEMP = "D:\Temp\" instead of ```[Environment]::SetEnvironmentVariable("SQUIRREL_TEMP ", "D:\Temp\") ```
 ```
