### ISSUE TITLE
Squirrel doesn't want to download release notes from the remote path (https)

### ISSUE THREAD

**Issue by danielkornev** [Squirrel/Squirrel.Windows#381]
both delta and full .nupkg files are available at the given path (see below). Squirrel is able to download release notes when checking against local folder just fine. This problem happens only when URL is remote.

Here's an excerpt from our app's log:

INFO  2015-07-10 15:26:32Z Trying to obtain release notes for build "2.0.5669.27401" from "https://zetuniversealpha.blob.core.windows.net/20150622-1345/"
ERROR  2015-07-10 15:26:32Z Error occured while trying to obtain release notes
DEBUG  2015-07-10 15:26:32Z EXCEPTION: System.NotSupportedException: The given path's format is not supported.
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at NuGet.ZipPackage.<>c__DisplayClass2.<.ctor>b__0()
   at NuGet.ZipPackage.EnsureManifest()
   at Squirrel.ReleaseEntry.GetReleaseNotes(String packageDirectory)
   at ZU.WPF.Frame.<CheckForUpdates>d__f6.MoveNext()

**Comment by danielkornev** [comment]
Any thoughts, @paulcbetts?

**Comment by paulcbetts** [comment]
Weird!

**Comment by paulcbetts** [comment]
Probably need to build a debug version and debug it

**Comment by scionwest** [comment]
Was this ever figured out? I'm running into the same issue now. I deploy it to a network fileshare at my enterprise and when i install it, squirrel fails because it can't find the readme.

**Comment by paulcbetts** [comment]
Squirrel never fails because of the release notes (if it fails, it just keeps going), you've got something else going on

**Comment by scionwest** [comment]
Yeah, turns out I was running the run release. My --releasesDir is being ignored or failing, causing nothing to actually output to the specifed release folder (v5.0.2512.52125-QA). The nuget package is generated in the folder where the nuspec is at, but the releases folder is empty. Works fine if I don't use --releasesDir, which i need to use so I can generate different installers per environment.

**Comment by tbrown9164** [comment]
I see however with Charles Proxy,  that squirrel indicates an error as indicated above and then downloads the package a second time,  essentially doubling the download time.   For some reason,  in my case, it doesn't mind the second time and then wraps up the installation.    True,  it doesn't fail but it does add significantly to the download time.
