### ISSUE TITLE
New install does not add the shortcut to the Start Menu in Windows 10

### ISSUE THREAD

**Issue by christianrondeau** [Squirrel/Squirrel.Windows#411]
It works on the Desktop, but it's not created in `C:\Users\USERNAME\AppData\Roaming\Microsoft\Windows\Start Menu\Programs` and do not show up in the Start Menu in Windows 10.

The line is very simple: `_updateManager.CreateShortcutsForExecutable(executableFilename, ShortcutLocation.StartMenu, updateOnly);`

The same for Desktop works, and the `executableFilename` is correct. For some reason I can't debug Squirrel, so at least here's an issue.

**Comment by paulcbetts** [comment]
This is working for us, what does SquirrelSetup.log say?

**Comment by christianrondeau** [comment]
`SquirrelSetup.log` says:

```
2015-08-16 13:08:30> Program: Starting Squirrel Updater: --install .
2015-08-16 13:08:30> Program: Starting install, writing to C:\Users\christian\AppData\Local\SquirrelTemp
2015-08-16 13:08:30> Program: About to install to: C:\Users\christian\AppData\Local\GoToWindow
2015-08-16 13:08:30> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\christian\AppData\Local\GoToWindow\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__3a.MoveNext()
2015-08-16 13:08:30> CheckForUpdateImpl: Reading RELEASES file from C:\Users\christian\AppData\Local\SquirrelTemp
2015-08-16 13:08:30> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2015-08-16 13:08:30> ApplyReleasesImpl: Writing files to app directory: C:\Users\christian\AppData\Local\GoToWindow\app-0.4.1
2015-08-16 13:08:31> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\christian\AppData\Local\GoToWindow\app-0.4.1\GoToWindow.exe]
2015-08-16 13:08:31> ApplyReleasesImpl: Starting fixPinnedExecutables
2015-08-16 13:08:31> ApplyReleasesImpl: fixPinnedExecutables: oldAppDirectories is empty, this is pointless
2015-08-16 13:08:31> ApplyReleasesImpl: cleanDeadVersions: for version 0.4.1
2015-08-16 13:08:31> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.4.1
```

That's my current log, from my last clean + reinstall.

I hope to be able to spend more time finding what the issue what, and hopefully it's machine-specific. Knowing that you did test with Windows 10 and didn't have issues, let me take the time to diagnose the issue before taking any action on that (unless you do have multiple reports of that problem)

**Comment by enzanki-ars** [comment]
This bug seems to be more of an issue with Windows 10 rather than Squirrel.  See https://answers.microsoft.com/en-us/windows/forum/apps_windows_10-winapps/windows-10-all-apps-does-not-display-all-apps/87d57544-a4d2-432a-9da8-461a2cb9a917

**Comment by BlythMeister** [comment]
This is still an issue and the it being windows 10 relates to upgrades from 8.1 to 10.

This is a fresh install of 10 installing 2 apps which use squirrel. 
One is my own app, and the other is WhatsApp. 
Neither can create start menu items.
My app does however create the desktop shortcut.

**Comment by simonwidjaja** [comment]
I am experiencing the exact same problem. (Desktop Link is added, Start Menu Link is NOT added).
Is this still the case in 2021 or am I missing something? (already spent 1 entire day with this...)

**Comment by BlythMeister** [comment]
My issue was related to group policy blocking parts of the install (and subsequent app starts)

It might be worth checking event viewer for any information.
