### ISSUE TITLE
Error of dependencies

### ISSUE THREAD

**Issue by ricardopolo** [Squirrel/Squirrel.Windows#437]
Hi @paulcbetts.

Have been some updates that could broke the dependencies versions while updating?

When the app is updating I get fatal exception whit this info

````
System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
File name: 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter..ctor()
   at System.Net.Http.Formatting.JsonMediaTypeFormatter..ctor()
   at System.Net.Http.Formatting.MediaTypeFormatterCollection.CreateDefaultFormatters()
   at System.Net.Http.HttpContentExtensions.get_DefaultMediaTypeFormatterCollection()
   at System.Net.Http.HttpContentExtensions.ReadAsAsync[T](HttpContent content)
   at Tulpep.Signtul.UpdateOutlookSignatures.ConfigureSignature.<StartOutlookConfiguration>d__3.MoveNext() in c:\projects\signtul\Tulpep.Signtul.UpdateOutlookSignatures\ConfigureSignature.cs:line 51

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

2015-09-10 11:53:26.9358|DEBUG|Tulpep.Signtul.UpdateOutlookSignatures.App+<StartUpdateProcess>d__7|Fail update Could not load file or assembly 'NuGet.Squirrel, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
2015-09-10 11:53:26.9983|FATAL|Tulpep.Signtul.UpdateOutlookSignatures.App|Signtul Error
System.UnhandledExceptionEventArgs
````

I think is something related to Squirrel because of the line
````
Could not load file or assembly 'NuGet.Squirrel, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null' 
````

Any idea?

Thanks

**Comment by Thieum** [comment]
:+1:

**Comment by InnovaTex** [comment]
Same problem here, when is 1.03 going to be released?

**Comment by jmelosegui** [comment]
:+1:

**Comment by paulcbetts** [comment]
Hey guys, 1.0.3 is up on NuGet which should solve this. Reopen if it doesn't!
