### ISSUE TITLE
Failed to invoke post-install

### ISSUE THREAD

**Issue by bruce** [Squirrel/Squirrel.Windows#456]
I'm encountering the following running `Setup.exe` created by `Squirrel.exe --releasify`.

```
2015-10-04 20:25:49> Program: Starting Squirrel Updater: --install .
2015-10-04 20:25:49> Program: Starting install, writing to C:\Users\bruce\AppData\Local\SquirrelTemp
2015-10-04 20:25:49> Program: About to install to: C:\Users\bruce\AppData\Local\OurApp
2015-10-04 20:25:49> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\bruce\AppData\Local\OurApp\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__3c.MoveNext()
2015-10-04 20:25:49> CheckForUpdateImpl: Reading RELEASES file from C:\Users\bruce\AppData\Local\SquirrelTemp
2015-10-04 20:25:49> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2015-10-04 20:25:49> ApplyReleasesImpl: Writing files to app directory: C:\Users\bruce\AppData\Local\OurApp\app-1.5.0
2015-10-04 20:25:50> ApplyReleasesImpl: Moving file C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\lib\net45\OurApp.exe to C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\OurApp.exe
2015-10-04 20:25:50> ApplyReleasesImpl: Moving file C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\lib\net45\content_shell.pak to C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\content_shell.pak
2015-10-04 20:25:50> ApplyReleasesImpl: Moving file C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\lib\net45\content_resources_200_percent.pak to C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\content_resources_200_percent.pak
2015-10-04 20:25:50> ApplyReleasesImpl: Moving file C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\lib\net45\d3dcompiler_47.dll to C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\d3dcompiler_47.dll
2015-10-04 20:25:50> ApplyReleasesImpl: Moving file C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\lib\net45\ffmpegsumo.dll to C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\ffmpegsumo.dll
2015-10-04 20:25:50> ApplyReleasesImpl: Moving file C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\lib\net45\icudtl.dat to C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\icudtl.dat
2015-10-04 20:25:50> ApplyReleasesImpl: Moving file C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\lib\net45\libEGL.dll to C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\libEGL.dll
2015-10-04 20:25:50> ApplyReleasesImpl: Moving file C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\lib\net45\libGLESv2.dll to C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\libGLESv2.dll
2015-10-04 20:25:50> ApplyReleasesImpl: Moving file C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\lib\net45\msvcp120.dll to C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\msvcp120.dll
2015-10-04 20:25:50> ApplyReleasesImpl: Moving file C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\lib\net45\msvcr120.dll to C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\msvcr120.dll
2015-10-04 20:25:50> ApplyReleasesImpl: Moving file C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\lib\net45\node.dll to C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\node.dll
2015-10-04 20:25:50> ApplyReleasesImpl: Moving file C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\lib\net45\pdf.dll to C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\pdf.dll
2015-10-04 20:25:50> ApplyReleasesImpl: Moving file C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\lib\net45\natives_blob.bin to C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\natives_blob.bin
2015-10-04 20:25:50> ApplyReleasesImpl: Moving file C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\lib\net45\nuget.exe to C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\nuget.exe
2015-10-04 20:25:50> ApplyReleasesImpl: Moving file C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\lib\net45\rcedit.exe to C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\rcedit.exe
2015-10-04 20:25:50> ApplyReleasesImpl: Moving file C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\lib\net45\Setup.exe to C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\Setup.exe
2015-10-04 20:25:50> ApplyReleasesImpl: Moving file C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\lib\net45\snapshot_blob.bin to C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\snapshot_blob.bin
2015-10-04 20:25:50> ApplyReleasesImpl: Moving file C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\lib\net45\Squirrel.exe to C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\Squirrel.exe
2015-10-04 20:25:50> ApplyReleasesImpl: Moving file C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\lib\net45\Squirrel.Windows-1.0.1.zip to C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\Squirrel.Windows-1.0.1.zip
2015-10-04 20:25:50> ApplyReleasesImpl: Moving file C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\lib\net45\signtool.exe to C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\signtool.exe
2015-10-04 20:25:50> ApplyReleasesImpl: Moving file C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\lib\net45\Squirrel.com to C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\Squirrel.com
2015-10-04 20:25:50> ApplyReleasesImpl: Moving file C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\lib\net45\SyncReleases.exe to C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\SyncReleases.exe
2015-10-04 20:25:50> ApplyReleasesImpl: Moving file C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\lib\net45\Squirrel.Windows-1.0.2.zip to C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\Squirrel.Windows-1.0.2.zip
2015-10-04 20:25:50> ApplyReleasesImpl: Moving file C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\lib\net45\ui_resources_200_percent.pak to C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\ui_resources_200_percent.pak
2015-10-04 20:25:50> ApplyReleasesImpl: Moving file C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\lib\net45\xinput1_3.dll to C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\xinput1_3.dll
2015-10-04 20:25:50> ApplyReleasesImpl: Moving file C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\lib\net45\vccorlib120.dll to C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\vccorlib120.dll
2015-10-04 20:25:51> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\OurApp.exe,C:\Users\bruce\AppData\Local\OurApp\app-1.5.0\Setup.exe]
2015-10-04 20:25:53> IEnableLogger: Failed to invoke post-install: System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<invokePostInstall>b__cd(ProcessStartInfo info)
   at Squirrel.EnumerableExtensions.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<invokePostInstall>d__d9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__51.MoveNext()
2015-10-04 20:25:53> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.ComponentModel.Win32Exception: The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<invokePostInstall>b__cd(ProcessStartInfo info)
   at Squirrel.EnumerableExtensions.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<invokePostInstall>d__d9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__74.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<FullInstall>d__f.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Install>d__37.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<invokePostInstall>b__cd(ProcessStartInfo info)
   at Squirrel.EnumerableExtensions.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<invokePostInstall>d__d9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__74.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<FullInstall>d__f.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Install>d__37.MoveNext()<---

ompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<Install>d__37.MoveNext()<---
```

I believe that I've implemented the necessary Squirrel hooks in our Electron application; eg, the app successfully invokes `\path\to\Update.exe --createShortcut OurApp.exe` and exits; this appears to be something that occurs afterwards.

**Comment by Thieum** [comment]
@bruce are you still experiencing this issue with the latest version of Squirrel?
