### ISSUE TITLE
System.ArgumentNullException: Value cannot be null.

### ISSUE THREAD

**Issue by sickboy** [Squirrel/Squirrel.Windows#457]
~~~
2015-10-06 11:49:26> Program: Starting Squirrel Updater: --processStart sync.exe
2015-10-06 11:49:26> Unhandled exception: System.ArgumentNullException: Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2)
   at Squirrel.Update.Program.ProcessStart(String exeName, String arguments, Boolean shouldWait)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
~~~

**Comment by Thieum** [comment]
@patroza is this issue still happening in the most recent version if Squirrel?
