### ISSUE TITLE
FileNotFoundException when initializing UpdateManager()

### ISSUE THREAD

**Issue by Kordonme** [Squirrel/Squirrel.Windows#475]
I've been having a hard time setting up Squirrel, to be completely honest.

I'm getting a FileNotFoundException whenever I run UpdateManager:

```c#
private void App_OnStartup(object sender, StartupEventArgs e)
{
#if !DEBUG
    var updateManager = new UpdateManager(@"http://yourserver:8080/");
    using (updateManager)
    {
    }
#endif
}
```

If I simply remove these lines, the application installs and starts just fine.

**Comment by paulcbetts** [comment]
Maybe mention which file isn't found?

**Comment by Kordonme** [comment]
How could I know?

```
Exception Info: System.IO.FileNotFoundException
Stack:
   at Fiesta.SitemapManager.App.App_OnStartup(System.Object, System.Windows.StartupEventArgs)
   at System.Windows.Application.OnStartup(System.Windows.StartupEventArgs)
   at System.Windows.Application.<_ctor>b__0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at Fiesta.SitemapManager.App.Main()
```

**Comment by paulcbetts** [comment]
Hm, I don't see Squirrel anywhere in that stack though...

**Comment by Kordonme** [comment]
Well, I can assure you that the UpdateManager is being init. 

Don't know what to do then, moved the code into a method to show you, that it's actually the UpdateManager code being executed:

```
Exception Info: System.IO.FileNotFoundException
Stack:
   at Fiesta.SitemapManager.App.BootstrapSquirrel()
   at Fiesta.SitemapManager.App.App_OnStartup(System.Object, System.Windows.StartupEventArgs)
```

```c#
private void App_OnStartup(object sender, StartupEventArgs e)
{
    BootstrapSquirrel();
}

private void BootstrapSquirrel()
{
#if !DEBUG
    var updateManager = new UpdateManager(@"http://yourserver:8080/");
    using (updateManager)
    {
    }
#endif
}
```

Is it possible for me to run the UpdateManager when debugger is attached? When running local I get the update.exe not found of course.

http://i.imgur.com/PmmwU5z.png

**Comment by paulcbetts** [comment]
Ah, there's the real error - you can't check for updates when you're running out of your VS folder, you're not actually installed

**Comment by Kordonme** [comment]
Yes, I know that. The stacktrace and FileNotFoundException is being thrown after install. Install runs just fine, but when applications first run throws this error. And when installed with Squirrel, the update.exe is in the folder: http://i.imgur.com/s1LCh2h.png

**Comment by Kordonme** [comment]
OK, so I copied the update.exe file into the ./{project}/bin/ folder. That way I can mimic the installed application behaviour when it's actually running from /{project}/bin/Debug/. My UpdateManager code runs just fine then. I was actually hoping that an exception would be thrown. Oh well. I will debug some more.

**Comment by Kordonme** [comment]
OK, I think I found the issue @paulcbetts. Please let me know if I misunderstood something.


Squirrel.dll and Splat.dll have to be deployed in your package along side the other files:

```
<file src="bin\Release\Squirrel.dll" target="lib\net45" />
<file src="bin\Release\Splat.dll" target="lib\net45" />
```

Now I can get past the UpdateManager. And looking back I'm getting close to that tabeflip as it's pretty clear why it would not work without Squirrel.dll. It was, however, not mentioned in any docs, so I didn't give it much though.
