### ISSUE TITLE
Installer animation runs then nothing happens (for some users)

### ISSUE THREAD

**Issue by marwanhilmi** [Squirrel/Squirrel.Windows#525]
We are generating installers using `grunt-electron-installer` but are having issues with a small percentage of users where the installer essentially does nothing. The short default animation flashes but the application never starts. This has been difficult for us to debug as we cannot identify what is causing this to happen. This tends to happen on Windows 7 systems (and often they are using non-English languages). I've instructed users to manually install .NET 4.5 with no success.

We are signing our code as well. Code used to create installer is straight-forward:
```
'create-windows-installer':
      x64:
        appDirectory: path.join('build',"#{productName}-win32-x64")
        outputDirectory: 'build-win32-installer-x64'
        description: productName
        exe: "#{productName}.exe"
        setupIcon: 'icon.ico'
```

I've pasted logs below. Is there anything additional we can do to debug this? One user reported similar failure with another Squirrel-based installer (but then was able to install a different Squirrel-based application successfully).

```
2015-12-07 10:46:55> Program: Starting Squirrel Updater: --install .
2015-12-07 10:46:55> Program: Starting install, writing to C:\Users\M\AppData\Local\SquirrelTemp
2015-12-07 10:46:55> Program: About to install to: C:\Users\M\AppData\Local\launcher
2015-12-07 10:46:55> Program: Install path C:\Users\M\AppData\Local\launcher already exists, burning it to the ground
2015-12-07 10:46:55> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\M\AppData\Local\launcher\packages\RELEASES'.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
at Squirrel.UpdateManager.CheckForUpdateImpl.d__3f.MoveNext()
2015-12-07 10:46:55> CheckForUpdateImpl: Reading RELEASES file from C:\Users\M\AppData\Local\SquirrelTemp
2015-12-07 10:46:55> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2015-12-07 10:46:56> ApplyReleasesImpl: Writing files to app directory: C:\Users\M\AppData\Local\launcher\app-0.0.7
2015-12-07 10:46:59> ApplyReleasesImpl: Moving file C:\Users\M\AppData\Local\launcher\app-0.0.7\lib\net45\content_resources_200_percent.pak to C:\Users\M\AppData\Local\launcher\app-0.0.7\content_resources_200_percent.pak
2015-12-07 10:46:59> ApplyReleasesImpl: Moving file C:\Users\M\AppData\Local\launcher\app-0.0.7\lib\net45\Launcher.exe to C:\Users\M\AppData\Local\launcher\app-0.0.7\Launcher.exe
2015-12-07 10:46:59> ApplyReleasesImpl: Moving file C:\Users\M\AppData\Local\launcher\app-0.0.7\lib\net45\d3dcompiler_47.dll to C:\Users\M\AppData\Local\launcher\app-0.0.7\d3dcompiler_47.dll
2015-12-07 10:46:59> ApplyReleasesImpl: Moving file C:\Users\M\AppData\Local\launcher\app-0.0.7\lib\net45\content_shell.pak to C:\Users\M\AppData\Local\launcher\app-0.0.7\content_shell.pak
2015-12-07 10:46:59> ApplyReleasesImpl: Moving file C:\Users\M\AppData\Local\launcher\app-0.0.7\lib\net45\ffmpegsumo.dll to C:\Users\M\AppData\Local\launcher\app-0.0.7\ffmpegsumo.dll
2015-12-07 10:46:59> ApplyReleasesImpl: Moving file C:\Users\M\AppData\Local\launcher\app-0.0.7\lib\net45\icudtl.dat to C:\Users\M\AppData\Local\launcher\app-0.0.7\icudtl.dat
2015-12-07 10:46:59> ApplyReleasesImpl: Moving file C:\Users\M\AppData\Local\launcher\app-0.0.7\lib\net45\libEGL.dll to C:\Users\M\AppData\Local\launcher\app-0.0.7\libEGL.dll
2015-12-07 10:46:59> ApplyReleasesImpl: Moving file C:\Users\M\AppData\Local\launcher\app-0.0.7\lib\net45\libGLESv2.dll to C:\Users\M\AppData\Local\launcher\app-0.0.7\libGLESv2.dll
2015-12-07 10:46:59> ApplyReleasesImpl: Moving file C:\Users\M\AppData\Local\launcher\app-0.0.7\lib\net45\LICENSE to C:\Users\M\AppData\Local\launcher\app-0.0.7\LICENSE
2015-12-07 10:46:59> ApplyReleasesImpl: Moving file C:\Users\M\AppData\Local\launcher\app-0.0.7\lib\net45\msvcp120.dll to C:\Users\M\AppData\Local\launcher\app-0.0.7\msvcp120.dll
2015-12-07 10:46:59> ApplyReleasesImpl: Moving file C:\Users\M\AppData\Local\launcher\app-0.0.7\lib\net45\msvcr120.dll to C:\Users\M\AppData\Local\launcher\app-0.0.7\msvcr120.dll
2015-12-07 10:46:59> ApplyReleasesImpl: Moving file C:\Users\M\AppData\Local\launcher\app-0.0.7\lib\net45\natives_blob.bin to C:\Users\M\AppData\Local\launcher\app-0.0.7\natives_blob.bin
2015-12-07 10:46:59> ApplyReleasesImpl: Moving file C:\Users\M\AppData\Local\launcher\app-0.0.7\lib\net45\node.dll to C:\Users\M\AppData\Local\launcher\app-0.0.7\node.dll
2015-12-07 10:46:59> ApplyReleasesImpl: Moving file C:\Users\M\AppData\Local\launcher\app-0.0.7\lib\net45\snapshot_blob.bin to C:\Users\M\AppData\Local\launcher\app-0.0.7\snapshot_blob.bin
2015-12-07 10:46:59> ApplyReleasesImpl: Moving file C:\Users\M\AppData\Local\launcher\app-0.0.7\lib\net45\ui_resources_200_percent.pak to C:\Users\M\AppData\Local\launcher\app-0.0.7\ui_resources_200_percent.pak
2015-12-07 10:46:59> ApplyReleasesImpl: Moving file C:\Users\M\AppData\Local\launcher\app-0.0.7\lib\net45\xinput1_3.dll to C:\Users\M\AppData\Local\launcher\app-0.0.7\xinput1_3.dll
2015-12-07 10:46:59> ApplyReleasesImpl: Moving file C:\Users\M\AppData\Local\launcher\app-0.0.7\lib\net45\pdf.dll to C:\Users\M\AppData\Local\launcher\app-0.0.7\pdf.dll
2015-12-07 10:46:59> ApplyReleasesImpl: Moving file C:\Users\M\AppData\Local\launcher\app-0.0.7\lib\net45\squirrel.exe to C:\Users\M\AppData\Local\launcher\app-0.0.7\squirrel.exe
2015-12-07 10:46:59> ApplyReleasesImpl: Moving file C:\Users\M\AppData\Local\launcher\app-0.0.7\lib\net45\vccorlib120.dll to C:\Users\M\AppData\Local\launcher\app-0.0.7\vccorlib120.dll
2015-12-07 10:47:12> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\M\AppData\Local\launcher\app-0.0.7\Launcher.exe]
2015-12-07 10:47:15> ApplyReleasesImpl: Starting fixPinnedExecutables
2015-12-07 10:47:15> ApplyReleasesImpl: fixPinnedExecutables: oldAppDirectories is empty, this is pointless
2015-12-07 10:47:15> ApplyReleasesImpl: Fixing up tray icons
2015-12-07 10:47:15> ApplyReleasesImpl: cleanDeadVersions: for version 0.0.7
2015-12-07 10:47:15> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.0.7
```
```
2015-12-07 10:47:01> Program: Starting Squirrel Updater: --updateSelf=C:\Users\M\AppData\Local\SquirrelTemp\Update.exe
2015-12-07 10:47:01> Program: About to wait for parent PID 4136
```

**Comment by paulcbetts** [comment]
My Psychic Debugger is saying that your app is crashing on first run and just hanging around, as Electron apps usually do when they crash

**Comment by marwanhilmi** [comment]
This is honestly something I've considered and will investigate further - is there any additional information in the Squirrel logs that can indicate what state the application is in? Unless I am wrong, everything seems ordinary in the Squirrel logs correct?

I need to verify with the users if the shortcuts get created but from what I recall - they are not, so the application is terminating before that even though that is the first hook into the application.

**Comment by paulcbetts** [comment]
I'd start by trying to just run your app from CMD:

```
DuelystLauncher.exe --squirrel-install 0.0.7
DuelystLauncher.exe --squirrel-firstrun
```

And see if that does what you expect

**Comment by marwanhilmi** [comment]
Apologies, closing this and it does appear to be related to the application itself.
