### ISSUE TITLE
Releasify not creating -full package file

### ISSUE THREAD

**Issue by bkCDL** [Squirrel/Squirrel.Windows#539]
I just upgraded my Squirrel version to 1.2.1. 

I tried to run the "releasify" command after my app rebuild as follows:
`Squirrel --releasify ..\App.1.0.0.5.nupkg -n "/a /f SHT-CodeSign-2015.pfx /p ##### " -r ..\Releases`

But I get this error:

```
2016-01-04 09:41:11> Program: Starting Squirrel Updater: --releasify ..\App.1.0.0.5.nupkg -n /a /f SHT-CodeSign-2015.pfx /p #####  -r ..\Releases
2016-01-04 09:41:11> Program: Bootstrapper EXE found at:E:\CDL\App\App\App\packages\squirrel.windows.1.2.1\tools\Setup.exe
2016-01-04 09:41:11> Program: Creating release package: E:\CDL\App\App\Releases\App.1.0.0.5.nupkg
2016-01-04 09:41:11> ReleasePackage: Creating release package: E:\CDL\App\App\Releases\App.1.0.0.5.nupkg => E:\CDL\App\App\Releases\App-1.0.0.5-full.nupkg
2016-01-04 09:41:11> ReleasePackage: Couldn't find file for package in .: NuGet.Commands
2016-01-04 09:41:11> Unhandled exception: System.Exception: Couldn't find file for package in .: NuGet.Commands
   at Squirrel.ReleasePackage.<>c__DisplayClass22_0.<findAllDependentPackages>b__2(PackageDependency dependency)
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Squirrel.ReleasePackage.findAllDependentPackages(IPackage package, IPackageRepository packageRepository, HashSet`1 packageCache, FrameworkName frameworkName)
   at Squirrel.ReleasePackage.CreateReleasePackage(String outputFile, String packagesRootDir, Func`2 releaseNotesProcessor, Action`1 contentsPostProcessHook)
   at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon, Boolean generateMsi)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
```

It looks like it's not creating the "App.1.0.0.5-full.nupkg" file in the "Releases" directory.

Any thoughts why this might occur?

Bryan

**Comment by AnderssonPeter** [comment]
Im having the same problem, but with `GoogleAnalyticsTracker.Simple` instead of `NuGet.Commands`.
I added `GoogleAnalyticsTracker.Simple` in my latest version of the package.

**Comment by AnderssonPeter** [comment]
I wanted to debug this issue, but im a bit confused i cloned the github repo but the `Squirrel` is a class library and not a console application?

**Comment by AnderssonPeter** [comment]
Ok i feel a bit stupid, `GoogleAnalyticsTracker.Simple` is added as a dependency and i guess thats the problem, but a better error message would be nice!

**Comment by AnderssonPeter** [comment]
Adding `developmentDependency="true"` to the package in `packages.config` solved the problem!

**Comment by bkCDL** [comment]
Thanks @AnderssonPeter ! That works for me too.

**Comment by DorGoldi** [comment]
That doens't work me :(

here the content of the packages.config file:
<packages>
  <package id="DeltaCompressionDotNet" version="1.1.0" targetFramework="net452" developmentDependency="true"/>
  <package id="PDFsharp-wpf" version="1.50.4740-beta5" targetFramework="net452" developmentDependency="true" />
....


and the error received:

PM> Squirrel --releasify HitKli_WpfApp.1.0.0.nupkg --releaseDir "C:\SquirrelReleases"
Squirrel : System.Exception: Couldn't find file for package in .: PDFsharp-wpf
At line:1 char:1
+ Squirrel --releasify HitKli_WpfApp.1.0.0.nupkg --releaseDir "C:\SquirrelReleases ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (System.Exceptio....: PDFsharp-wpf:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
   at Squirrel.ReleasePackage.<>c__DisplayClass20_0.<findAllDependentPackages>b__2(PackageDependency dependency)
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   a
t System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Squirrel.ReleasePackage.findAllDependentPackages(IPackage package, IPackageRepository packageRepository, HashSet`1 packageCache, FrameworkName f
rameworkName)
   at Squirrel.ReleasePackage.CreateReleasePackage(String outputFile, String packagesRootDir, Func`2 releaseNotesProcessor, Action`1 contentsPostProce
ssHook)
   at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String sig
ningOpts, String baseUrl, String setupIcon, Boolean generateMsi, String frameworkVersion, Boolean generateDeltas)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)


any help will be appreciated!!

**Comment by Andlo2013** [comment]
DorGoldi. I have the same problem

Can you solve?

**Comment by DorGoldi** [comment]
I fixed that one and had anther issue, got despaired, gave up, and started using a simple script (Inno setup) for a less complex installation.

**Comment by antoineazar** [comment]
Anyone can help on this issue? I'm hitting the same thing.

**Comment by Thieum** [comment]
@Andlo2013 @antoineazar if you are still experiencing the issue, please create a new issue with a screenshot of your nupkg open in Nuget Package Explorer like this:

![image](https://user-images.githubusercontent.com/944894/57257853-ade54f80-7028-11e9-82e3-91c661a806bc.png)


@shiftkey original question has been answered. this can be closed.
