### ISSUE TITLE
rcedit crashes on Windows 2012 r2 server causing installer build to fail from Squirrel

### ISSUE THREAD

**Issue by backpacked** [Squirrel/Squirrel.Windows#542]
While building through Release Management for Visual Studio or directly executing the command from PowerShell or cmd prompt, Squirrel fails to complete the process. The installer is created but rcedit crashes and the process fails.
## Squirrel Log Ouput:

2016-01-04 17:30:39> Program: Starting Squirrel Updater: --releasify C:\Users\builder\AppData\Local\Temp\RM\T\RM\AppBuildInstaller\201601041730252849730-3\App.5.0.5840.28508.nupkg --no-msi --releaseDir d:\releases\qa
2016-01-04 17:30:39> Program: Bootstrapper EXE found at:C:\Users\builder\AppData\Local\Temp\RM\T\RM\AppBuildInstaller\201601041730252849730-3\tools\squirrel\Setup.exe
2016-01-04 17:30:39> Program: Creating release package: C:\Users\builder\AppData\Local\Temp\RM\T\RM\AppBuildInstaller\201601041730252849730-3\Releases\App.5.0.5840.28508.nupkg
2016-01-04 17:30:39> ReleasePackage: Creating release package: C:\Users\builder\AppData\Local\Temp\RM\T\RM\AppBuildInstaller\201601041730252849730-3\Releases\App.5.0.5840.28508.nupkg => C:\Users\builder\AppData\Local\Temp\RM\T\RM\AppBuildInstaller\201601041730252849730-3\Releases\App-5.0.5840.28508-full.nupkg
2016-01-04 17:30:42> ReleasePackage: Extracting dependent packages: []
2016-01-04 17:30:42> ReleasePackage: Removing unnecessary data
2016-01-04 17:30:42> ReleasePackage: No release notes found in C:\Users\builder\AppData\Local\SquirrelTemp\tempa\App.nuspec
2016-01-04 17:30:44> Program: Building embedded zip file for Setup.exe
2016-01-04 17:30:47> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.Exception: Failed to modify resources, command invoked was: 'C:\Users\builder\AppData\Local\Temp\RM\T\RM\AppBuildInstaller\201601041730252849730-3\tools\squirrel\rcedit.exe "C:\Users\builder\AppData\Local\Temp\RM\T\RM\AppBuildInstaller\201601041730252849730-3\Releases\Setup.exe" --set-version-string "CompanyName" "MY GREAT COMPANY" --set-version-string "LegalCopyright" "Copyright © 2016 MY GREAT COMPANY" --set-version-string "FileDescription" "Construction documentation and payment application" --set-version-string "ProductName" "Construction documentation and payment application" --set-file-version 5.0.5840.28508 --set-product-version 5.0.5840.28508'

Output was:

   at Squirrel.Update.Program.<setPEVersionInfoAndIcon>d__17.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Squirrel.Update.Program.<>c__DisplayClass9_0.<Releasify>b__10()
   at Squirrel.Utility.<>c__DisplayClass8_0.<Retry>b__0()
   at Squirrel.Utility.Retry[T](Func`1 block, Int32 retries)
   at Squirrel.Utility.Retry(Action block, Int32 retries)
   at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon, Boolean generateMsi)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.Exception: Failed to modify resources, command invoked was: 'C:\Users\builder\AppData\Local\Temp\RM\T\RM\AppBuildInstaller\201601041730252849730-3\tools\squirrel\rcedit.exe "C:\Users\builder\AppData\Local\Temp\RM\T\RM\AppBuildInstaller\201601041730252849730-3\Releases\Setup.exe" --set-version-string "CompanyName" "MY GREAT COMPANY" --set-version-string "LegalCopyright" "Copyright © 2016 MY GREAT COMPANY" --set-version-string "FileDescription" "Construction documentation and payment application" --set-version-string "ProductName" "Construction documentation and payment application" --set-file-version 5.0.5840.28508 --set-product-version 5.0.5840.28508'

Output was:

   at Squirrel.Update.Program.<setPEVersionInfoAndIcon>d__17.MoveNext()<---

**Comment by paulcbetts** [comment]
What happens if you run the rcedit command directly?

**Comment by backpacked** [comment]
it crashes. There is a rcedit issue: https://github.com/atom/rcedit/issues/3

I tried copying the MSVCP100.dll but now  the error is with ntdll.dll which already exists.

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	rcedit.exe
  Application Version:	0.2.0.0
  Application Timestamp:	528436dd
  Fault Module Name:	ntdll.dll
  Fault Module Version:	6.3.9600.18146
  Fault Module Timestamp:	5650afd4
  Exception Code:	c000012f
  Exception Offset:	0009d572
  OS Version:	6.3.9600.2.0.0.272.7
  Locale ID:	1033
  Additional Information 1:	1abe
  Additional Information 2:	1abee00edb3fc1158f9ad6f44f0f6be8
  Additional Information 3:	1abe
  Additional Information 4:	1abee00edb3fc1158f9ad6f44f0f6be8

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=280262

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by paulcbetts** [comment]
This is saying that rcedit.exe is corrupted, check the file and perhaps disable any 3rd party shady Antivirus

**Comment by backpacked** [comment]
The same application on my Windows 7 is not crashing and I am not using any shady antivirus. Please reopen the issue.

Appreciate you help.

**Comment by paulcbetts** [comment]
I don't know what to tell you, that error code means the file is missing an executable header

**Comment by paulcbetts** [comment]
```
0: kd> !error c000012f
Error code: (NTSTATUS) 0xc000012f (3221225775) - The specified image file did not have the correct format, it did not have an initial MZ.
```

**Comment by backpacked** [comment]
I am not even using an image. I just ran the command. > rcedit.exe and it crashed on Win 2012 R2 server. On my Win 7 box it exits gracefully with - "Fatal error: You should specify a exe/dll file"

**Comment by backpacked** [comment]
Is there way I could demonstrate the error for you? I am using the same executable on two machines. The exe is on machine A and it fails on machine A. I shared the directory and tried to run it on machine B and it works. It is not even a copy. It is the same executable. Squirrel is critical for our process and I do not want to try any other solution. The current problem is an impediment and we may have to introduce a manual step in our automation effort but if that is how it works, we may have to live with it.

**Comment by paulcbetts** [comment]
> I am not even using an image. 

Here 'image file' means rcedit.exe, as in PE Image

> Is there way I could demonstrate the error for you?

I mean, I believe you, I just don't know what you can do about it. Are you sure it's the same exception code every time?

**Comment by backpacked** [comment]
Yes. The error is consistent across all systems I have tried. My dev says, I should install Visual Studio 2015 on the server and then try it. It probably will take care of the issue as the dev has been running Squirrel on Windows 10 and has had no problems unlike the https://github.com/atom/rcedit/issues/3 issue. It may be that that the appropriate dlls are found by rcedit when VS is installed. I will post my findings tomorrow.

**Comment by shiftkey** [comment]
Merging this into #888 which is about upgrading rcedit, which sounds like it should address it given the details in the last comment.
