### ISSUE TITLE
FileNotFoundException: Could not load file or assembly 'Microsoft.Data.OData, Version=5.6.1.0...

### ISSUE THREAD

**Issue by dsaf** [Squirrel/Squirrel.Windows#569]
I have an application that uses NServiceBus and Autofac.

NServiceBus scans referenced assemblies to generate an IoC container.

I have installed the official ```squirrel.windows``` NuGet package into the application and it started to fail on startup:

```
System.Exception was unhandled
  HResult=-2146233088
  Message=Could not enumerate all types for '...bin\Debug\NuGet.Squirrel.dll'.
Exceptions:
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Data.OData, Version=5.6.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Data.OData, Version=5.6.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

=== Pre-bind state information ===
LOG: DisplayName = Microsoft.Data.OData, Version=5.6.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
 (Fully-specified)
LOG: Appbase = 
LOG: Initial PrivatePath = NULL
Calling assembly : NuGet.Squirrel, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file:
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: Microsoft.Data.OData, Version=5.6.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
LOG: Attempting download of new URL .../bin/Debug/Microsoft.Data.OData.DLL.
LOG: Attempting download of new URL .../bin/Debug/Microsoft.Data.OData/Microsoft.Data.OData.DLL.
LOG: Attempting download of new URL .../bin/Debug/Microsoft.Data.OData.EXE.
LOG: Attempting download of new URL .../bin/Debug/Microsoft.Data.OData/Microsoft.Data.OData.EXE.



  Source=NServiceBus.Core
  StackTrace:
       at NServiceBus.Hosting.Helpers.AssemblyScanner.ScanAssembly(String assemblyPath, AssemblyScannerResults results) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Hosting\Helpers\AssemblyScanner.cs:line 153
       at NServiceBus.Hosting.Helpers.AssemblyScanner.GetScannableAssemblies() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Hosting\Helpers\AssemblyScanner.cs:line 65
       at NServiceBus.BusConfiguration.GetAssembliesInDirectory(String path, String[] assembliesToSkip) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\BusConfiguration.cs:line 250
       at NServiceBus.BusConfiguration.ScanAssembliesInDirectory(String probeDirectory) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\BusConfiguration.cs:line 89
       at NServiceBus.BusConfiguration.BuildConfiguration() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\BusConfiguration.cs:line 191
       at NServiceBus.Bus.Create(BusConfiguration configuration) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Bus.cs:line 17
       at ....AppBootstrapper.Run() in ...\AppBootstrapper.cs:line 61
       at ....App..ctor() in ...\App.xaml.cs:line 14
       at ....App.Main() in ...\obj\Debug\App.g.cs:line 0
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()```

**Comment by dsaf** [comment]
Possibly related to #531.

**Comment by paulcbetts** [comment]
Sounds like you'll need to ship this DLL in order to make NServiceBus not whine
