### ISSUE TITLE
WPF App - SquirrelAwareApp.HandleEvents doesn't run

### ISSUE THREAD

**Issue by ArcadeRenegade** [Squirrel/Squirrel.Windows#596]
In my App.xaml.cs I created a constructor for app and put the HandleEvents there but none of them run. This is as early as I could possibly get it.

```
public App()
{
    using (UpdateManager _manager = new UpdateManager(@"C:\Releases"))
    {
        SquirrelAwareApp.HandleEvents(
            v => _manager.CreateShortcutForThisExe(),
            v => _manager.CreateShortcutForThisExe(),
            v => _manager.RemoveShortcutForThisExe(),
            v => _manager.RemoveShortcutForThisExe()
            );
    }
}
```

Later in the application startup I run the updates.

```
using (UpdateManager _manager = new UpdateManager(@"C:\Releases"))
{
    await _manager.UpdateApp();
}
```

In the Squirrel log I see a relevant error:

```
2016-02-10 03:05:20> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\Ryan\AppData\Local\SidebarDiagnostics\app-2.5.0\SidebarDiagnostics.exe]
2016-02-10 03:05:20> ApplyReleasesImpl: Couldn't run Squirrel hook, continuing: C:\Users\Ryan\AppData\Local\SidebarDiagnostics\app-2.5.0\SidebarDiagnostics.exe: System.ComponentModel.Win32Exception (0x80004005): The requested operation requires elevation
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Squirrel.Utility.<InvokeProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass10_0.<<invokePostInstall>b__0>d.MoveNext()
2016-02-10 03:05:20> ApplyReleasesImpl: Starting fixPinnedExecutables
```

The message seems to be "The requested operation requires elevation".

I've tried everything and looked the docs, other issue threads, etc. I'm at the end of my wits here.

I need to be able to get the path of the NEW executable directly after an update occurs.

The HandleEvents onAppUpdate hook should be able to handle that right?

**Comment by ArcadeRenegade** [comment]
I should mention, in my application manifest I have "requestedExecutionLevel" set to "requiresAdministrator". Because my application requires admin access to work properly. 

I hope this is supposed, everything else works great just not the hooks :|

**Comment by paulcbetts** [comment]
@arcaderenegade Squirrel doesn't support applications that require UAC.

**Comment by ArcadeRenegade** [comment]
I see. Is there any way to build my Setup.exe with the requires Admin requested  execution level in the manifest?

**Comment by paulcbetts** [comment]
@ArcadeRenegade No, sorry. The only thing you _might_ be able to do is create a non-elevated helper EXE that is marked as Squirrel-Aware, then do your setup work there, and mark your main EXE as elevated.

**Comment by paulcbetts** [comment]
@ArcadeRenegade Also, why do you want to be elevated? Maybe there's a way that you don't need to be

**Comment by ArcadeRenegade** [comment]
It's a diagnostic app so it needs admin rights to query hardware data.

Your second exe solution might work I'll try it out.

**Comment by ArcadeRenegade** [comment]
If I were to build squirrel myself, do you think you could point me in the right direction as to how to force the build of setup.exe and update.exe to run as admin?

**Comment by ArcadeRenegade** [comment]
So I built squirrel.windows setup.exe and update.exe with the requiresAdmin flag and setup.exe kept prompting UAC in a loop. So that didn't work. 

Since I only cared about updates, I just did the stuff I needed to do in my app's update check. And built the path to the new version folder manually. Works great.
