### ISSUE TITLE
Proxy issue will stop deployment in many corps

### ISSUE THREAD

**Issue by wamra** [Squirrel/Squirrel.Windows#617]
Hi, 
I with there is a way to setup a proxy, the same as apt-get on linux. This issue is preventing me from running gitkraken for example. Our corp lives behind heavily secured proxies.

**Comment by paulcbetts** [comment]
Sure, just download `https://(update URL)/RELEASES` and all the files it references, then run:

```
cd C:\Users\NAME\AppData\Local\GitKraken
update --update .\path\to\my\downloaded\files
```

**Comment by wamra** [comment]
I get the following error in log, can't squirrel it's self identify and use proxies. We have an auto config script on an http location for proxy settings.

```
2016-03-15 11:55:58> Program: Starting Squirrel Updater: --update D:\Downloads\Git\GitKraken
2016-03-15 11:55:58> Program: Starting update, downloading from D:\Downloads\Git\GitKraken
2016-03-15 11:55:58> Program: About to update to: C:\Users\******\AppData\Local\gitkraken
2016-03-15 11:55:58> CheckForUpdateImpl: Reading RELEASES file from D:\Downloads\Git\GitKraken
2016-03-15 11:56:00> InstallHelperImpl: Couldn't write uninstall icon, don't care: System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)


```

**Comment by rdegelo** [comment]
Same problem here, my corp uses automatic configuration script for proxy.
Squirrel do not detect it automatically.

Is there a way to manually set proxy?

**Comment by wamra** [comment]
What is worse is that it keeps attempting to connect, so it was flagged/picked up by cyber security as a risk. I wish it provides is a plain offline installer as alternative.

**Comment by rdegelo** [comment]
Seems like WebRequest.DefaultWebProxy does not recognize .pac script if it is using wrong mime-type.
In my case I cannot modify this. So I found this site: http://www.codeproject.com/Articles/12168/Using-PAC-files-proxy that uses Win32 API call to get the proxy properly, and then I set manually the WebRequest.DefaultWebProxy before Update check process.

Unfortunately I still get 403, Forbidden. Maybe setting WebRequest.DefaultWebProxy manually does not work?

Any ideas?

**Comment by rdegelo** [comment]
Looks like my corp proxy settings are not supported by standard WebRequest.
Is it possible to manually set the WebRequest used by Squirrel?

**Comment by rdegelo** [comment]
Added Issue #657
