### ISSUE TITLE
Package Exception: Targets Multiple Versions

### ISSUE THREAD

**Issue by erdomke** [Squirrel/Squirrel.Windows#623]
For a .Net 4.5 console application I am working on at work, I am continually getting the following error stating that `...nupkg targets multiple platforms - .NETFramework,Version=
  v4.5; Unsupported,Version=v0.0;  - and cannot be transformed into a release package.`.  I cannot seem to figure out a workaround for this.  My `.nuspec` file is also reproduced below which shows that all the files are being put in the lib\net45 directory like they should be.  I have other projects using Squirrel which are packaged using a similar script and do not have the issue.  What do I need to do to successfully package this application?

**Console output from MSBuild script:**

```
..\.nuget\NuGet.exe Pack CtMeasurementClient.nuspec
  Attempting to build package from 'CtMeasurementClient.nuspec'.
  Successfully created package 'C:\Users\eric.domke\Documents\Code\CtMeasurementClient\CtMeasurementClient\CtMeasuremen
  tClient.2016.03.08.1649.nupkg'.
  ..\packages\squirrel.windows.1.2.5\tools\Squirrel.exe --releasify=CtMeasurementClient.2016.03.08.1649.nupkg --no-msi
  System.InvalidOperationException: The input package file C:\Users\eric.domke\Documents\Code\CtMeasurementClient\CtMea
  surementClient\Releases\CtMeasurementClient.2016.02.10.1634.nupkg targets multiple platforms - .NETFramework,Version=
  v4.5; Unsupported,Version=v0.0;  - and cannot be transformed into a release package.
     at Squirrel.ReleasePackage.CreateReleasePackage(String outputFile, String packagesRootDir, Func`2 releaseNotesProc
  essor, Action`1 contentsPostProcessHook)
     at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe,
   String backgroundGif, String signingOpts, String baseUrl, String setupIcon, Boolean generateMsi)
     at Squirrel.Update.Program.executeCommandLine(String[] args)
     at Squirrel.Update.Program.main(String[] args)
     at Squirrel.Update.Program.Main(String[] args)
```

**Nuspec File:**
```
<?xml version="1.0" encoding="utf-8"?>
  <package>
    <metadata>
      <id>CtMeasurementClient</id>
      <version>2016.03.08.1649</version>
      <authors>eric.domke</authors>
      <requireLicenseAcceptance>false</requireLicenseAcceptance>
      <iconUrl>file:///icon.png</iconUrl>
    </metadata>
    <files>
<file src="bin\Release\**\*.*" target="lib\net45" exclude="bin\Release\**\*.pdb;bin\Release\*.nupkg;bin\Release\*.vshost.*;bin\Release\**\*.dylib;bin\Release\**\*.so"/>
</files>
  </package>
```

**Comment by erdomke** [comment]
This appears to be a problem with the packages pre-existing in my Releases directory.  I resolved this by removing all the existing packages from that directory.
