### ISSUE TITLE
Crashing during update

### ISSUE THREAD

**Issue by lipis** [Squirrel/Squirrel.Windows#690]
It's quite strange because the folder exists and it's trying to burn it to the ground and then it complains about that part of the path is not there.. very strange!

So I'm not sure if someone can get anything useful from that.. but here it is anyway..

```
2016-05-11 14:46:11> Program: Starting install, writing to C:\Users\jenkins\AppData\Local\SquirrelTemp
2016-05-11 14:46:11> Program: About to install to: C:\Users\jenkins\AppData\Local\wire
2016-05-11 14:46:11> Program: Install path C:\Users\jenkins\AppData\Local\wire already exists, burning it to the ground
2016-05-11 14:46:12> IEnableLogger: Failed to copy Update.exe to C:\Users\jenkins\AppData\Local\wire\Update.exe: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\jenkins\AppData\Local\wire\Update.exe'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Squirrel.Update.Program.<>c__DisplayClass36.<Install>b__2d()
   at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
2016-05-11 14:46:12> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\jenkins\AppData\Local\wire\Update.exe'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Squirrel.Update.Program.<>c__DisplayClass36.<Install>b__2d()
   at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
   at Squirrel.Utility.ErrorIfThrows(IEnableLogger This, Action block, String message)
   at Squirrel.Update.Program.<Install>d__38.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\jenkins\AppData\Local\wire\Update.exe'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Squirrel.Update.Program.<>c__DisplayClass36.<Install>b__2d()
   at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
   at Squirrel.Utility.ErrorIfThrows(IEnableLogger This, Action block, String message)
   at Squirrel.Update.Program.<Install>d__38.MoveNext()<---
```

**Comment by rahulbm** [comment]
@lipis did you found any work-around on this issue?

**Comment by lipis** [comment]
:D Should work now.. https://github.com/wireapp/wire-desktop
