### ISSUE TITLE
Squirrel aware exe is not called with --squirrel-install at the end of installation

### ISSUE THREAD

**Issue by dessant** [Squirrel/Squirrel.Windows#701]
I'm using Squirrel with a Python app packaged by PyInstaller, `SquirrelAwareVersion` is set and it seems to be detected correctly (Squirrel runs the right exe and no shortcuts are created).

The only call I receive at the end of the installation is `--squirrel-firstrun`, a second call with `--squirrel-install` is missing.
https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/custom-squirrel-events-non-cs.md

**Comment by paulcbetts** [comment]
You should receive `--squirrel-install` first, then `--squirrel-firstrun`

**Comment by paulcbetts** [comment]
It's odd that this would be the case, not getting shortcuts but still getting `--squirrel-firstrun`

**Comment by dessant** [comment]
Before I've set `SquirrelAwareVersion` for the main exe `--squirrel-firstrun` was sent the same way, the difference was that the app worker exe also received it and shorcuts were set.

Is it normal to receive *any* event when `SquirrelAwareVersion` is not set?

**Comment by paulcbetts** [comment]
> Is it normal to receive any event when SquirrelAwareVersion is not set?

It's supposed to be that you don't receive any events, but I may have messed that up. I'd use Resource Hacker to verify you're setting the resource correctly, you can compare the EXE to https://github.com/electron/electron to see if it's set correctly

**Comment by dessant** [comment]
I'm seeing the same behavior while using Electron's VERSIONINFO.

Mine is:
```
1 VERSIONINFO
FILEVERSION 0,0,0,0
PRODUCTVERSION 0,0,0,0
FILEOS 0x40004
FILETYPE 0x1
{
BLOCK "StringFileInfo"
{
	BLOCK "040904B0"
	{
		VALUE "SquirrelAwareVersion", "1"
	}
}

BLOCK "VarFileInfo"
{
	VALUE "Translation", 0x0409 0x04B0
}
}
```

electron.exe:
```
1 VERSIONINFO
FILEVERSION 1,1,1,0
PRODUCTVERSION 1,1,1,0
FILEOS 0x40004
FILETYPE 0x1
{
BLOCK "StringFileInfo"
{
	BLOCK "040904b0"
	{
		VALUE "CompanyName", "GitHub, Inc."
		VALUE "FileDescription", "Electron"
		VALUE "FileVersion", "1.1.1"
		VALUE "InternalName", "electron.exe"
		VALUE "LegalCopyright", "Copyright (C) 2015 GitHub, Inc. All rights reserved."
		VALUE "OriginalFilename", "electron.exe"
		VALUE "ProductName", "Electron"
		VALUE "ProductVersion", "1.1.1"
		VALUE "SquirrelAwareVersion", "1"
	}
}

BLOCK "VarFileInfo"
{
	VALUE "Translation", 0x0409 0x04B0
}
}
```

**Comment by paulcbetts** [comment]
@dessant Can you share your SquirrelSetup.log file?

**Comment by dessant** [comment]
Ok, so my test was flawed, I have written all arguments to a file (opened with a relative path) to see what got passed.

When the exe was called with `--squirrel-install`, the current working directory was `C:\Users\prc\AppData\Local\SquirrelTemp`, I've found the file with the expected line there. I'm unsure if using this folder as the cwd for this call is intended or not.

When the exe was called with `--squirrel-firstrun`, the cwd was the parent folder of the exe, this is why I was seeing this call only.

I'll post some logs shortly.

**Comment by dessant** [comment]
No VERSIONINFO resource, the EXEs are not Squirrel aware.

Passed events and their current working directory:
```
'C:\\Users\\prc\\AppData\\Local\\TestApp\\app-1.0.0\\testapp.exe', '--squirrel-firstrun, C:\Users\prc\AppData\Local\TestApp\app-1.0.0
'C:\\Users\\prc\\AppData\\Local\\TestApp\\app-1.0.0\\testapp-worker.exe', '--squirrel-firstrun, C:\Users\prc\AppData\Local\TestApp\app-1.0.0
```

SquirrelSetup.log:
```
2016-05-21 01:45:11> Program: Starting Squirrel Updater: --install .
2016-05-21 01:45:11> Program: Starting install, writing to C:\Users\prc\AppData\Local\SquirrelTemp
2016-05-21 01:45:11> Program: About to install to: C:\Users\prc\AppData\Local\TestApp
2016-05-21 01:45:11> Program: Install path C:\Users\prc\AppData\Local\TestApp already exists, burning it to the ground
2016-05-21 01:45:11> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\prc\AppData\Local\TestApp\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2016-05-21 01:45:11> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\prc\AppData\Local\TestApp\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__3f.MoveNext()
2016-05-21 01:45:11> CheckForUpdateImpl: Reading RELEASES file from C:\Users\prc\AppData\Local\SquirrelTemp
2016-05-21 01:45:11> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2016-05-21 01:45:12> ApplyReleasesImpl: Writing files to app directory: C:\Users\prc\AppData\Local\TestApp\app-1.0.0
2016-05-21 01:45:27> ApplyReleasesImpl: Moving file C:\Users\prc\AppData\Local\TestApp\app-1.0.0\lib\net45\testapp-worker.exe to C:\Users\prc\AppData\Local\TestApp\app-1.0.0\testapp-worker.exe
2016-05-21 01:45:27> ApplyReleasesImpl: Moving file C:\Users\prc\AppData\Local\TestApp\app-1.0.0\lib\net45\testapp.exe to C:\Users\prc\AppData\Local\TestApp\app-1.0.0\testapp.exe
2016-05-21 01:45:28> ApplyReleasesImpl: Squirrel Enabled Apps: []
2016-05-21 01:45:28> ApplyReleasesImpl: No apps are marked as Squirrel-aware! Going to run them all
2016-05-21 01:45:28> ApplyReleasesImpl: About to create shortcuts for testapp-worker.exe, rootAppDir C:\Users\prc\AppData\Local\TestApp
2016-05-21 01:45:28> ApplyReleasesImpl: Creating shortcut for testapp-worker.exe => C:\Users\prc\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\TestApp\TestApp.lnk
2016-05-21 01:45:28> ApplyReleasesImpl: About to save shortcut: C:\Users\prc\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\TestApp\TestApp.lnk (target C:\Users\prc\AppData\Local\TestApp\Update.exe, workingDir C:\Users\prc\AppData\Local\TestApp\app-1.0.0, args --processStart testapp-worker.exe)
2016-05-21 01:45:28> ApplyReleasesImpl: Creating shortcut for testapp-worker.exe => C:\Users\prc\Desktop\TestApp.lnk
2016-05-21 01:45:28> ApplyReleasesImpl: About to save shortcut: C:\Users\prc\Desktop\TestApp.lnk (target C:\Users\prc\AppData\Local\TestApp\Update.exe, workingDir C:\Users\prc\AppData\Local\TestApp\app-1.0.0, args --processStart testapp-worker.exe)
2016-05-21 01:45:28> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2016-05-21 01:45:28> ApplyReleasesImpl: Examining Pin: Mozilla Firefox.lnk
2016-05-21 01:45:29> ApplyReleasesImpl: About to create shortcuts for testapp.exe, rootAppDir C:\Users\prc\AppData\Local\TestApp
2016-05-21 01:45:29> ApplyReleasesImpl: Creating shortcut for testapp.exe => C:\Users\prc\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\TestApp\TestApp.lnk
2016-05-21 01:45:29> ApplyReleasesImpl: About to save shortcut: C:\Users\prc\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\TestApp\TestApp.lnk (target C:\Users\prc\AppData\Local\TestApp\Update.exe, workingDir C:\Users\prc\AppData\Local\TestApp\app-1.0.0, args --processStart testapp.exe)
2016-05-21 01:45:29> ApplyReleasesImpl: Creating shortcut for testapp.exe => C:\Users\prc\Desktop\TestApp.lnk
2016-05-21 01:45:29> ApplyReleasesImpl: About to save shortcut: C:\Users\prc\Desktop\TestApp.lnk (target C:\Users\prc\AppData\Local\TestApp\Update.exe, workingDir C:\Users\prc\AppData\Local\TestApp\app-1.0.0, args --processStart testapp.exe)
2016-05-21 01:45:29> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2016-05-21 01:45:29> ApplyReleasesImpl: Examining Pin: Mozilla Firefox.lnk
2016-05-21 01:45:29> ApplyReleasesImpl: Starting fixPinnedExecutables
2016-05-21 01:45:29> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2016-05-21 01:45:29> ApplyReleasesImpl: Examining Pin: Mozilla Firefox.lnk
2016-05-21 01:45:29> ApplyReleasesImpl: Fixing up tray icons
2016-05-21 01:45:29> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__ee(RegistryView view)
2016-05-21 01:45:29> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__ee(RegistryView view)
2016-05-21 01:45:29> ApplyReleasesImpl: cleanDeadVersions: for version 1.0.0
2016-05-21 01:45:29> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.0.0
```

**Comment by dessant** [comment]
VERSIONINFO is present and SquirrelAwareVersion is set for `testapp.exe`, the EXE is Squirrel aware.

Passed events and their current working directory:
```
'C:\\Users\\prc\\AppData\\Local\\TestApp\\app-1.0.0\\testapp.exe', '--squirrel-install', '1.0.0', C:\Users\prc\AppData\Local\SquirrelTemp
'C:\\Users\\prc\\AppData\\Local\\TestApp\\app-1.0.0\\testapp.exe', '--squirrel-firstrun', C:\Users\prc\AppData\Local\TestApp\app-1.0.0
'C:\\Users\\prc\\AppData\\Local\\TestApp\\app-1.0.0\\testapp.exe', '--squirrel-uninstall', '1.0.0', C:\Windows\System32
```

SquirrelSetup.log:
```
﻿2016-05-21 02:46:10> Program: Starting Squirrel Updater: --install .
2016-05-21 02:46:11> Program: Starting install, writing to C:\Users\prc\AppData\Local\SquirrelTemp
2016-05-21 02:46:11> Program: About to install to: C:\Users\prc\AppData\Local\TestApp
2016-05-21 02:46:11> Program: Install path C:\Users\prc\AppData\Local\TestApp already exists, burning it to the ground
2016-05-21 02:46:11> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\prc\AppData\Local\TestApp\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2016-05-21 02:46:11> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\prc\AppData\Local\TestApp\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__3f.MoveNext()
2016-05-21 02:46:11> CheckForUpdateImpl: Reading RELEASES file from C:\Users\prc\AppData\Local\SquirrelTemp
2016-05-21 02:46:11> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2016-05-21 02:46:11> ApplyReleasesImpl: Writing files to app directory: C:\Users\prc\AppData\Local\TestApp\app-1.0.0
2016-05-21 02:46:25> ApplyReleasesImpl: Moving file C:\Users\prc\AppData\Local\TestApp\app-1.0.0\lib\net45\testapp-worker.exe to C:\Users\prc\AppData\Local\TestApp\app-1.0.0\testapp-worker.exe
2016-05-21 02:46:25> ApplyReleasesImpl: Moving file C:\Users\prc\AppData\Local\TestApp\app-1.0.0\lib\net45\testapp.exe to C:\Users\prc\AppData\Local\TestApp\app-1.0.0\testapp.exe
2016-05-21 02:46:25> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\prc\AppData\Local\TestApp\app-1.0.0\testapp.exe]
2016-05-21 02:46:26> ApplyReleasesImpl: Starting fixPinnedExecutables
2016-05-21 02:46:26> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2016-05-21 02:46:26> ApplyReleasesImpl: Examining Pin: Mozilla Firefox.lnk
2016-05-21 02:46:26> ApplyReleasesImpl: Fixing up tray icons
2016-05-21 02:46:26> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__ee(RegistryView view)
2016-05-21 02:46:26> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__ee(RegistryView view)
2016-05-21 02:46:26> ApplyReleasesImpl: cleanDeadVersions: for version 1.0.0
2016-05-21 02:46:26> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.0.0
```

**Comment by dessant** [comment]
The original issue I was reporting is invalid, these are the likely bugs instead:
- `--squirrel-firstrun` is passed to all exes when none of them are Squirrel aware
- events are passed under different working directories for Squirrel aware executables

**Comment by flutefreak7** [comment]
@dessant , Did you get squirrel working for your pyinstaller application?  I'm curious about this since pyupdater is ok, but not as friendly as I would like.

**Comment by dessant** [comment]
I don't maintain any desktop app currently so it's a bit foggy *how* it all worked, but yes, it worked quite well.
