### ISSUE TITLE
"The base package release does not exist"

### ISSUE THREAD

**Issue by Aluxian** [Squirrel/Squirrel.Windows#707]
One of the users of [electron-windows-installer](https://github.com/Aluxian/electron-windows-installer) (which is a fork of [grunt-electron-installer](https://github.com/electron/grunt-electron-installer)) encountered this error when they tried to build a version that's already been released.

Please see the original issue for more context: https://github.com/Aluxian/electron-windows-installer/issues/8

I'm going to quote the original post from there:

> 
> Electron windows installer worked great but now suddenly without changing anything in our build process it stopped working throwing this error:
> ```
>  C:\a\node_modules\electron-windows-installer\vendor\Squirrel.exe --releasify C:\Users\avcd\AppData\Local\Temp\squirrel-installer-116424-8836-22vrou\avocodebeta.2.8.0-beta4.nupkg --releaseDir C:\a\release\build --loadingGif C:\a\resources\win\loading.gif --no-msi --setupIcon C:\a\resources\win\avocode.ico
> System.IO.FileNotFoundException: The base package release does not exist
> File name: 'C:\a\release\build\avocode-2.8.0-beta3-full.nupkg'
>    at Squirrel.DeltaPackageBuilder.CreateDeltaPackage(ReleasePackage basePackage, ReleasePackage newPackage, String outputFile)
>    at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon, Boolean generateMsi)
>    at Squirrel.Update.Program.executeCommandLine(String[] args)
>    at Squirrel.Update.Program.main(String[] args)
>    at Squirrel.Update.Program.Main(String[] args)
> ]
> 
> ```
> NOTE: file `avocode-2.8.0-beta3-full.nupkg` is available on our S3.
> 
> Do you have any tip for us what might caused this error? We are not able to create installer. The only real change was that we changed product name from `avocode` to `avocodebeta` and that was it. Here are our releases: https://avocode-media.s3.amazonaws.com/squirrel-windows-beta/RELEASES
> And config of installer is here:
> ```
> appDirectory: buildAppPath
>     outputDirectory: path.join(releaseFolder, 'build')
>     authors: 'Piffle LLC.'
>     loadingGif: path.join('resources', 'win', 'loading.gif')
>     setupIcon: path.join('resources', 'win', 'avocode.ico')
>     iconUrl: 'https://avocode-manager.r.worldssl.net/static/images/avocode.ico'
>     exe: 'Avocode.exe'
>     remoteReleases: 'https://avocode-media.s3.amazonaws.com/squirrel-windows-beta/'
>     noMsi: true
> ```

---

I know the fix is to either not build already released versions or modify the RELEASES file, but I thought I should report this bug here.

**Comment by Thieum** [comment]
From #1168

> As Squirrel doesn't check if a version already exists in the path to release, we need to check for this beforehand with an embedding script.
> It's hard to see where the current behavior can be a desired behavior, as it will break installs in most cases.
> Maybe at least put a flag to force a "no-existing-version-replacement" option that will throw an error if a version already exists in the release path.

**Comment by Thieum** [comment]
#1105 goes a step further, requesting to block the creation of intermediate versions. We could fix both by blocking anything that is inferior or equal to the most recent release.

**Comment by Thieum** [comment]
see also #42

**Comment by Fredy7777** [comment]
Check the created Release File. If you for example delete nuget Packages the base is missing. Adjust the entries in the Release File. So the delta can be detected.
