### ISSUE TITLE
CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 

### ISSUE THREAD

**Issue by wangxiexe** [Squirrel/Squirrel.Windows#710]
Got this isise, the fulllog is here, it is on windows 7: 

```
2016-05-25 20:02:11> Program: Starting Squirrel Updater: --install .
2016-05-25 20:02:12> Program: Starting install, writing to C:\Users\liwenjing.xiaomi\AppData\Local\SquirrelTemp
2016-05-25 20:02:12> Program: About to install to: C:\Users\liwenjing.xiaomi\AppData\Local\MiCloudPC
2016-05-25 20:02:13> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\liwenjing.xiaomi\AppData\Local\MiCloudPC\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2016-05-25 20:02:13> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\liwenjing.xiaomi\AppData\Local\MiCloudPC\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__3f.MoveNext()
2016-05-25 20:02:14> CheckForUpdateImpl: Reading RELEASES file from C:\Users\liwenjing.xiaomi\AppData\Local\SquirrelTemp
2016-05-25 20:02:14> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2016-05-25 20:02:14> ApplyReleasesImpl: Writing files to app directory: C:\Users\liwenjing.xiaomi\AppData\Local\MiCloudPC\app-0.0.136
2016-05-25 20:02:56> ApplyReleasesImpl: Moving file C:\Users\liwenjing.xiaomi\AppData\Local\MiCloudPC\app-0.0.136\lib\net45\natives_blob.bin to C:\Users\liwenjing.xiaomi\AppData\Local\MiCloudPC\app-0.0.136\natives_blob.bin
2016-05-25 20:02:56> ApplyReleasesImpl: Moving file C:\Users\liwenjing.xiaomi\AppData\Local\MiCloudPC\app-0.0.136\lib\net45\node.dll to C:\Users\liwenjing.xiaomi\AppData\Local\MiCloudPC\app-0.0.136\node.dll
2016-05-25 20:02:56> ApplyReleasesImpl: Moving file C:\Users\liwenjing.xiaomi\AppData\Local\MiCloudPC\app-0.0.136\lib\net45\snapshot_blob.bin to C:\Users\liwenjing.xiaomi\AppData\Local\MiCloudPC\app-0.0.136\snapshot_blob.bin
2016-05-25 20:02:56> ApplyReleasesImpl: Moving file C:\Users\liwenjing.xiaomi\AppData\Local\MiCloudPC\app-0.0.136\lib\net45\squirrel.exe to C:\Users\liwenjing.xiaomi\AppData\Local\MiCloudPC\app-0.0.136\squirrel.exe
2016-05-25 20:02:56> ApplyReleasesImpl: Moving file C:\Users\liwenjing.xiaomi\AppData\Local\MiCloudPC\app-0.0.136\lib\net45\ui_resources_200_percent.pak to C:\Users\liwenjing.xiaomi\AppData\Local\MiCloudPC\app-0.0.136\ui_resources_200_percent.pak
2016-05-25 20:02:56> ApplyReleasesImpl: Moving file C:\Users\liwenjing.xiaomi\AppData\Local\MiCloudPC\app-0.0.136\lib\net45\xinput1_3.dll to C:\Users\liwenjing.xiaomi\AppData\Local\MiCloudPC\app-0.0.136\xinput1_3.dll
2016-05-25 20:02:57> ApplyReleasesImpl: Squirrel Enabled Apps: []
2016-05-25 20:02:57> ApplyReleasesImpl: No apps are marked as Squirrel-aware! Going to run them all
2016-05-25 20:02:57> ApplyReleasesImpl: Starting fixPinnedExecutables
2016-05-25 20:02:57> ApplyReleasesImpl: Examining Pin: Internet Explorer (2).lnk
2016-05-25 20:02:57> ApplyReleasesImpl: Examining Pin: Internet Explorer (3).lnk
2016-05-25 20:02:57> ApplyReleasesImpl: Examining Pin: Internet Explorer.lnk
2016-05-25 20:02:57> ApplyReleasesImpl: Examining Pin: 猎豹安全浏览器.lnk
2016-05-25 20:02:57> ApplyReleasesImpl: Fixing up tray icons
2016-05-25 20:02:57> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__ee(RegistryView view)
2016-05-25 20:02:57> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__ee(RegistryView view)
2016-05-25 20:02:57> ApplyReleasesImpl: cleanDeadVersions: for version 0.0.136
2016-05-25 20:02:57> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.0.136
2016-05-25 20:03:03> InstallHelperImpl: Couldn't write uninstall icon, don't care: System.Net.WebException: Could not find a part of the path 'C:\Users\Dell\git\micloud-pc\app\logo.ico'. ---> System.Net.WebException: Could not find a part of the path 'C:\Users\Dell\git\micloud-pc\app\logo.ico'. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Dell\git\micloud-pc\app\logo.ico'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at System.Net.FileWebStream..ctor(FileWebRequest request, String path, FileMode mode, FileAccess access, FileShare sharing, Int32 length, Boolean async)
   at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)
   --- End of inner exception stack trace ---
   at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)
   at System.Net.FileWebRequest.GetResponseCallback(Object state)
   --- End of inner exception stack trace ---
   at System.Net.FileWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.InstallHelperImpl.<CreateUninstallerRegistryEntry>d__12b.MoveNext()
skAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Install>d__38.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.IO.IOException: The process cannot access the file 'C:\Users\liwenjing.xiaomi\AppData\Local\MiCloudPC\packages\MiCloudPC-0.0.136-full.nupkg' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at Squirrel.Utility.<DeleteDirectory>b__34(String file)
   at Squirrel.Utility.<>c__DisplayClass18`1.<>c__DisplayClass1a.<ForEachAsync>b__17()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<<DeleteDirectory>b__35>d__38.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass1e`1.<>c__DisplayClass20.<<ForEachAsync>b__1d>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<DeleteDirectory>d__3b.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__4d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Install>d__38.MoveNext()<---
```

**Comment by wangxiexe** [comment]
another thing I noticed is that in the log:

2016-05-25 20:03:03> InstallHelperImpl: Couldn't write uninstall icon, don't care: System.Net.WebException: Could not find a part of the path 'C:\Users\Dell\git\micloud-pc\app\logo.ico'. ---> System.Net.WebException: Could not find a part of the path 'C:\Users\Dell\git\micloud-pc\app\logo.ico'. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Dell\git\micloud-pc\app\logo.ico'.

the path "C:\Users\Dell\git\micloud-pc\app\logo.ico" only exists on the build machine, and why the installer check that path on the the machine that running the installer ?

**Comment by wangxiexe** [comment]
also, it does success on some windows 7 but failed on some as well.

**Comment by paulcbetts** [comment]
Not being able to write the staging ID will not cause the installation to fail

**Comment by wangxiexe** [comment]
But my user did see an error dialog read "Installation has failed" 

I used the electron-window-installer to create the installer.

        * [electron-windows-installer](https://github.com/electronjs/windows-installer#usage)

Is there anything I can do to avoid such issue ? thanks!

**Comment by paulcbetts** [comment]
Hm, can you try deleting the Squirrel log and rerunning it? You might be copy-pasting from a different installation - the log you provided shows several warnings but no failures

**Comment by wangxiexe** [comment]
what I did is put the Setup.exe, the Release file and the nupkg file on an http server and then send the setup.exe url to ask my user to download and setup. She showed me an installation error dialog and send my the full log.

I will ask her to try again and let you know the result. Thanks.

**Comment by wangxiexe** [comment]
she told me reinstall worked, will see if we can see this problem again, close for now.

**Comment by Shobanabohs100** [comment]
I have got the same issue while trying to install atom in Windows 64bit
I have no antivirus software installed. still having the same issue. Anyone's help will be much appreciated. 

2017-12-28 18:23:07> Program: Starting Squirrel Updater: --install .
2017-12-28 18:23:08> Program: Starting install, writing to C:\Users\user\AppData\Local\SquirrelTemp
2017-12-28 18:23:09> Program: About to install to: C:\Users\user\AppData\Local\GitHubDesktop
2017-12-28 18:23:10> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\user\AppData\Local\GitHubDesktop\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2017-12-28 18:23:10> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\user\AppData\Local\GitHubDesktop\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2017-12-28 18:23:10> CheckForUpdateImpl: Reading RELEASES file from C:\Users\user\AppData\Local\SquirrelTemp
2017-12-28 18:23:11> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2017-12-28 18:23:12> ApplyReleasesImpl: Writing files to app directory: C:\Users\user\AppData\Local\GitHubDesktop\app-1.0.11
2017-12-28 18:23:13> LogHost: Rigging execution stub for lib/net45/GitHubDesktop_ExecutionStub.exe to C:\Users\user\AppData\Local\GitHubDesktop\GitHubDesktop.exe
2017-12-28 18:23:31> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\user\AppData\Local\GitHubDesktop\app-1.0.11\GitHubDesktop.exe]
2017-12-28 18:23:43> ApplyReleasesImpl: Starting fixPinnedExecutables
2017-12-28 18:23:43> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2017-12-28 18:23:43> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2017-12-28 18:23:44> ApplyReleasesImpl: Fixing up tray icons
2017-12-28 18:23:44> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__13_0(RegistryView view)
2017-12-28 18:23:44> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__13_0(RegistryView view)
2017-12-28 18:23:44> ApplyReleasesImpl: cleanDeadVersions: for version 1.0.11
2017-12-28 18:23:44> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.0.11
2018-01-10 18:09:49> Program: Starting Squirrel Updater: --install .
2018-01-10 18:09:49> Program: Starting install, writing to C:\Users\user\AppData\Local\SquirrelTemp
2018-01-10 18:09:50> Program: About to install to: C:\Users\user\AppData\Local\Postman
2018-01-10 18:09:50> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\user\AppData\Local\Postman\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2018-01-10 18:09:50> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\user\AppData\Local\Postman\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2018-01-10 18:09:50> CheckForUpdateImpl: Reading RELEASES file from C:\Users\user\AppData\Local\SquirrelTemp
2018-01-10 18:09:51> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2018-01-10 18:09:51> ApplyReleasesImpl: Writing files to app directory: C:\Users\user\AppData\Local\Postman\app-5.5.0
2018-01-10 18:10:01> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\user\AppData\Local\Postman\app-5.5.0\Postman.exe]
2018-01-10 18:10:03> ApplyReleasesImpl: Starting fixPinnedExecutables
2018-01-10 18:10:03> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2018-01-10 18:10:03> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2018-01-10 18:10:03> ApplyReleasesImpl: Examining Pin: Opera Browser.lnk
2018-01-10 18:10:03> ApplyReleasesImpl: Fixing up tray icons
2018-01-10 18:10:03> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__13_0(RegistryView view)
2018-01-10 18:10:03> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__13_0(RegistryView view)
2018-01-10 18:10:03> ApplyReleasesImpl: cleanDeadVersions: for version 5.5.0
2018-01-10 18:10:03> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-5.5.0
2018-01-10 18:10:09> InstallHelperImpl: Couldn't write uninstall icon, don't care: System.Net.WebException: Could not find a part of the path 'C:\Users\Postman\buildkite-agent\builds\postman-ci-agent-windows-1\postman\electron-package-and-deploy\resources\postman-prod.ico'. ---> System.Net.WebException: Could not find a part of the path 'C:\Users\Postman\buildkite-agent\builds\postman-ci-agent-windows-1\postman\electron-package-and-deploy\resources\postman-prod.ico'. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Postman\buildkite-agent\builds\postman-ci-agent-windows-1\postman\electron-package-and-deploy\resources\postman-prod.ico'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.Net.FileWebStream..ctor(FileWebRequest request, String path, FileMode mode, FileAccess access, FileShare sharing, Int32 length, Boolean async)
   at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)
   --- End of inner exception stack trace ---
   at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)
   at System.Net.FileWebRequest.GetResponseCallback(Object state)
   --- End of inner exception stack trace ---

**Comment by paulcbetts** [comment]
@Shobanabohs100 This is an issue with the app you're trying to install ("Postman"?), they're Doing Something Wrong

**Comment by jozelo** [comment]
The same to me:
CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: No se puede encontrar una parte de la ruta de acceso 'C:\Users\jozel\AppData\Local\GitHubDesktop\packages\.betaId'.
   en System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

**Comment by by12291216** [comment]
CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException:

**Comment by rollsch** [comment]
I get this in windows 11 when installing discord.

**Comment by anaisbetts** [comment]
@rollsch Read the bottom of the file to look for errors, not the top :)

**Comment by ngohuytrieu** [comment]
My bottom of file is @anaisbetts 
`Filed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\myuser\AppData\Local\Figma\packages\RELEASES'.`

**Comment by secoldPrivate** [comment]
Yes,it appears to look at every electron app on the user's system and try to find the RELEASES folder of that electron app for some reaosn. That's why it always is showing things like Figma, Discord, postman etc.

**Comment by milanm** [comment]
The error persists with the latest version (1.5.0).
