### ISSUE TITLE
Sequence contains more than one matching element

### ISSUE THREAD

**Issue by nullif** [Squirrel/Squirrel.Windows#727]
Is there something I need to be doing to avoid this error?

```
System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Squirrel.Utility.FindCurrentVersion(IEnumerable`1 localReleases)
   at Squirrel.UpdateManager.CheckForUpdateImpl.determineUpdateInfo(IEnumerable`1 localReleases, IEnumerable`1 remoteReleases, Boolean ignoreDeltaUpdates)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__3f.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__50`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.EasyModeMixin.<UpdateApp>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

It happens consistently on many different devices.

Possibly related to #122. Let me know if you need more information.

**Comment by nullif** [comment]
It looks like it has downloaded the delta and the full version. This is why FindCurrentVersion is returning two entries. See version 1.0.38 below:

```
8DB7DCC8DDADC0343D97EDE92DB7F633251815FE <app-name>-1.0.14-delta.nupkg 149361
1DFD74E49FBCD02398B293FB3F67616751370921 <app-name>-1.0.14.nupkg 32720032
48151944C71380A7470FA93C75BE4B2274209B50 <app-name>-1.0.31-delta.nupkg 198514
0312048DA96EE64C8A3866B4657CE33D5D951228 <app-name>-1.0.31.nupkg 32722209
DBAF7C5CB2F486D2468F2236CBE78C20473C0E35 <app-name>-1.0.37-delta.nupkg 105441
5B7609A5A99CFC0AAAF05B43B7FDDD937B7C3CC0 <app-name>-1.0.37.nupkg 32722653
929F3C9B3DAAD23BD0BB58BDF824AE516E4E9BAD <app-name>-1.0.38-delta.nupkg 95086
0270C7BDBFAA679B524E7393165E6AC867F0A81C <app-name>-1.0.38.nupkg 32723265
2B056C5EABD95249BBC5947FEE7D1B5E63D4563F <app-name>-1.0.38-full.nupkg 32935452
```

**Comment by jeremy-bridges** [comment]
We get this same error. It happens to us when the RELEASES file gets out of sync with the NuGet packages that are on disk. For example, after our build server failed to write out the Setup.exe file for a couple builds (0.1.1.75 and 0.1.1.76), our RELEASES file looked like this:

02898A9F85CD9615657EE62D8281A2F8C3359062 OurApp-0.1.1.74-beta01-delta.nupkg 288257
3C2611974BE3421508836FCC343C742E98389207 OurApp-0.1.1.74-beta01-full.nupkg 29627625
11514B027011D8BA630383EB93523D7107402C88 OurApp-0.1.1.75-beta01-delta.nupkg 197317
C83FDCE0B0E33D15FB401D523DED429DDDFBFBDE OurApp-0.1.1.75-beta01-full.nupkg 29627633
274793FD857F13BC50E866C8001E44DAD3091BF8 OurApp-0.1.1.76-beta01-delta.nupkg 301729
28FE88AD129686EEF124D47AF3F0E1495CEB8CFC OurApp-0.1.1.76-beta01-full.nupkg 29628263
46578F073E785C20F8AD59E8793F457173F0EE6A OurApp-0.1.1.77-beta01-delta.nupkg 346642
27C96DB591E53282B71A1BECEF60BEFAAEF67D96 OurApp-0.1.1.77-beta01-full.nupkg 29624752

Notice that the failed builds are listed in the RELEASES file. However, on disk, those packages are not there. The output of the Releasify command that fails is:

Done Adding Additional Store
Successfully signed: C:\Users\build\AppData\Local\SquirrelTemp\tempb\lib\net45\OurApp.exe
System.IO.IOException: The process cannot access the file '\\build.repo\our-app\develop\Setup.exe' because it is being used by another process.
    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
    at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
    at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
    at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon, Boolean generateMsi)
    at Squirrel.Update.Program.executeCommandLine(String[] args)
    at Squirrel.Update.Program.main(String[] args)
    at Squirrel.Update.Program.Main(String[] args)

**Comment by nullif** [comment]
@paulcbetts This seems like quite a serious/urgent issue.
