### ISSUE TITLE
Running Setup.exe crashes

### ISSUE THREAD

**Issue by nullif** [Squirrel/Squirrel.Windows#731]
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Squirrel.UnsafeUtility.<>c__DisplayClass2.<EnumerateProcesses>b__0(Int32 i)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Squirrel.UnsafeUtility.EnumerateProcesses()
   at Squirrel.UpdateManager.InstallHelperImpl.KillAllProcessesBelongingToPackage()
   at Squirrel.Update.Program.<Install>d__38.MoveNext()
```

**Comment by michael-kindtner** [comment]
Have this issue, too. Seems PID over 2048 causes this.
