### ISSUE TITLE
Access denied error when installing squirrel app

### ISSUE THREAD

**Issue by btoda** [Squirrel/Squirrel.Windows#804]
Hi,
We keep getting this error from time to time while installing the app.
The de-DE folder in our app contains just a single dll file.
If feels a bit illogical, as if we can create the root folder why would we have no access to create the subfolders?

2016-04-22 09:28:31> IEnableLogger: Failed to install package to app dir: System.AggregateException: One or more errors occurred. ---> System.IO.IOException: Access to the path 'de-DE' is denied.
   at System.IO.DirectoryInfo.MoveTo(String destDirName)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass7_1.<installPackageToAppDir>b__4(DirectoryInfo subdir)
   at Squirrel.Utility.<>c__DisplayClass12_1`1.<ForEachAsync>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass7_2.<installPackageToAppDir>b__3(DirectoryInfo ld)
   at Squirrel.EnumerableExtensions.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass7_0.<<installPackageToAppDir>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext()
---> (Inner Exception #0) System.IO.IOException: Access to the path 'de-DE' is denied.
   at System.IO.DirectoryInfo.MoveTo(String destDirName)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass7_1.<installPackageToAppDir>b__4(DirectoryInfo subdir)
   at Squirrel.Utility.<>c__DisplayClass12_1`1.<ForEachAsync>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()<---

Any ideas why this could happen? Should we avoid subdirectories in our app?

**Comment by hatton** [comment]
Our customers are also getting this, very occasionally. They seem to eventually get it installed by retrying.  We have never been able to get ahold of one of these problem machines to investigate.

For what it's worth, I have been able to reproduce the symptom using https://github.com/hatton/FileMeddler, which agressively locks every file that is touched in a directory. This suggests that possibly some process on the customer computer is seeing the installation activity and touching files. One expects anti-virus to do that without locking. But we've seen some customers with three different anti-virus programs running.. maybe at some point they interfere?

We are considering making our squirrel instance robust to this kind of interference through retries.

**Comment by hvassbotn** [comment]
Are you guys on the latest version. Sounds like this
https://github.com/Squirrel/Squirrel.Windows/issues/698
Should be fixed in the latest version

**Comment by hatton** [comment]
@hvassbotn No, we're behind. Thanks for the pointer.

Just to update this thread: we were able to confirm that when the problem happens, it can be worked around by temporarily lowering Windows's UAC to the lowest level, or disabling the anti-virus. We decided to provide users with that troubleshooting info instead of adding automatic fileio retries.

**Comment by hvassbotn** [comment]
We just updated to 1.4.4 to fix this problem:
https://github.com/Squirrel/Squirrel.Windows/releases

It doesn't do retries, it just avoids moving files between folders by unpacking them to the correct folder in the first place.

**Comment by GabrielAPass** [comment]
This is a problem again in version 1.16.0 & 1.17.0 Beta.
It is summarized in this thread with SquirrlSetup.log files:
https://github.com/atom/atom/issues/13150
& sample log file
[SquirrelSetup.pdf](https://github.com/Squirrel/Squirrel.Windows/files/949886/SquirrelSetup.pdf)

In an attempt to pull together redundant / related posts of this issue since 1.16+, I found the following open issue reports.  These appear to all be the same:
- https://github.com/Squirrel/Squirrel.Windows/issues/775
- https://github.com/Squirrel/Squirrel.Windows/issues/804
- https://github.com/Squirrel/Squirrel.Windows/issues/848
- https://github.com/Squirrel/Squirrel.Windows/issues/876
