### ISSUE TITLE
Error Downloading Update: Command failed: 4294967295

### ISSUE THREAD

**Issue by lubov15911** [Squirrel/Squirrel.Windows#833]
I have an electron app (1.3.4) with the autoUpdater module which uses the Squirrel framework.

If I have not the latest version of app and I check for updates, app is updated to the latest version. But if I have the latest version of app and I try to check for updates, I get an error:

```
Error Downloading Update: Command failed: 4294967295
System.AggregateException: One or more errors occurred. ---> System.Exception: Remote release File is empty or corrupted
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<Download>d__7.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)
---> (Inner Exception #0) System.Exception: Remote release File is empty or corrupted
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<Download>d__7.MoveNext()<---
```

Why does app download nonexistent updates after checking for updates? I think should generate an 'update-not-available' event for this, don't try to download nonexistent updates.

**Comment by saenzramiro** [comment]
BUMP

**Comment by paulcbetts** [comment]
I think this is a bug in your program, can you double-check that you're not changing the update URL?

**Comment by lubov15911** [comment]
@paulcbetts  The update URL is right and the app works correctly with the latest version but this error appear only in a log-file. Does it ok that I get this error? Should I get an 'update-not-available' event?

**Comment by manikantag** [comment]
I m not sure about @lubov15911 scenario, but in my case I was returning `204` response when app is the latest version. Ideally server should return `RELEASES` response for the latest version of the even if the requesting app is the latest.

From Squirrel docs: (https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/update-process.md)

> **1. Check for Updates** - the RELEASES file at the distribution location is downloaded and compared to local RELEASES file to check for any updates.

The local `RELEASES` (which was kept in installation dir by Squirrel) is having latest version `nupkg` details.

As i m returning `204` response, Squirrel is thinking the `RELEASES` file got corrupted. Hope this helps someone.

**Comment by paulcbetts** [comment]
Returning a 204 doesn't make any sense, because the server doesn't know if the client is up-to-date, unlike Squirrel.Mac.

**Comment by manikantag** [comment]
> Returning a 204 doesn't make any sense, because the server doesn't know if the client is up-to-date, unlike Squirrel.Mac.

Correct. Now I m returning the latest version `RELEASES` all the times *(of course for that platform)*

**Comment by Thieum** [comment]
@lubov15911 does [this comment](https://github.com/Squirrel/Squirrel.Windows/issues/833#issuecomment-270119045) helped you resolve your issue? If so, you can close it.
