### ISSUE TITLE
Releasify throwing "System.AccessViolationException: Attempted to read or write protected memory" while creating the delta package

### ISSUE THREAD

**Issue by szanto90balazs** [Squirrel/Squirrel.Windows#844]
Every now and then we get this exception on our CI slave machines running `releasify`. It's non-deterministic, rerunning it pretty much helps. We're on 1.4.2. The only thing changed is that our CI machines are connected to a different Jenkins master, however it might not have nothing to do with it.

```
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at DeltaCompressionDotNet.MsDelta.NativeMethods.CreateDelta(FileTypeSet fileTypeSet, Int64 setFlags, Int64 resetFlags, String sourceName, String targetName, String sourceOptionsName, String targetOptionsName, DeltaInput globalOptions, IntPtr targetFileTime, HashAlgId hashAlgId, String deltaName)
   at DeltaCompressionDotNet.MsDelta.MsDeltaCompression.CreateDelta(String oldFilePath, String newFilePath, String deltaFilePath)
   at Squirrel.DeltaPackageBuilder.createDeltaForSingleFile(FileInfo targetFile, DirectoryInfo workingDirectory, Dictionary`2 baseFileListing)
   at Squirrel.DeltaPackageBuilder.CreateDeltaPackage(ReleasePackage basePackage, ReleasePackage newPackage, String outputFile)
   at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon, Boolean generateMsi)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)
```

**Comment by shiftkey** [comment]
@szanto90balazs is this something you've seen on a more recent version of Squirrel? #803 included an update to `DeltaCompressionDotNet` which went out in `1.7.0`, so I'm wondering if this has indirectly been addressed.

**Comment by szanto90balazs** [comment]
@shiftkey We used Squirrel.Windows up until May, 2018 (v1.7.9), so my memories are bit hazy, however I think we haven't experienced this one with newer versions. I think this issue can be closed.

**Comment by shiftkey** [comment]
@szanto90balazs excellent, feel free to revisit this if you spot anything else!
