### ISSUE TITLE
app folder is empty _._ 

### ISSUE THREAD

**Issue by reach2deep** [Squirrel/Squirrel.Windows#852]
Hi

am doing fresh installer using squirrel

when i run the setup.exe the app folder is empty with the file _._

but no errors in log file.

```
Local
--- GSMTest
       --- App-1.1.0
              ---  _._   // this folder is empty
       --- packages
       --- Update.exe
```

2016-10-14 15:13:00> Program: Starting Squirrel Updater: --install .
2016-10-14 15:13:00> Program: Starting install, writing to C:\Users\reach\AppData\Local\SquirrelTemp
2016-10-14 15:13:00> Program: About to install to: C:\Users\reach\AppData\Local\GSMTest
2016-10-14 15:13:00> Program: Install path C:\Users\reach\AppData\Local\GSMTest already exists, burning it to the ground
2016-10-14 15:13:01> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\reach\AppData\Local\GSMTest\packages.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2016-10-14 15:13:01> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\reach\AppData\Local\GSMTest\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2016-10-14 15:13:01> CheckForUpdateImpl: Reading RELEASES file from C:\Users\reach\AppData\Local\SquirrelTemp
2016-10-14 15:13:01> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2016-10-14 15:13:01> ApplyReleasesImpl: Writing files to app directory: C:\Users\reach\AppData\Local\GSMTest\app-1.1.0
2016-10-14 15:13:01> ApplyReleasesImpl: Squirrel Enabled Apps: []
2016-10-14 15:13:01> ApplyReleasesImpl: No apps are marked as Squirrel-aware! Going to run them all
2016-10-14 15:13:01> ApplyReleasesImpl: Starting fixPinnedExecutables
2016-10-14 15:13:01> ApplyReleasesImpl: Examining Pin: Control Panel.lnk
2016-10-14 15:13:01> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2016-10-14 15:13:01> ApplyReleasesImpl: Fixing up tray icons
2016-10-14 15:13:01> ApplyReleasesImpl: cleanDeadVersions: for version 1.1.0
2016-10-14 15:13:01> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.1.0

**Comment by agostinocinelli** [comment]
Did you put your application files in the lib/net45 folder of the nupkg? :-O

**Comment by Thieum** [comment]
@reach2deep did @agostinocinelli hint helped you fix your issue? If so, you can close this.
