### ISSUE TITLE
Crash when update server returns a 500 status response

### ISSUE THREAD

**Issue by skewart** [Squirrel/Squirrel.Windows#881]
I'm running an electron app, built with grunt-electron-installer v1.2.3, which uses Squirrel.Windows v1.2.5.  Maybe this problem wouldn't happen in newer versions.

Update.exe seems to crash and not start the Electron app if the update server returns a 500 status code response.  I would think it would handle these kinds of errors more gracefully.

Is this the intended behavior?  Or does this seem more like an application problem?

Here are logs from SquirrelSetup.log after a crash:

```
2016-11-23 09:37:32> CheckForUpdateImpl: Download resulted in WebException (returning blank release list): System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__50`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.FileDownloader.<DownloadUrl>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__3f.MoveNext()
```

**Comment by PierBover** [comment]
I'm getting the same problem. The electron app doesn't crash but a very ugly error is shown to the user.

![screenshot_1](https://cloud.githubusercontent.com/assets/226483/21855964/d7f59d58-d7e5-11e6-8d5d-1b6e52dc660c.jpg)

**Comment by skewart** [comment]
Bummer that you're running into a similar problem; though I'm kinda glad I'm not the only one.  

What version of Electron are you running?

**Comment by PierBover** [comment]
I'm using `1.3.5`.

I'm a bit afraid to update in case anything breaks with the build process...

**Comment by paulcbetts** [comment]
@pierbover when you call methods and they fail, they throw exceptions. You should catch those exceptions and do something appropriate

**Comment by PierBover** [comment]
@paulcbetts don't you think I'd do that if I could?

I can't catch a .NET exception from Node.

**Comment by paulcbetts** [comment]
Now I understand the confusion - you're calling checkForUpdates and it's throwing a JavaScript exception, the _message_ is the stderr text of Update.exe, which that text is a .NET stack trace. You can catch it!

**Comment by PierBover** [comment]
Something like this?

```
	try {
		autoUpdater.checkForUpdates();
	} catch (error) {
		console.log(error);
	}
```

**Comment by paulcbetts** [comment]
Looks like autoUpdate is rethrowing it or something. Try listening to the `error` event - https://github.com/electron/electron/blob/2b955a5ae12ca4b15f0c018243b99c78d5e79e40/docs/api/auto-updater.md#event-error

**Comment by PierBover** [comment]
Thanks @paulcbetts that was it.

I added:

```
	autoUpdater.on('error', error => {
		...
	});
```
