### ISSUE TITLE
Auto-Update GitHub releases download failure

### ISSUE THREAD

**Issue by afreeland** [Squirrel/Squirrel.Windows#944]
I am working with pulling updates from GitHub as opposed to a network share and ran into an issue pulling the RELEASES file. 

I originally had something along the lines of this, which works fine:
`Update.exe --update '\\MyNetwork\dist'`

I have created releases in Github that are structured like the following
- 0.0.2
-- MyApp-0.0.1-full.nupkg
-- MyApp-0.0.2-delta.nupkg
-- MyApp-0.0.2-full.nupkg
-- RELEASES
-- Setup.exe
-- Setup.msi
-- Source Code (zip)
-- Source Code (tar.gz)

- 0.0.1
-- MyApp-0.0.1-full.nupkg
-- RELEASES
-- Setup.exe
-- Setup.msi
-- Source Code (zip)
-- Source Code (tar.gz)

Was reading through the [UpdateManager.Factory](https://github.com/Squirrel/Squirrel.Windows/blob/master/src/Squirrel/UpdateManager.Factory.cs) and seen where it essentially just pulled the latest release and grabbed the `html_url` from the GitHub API response.  Then it rewrites `/tag` with `/download` and then feeds that back into the Update Manager and slaps on the access_token.

Armed with that knowledge I tried running the Update.exe like this:
`Update.exe --update 'https://github.com/{User}/{Repo}/releases/download/0.0.2?access_token={access_token}'`

Which when looking through the `SquirrelSetup.log` file I shows the following error:
```
2017-02-03 09:01:16> CheckForUpdateImpl: Using existing staging user ID: 7edd3044-32e7-5fd3-9068-5ce586c09446
2017-02-03 09:01:16> CheckForUpdateImpl: Downloading RELEASES file from https://github.com/{User}/{Repo}/releases/download/0.0.2?access_token={access_token}
2017-02-03 09:01:16> FileDownloader: Downloading url: https://github.com/{User}/{Repo}/releases/download/0.0.2/RELEASES?access_token={access_token}&id={app_name}&localVersion=0.0.1&arch=amd64
2017-02-03 09:01:17> IEnableLogger: Failed to download url: https://github.com/{User}/{Repo}/releases/download/0.0.2/RELEASES?access_token={access_token}&id={app_name}&localVersion=0.0.1&arch=amd64: System.Net.WebException: The request was aborted: The connection was closed unexpectedly.
   at System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.HttpWebRequest.MakeMemoryStream(Stream stream)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__36`1.MoveNext()
```

[More Verbose Version](https://gist.github.com/afreeland/29460fd2a2138843dba606a65c9a678a)

It looks like it has an issue downloading the RELEASES file but whenever I hit it with postman or from the browser I am able to download the file without any issues.

Trying to determine if this is an issue within the Update.exe or something in my project structure? Any help or direction would be greatly appreciated =)

I should also mention this is a private repo, not sure if that matters since the access_token is getting passed with it as well.

**Comment by afreeland** [comment]
Decided on going with a local network share and not sure that this was the best approach anyhow.
