### ISSUE TITLE
CheckForUpdate fails with "The request was aborted: The connection was closed unexpectedly."

### ISSUE THREAD

**Issue by phw198** [Squirrel/Squirrel.Windows#995]
Hi,
I'm wanting to port my CodePlex project over to github and move from ClickOnce to Squirrel. I'm just playing around at the moment, but I have released/tagged v2.5.0-beta and uploaded the Squirrel release files as artifacts for that release. 

However, when I then try and use the UpdateManager to check for updates and install the Squirrel version, it just fails with "The request was aborted: The connection was closed unexpectedly."
```
using (var updateManager = new UpdateManager("https://github.com/phw198/OutlookGoogleCalendarSync/releases/latest")) {
//using (UpdateManager updateManager = new UpdateManager("C:\\Development\\git\\outlookgooglecalendarsync\\Releases")) {
      UpdateInfo info = await updateManager.CheckForUpdate();
}
```
If I instead use the commented out line to point to the local files, it all works exactly as expected. Note, I'm running this in VS debugger, so it's not a Squirrel install yet. What am I doing wrong?

Thanks!

**Comment by phw198** [comment]
Running Update.exe on the command line also produces this log file:

> Update.exe --checkForUpdate 'https://github.com/phw198/OutlookGoogleCalendarSync/releases/latest'
```
2017-04-09 23:47:28> Program: Starting Squirrel Updater: --checkForUpdate 'https://github.com/phw198/OutlookGoogleCalendarSync/releases/latest'
2017-04-09 23:47:28> Program: Fetching update information, downloading from 'https://github.com/phw198/OutlookGoogleCalendarSync/releases/latest'
2017-04-09 23:47:28> CheckForUpdateImpl: Generated new staging user ID: d76c1580-3898-5eb3-a5f4-58ea30570c2f
2017-04-09 23:47:28> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.FileNotFoundException: Could not find file 'C:\Development\git\outlookgooglecalendarsync\OutlookGoogleCalendarSync\packages\RELEASES'.
File name: 'C:\Development\git\outlookgooglecalendarsync\OutlookGoogleCalendarSync\packages\RELEASES'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2017-04-09 23:47:28> CheckForUpdateImpl: Reading RELEASES file from 'https://github.com/phw198/OutlookGoogleCalendarSync/releases/latest'
2017-04-09 23:47:28> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.Exception: The directory 'https://github.com/phw198/OutlookGoogleCalendarSync/releases/latest' does not exist, something is probably broken with your application
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.Exception: The directory 'https://github.com/phw198/OutlookGoogleCalendarSync/releases/latest' does not exist, something is probably broken with your application
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()<---
```

**Comment by phw198** [comment]
Finally realised I needed to use the `GitHubUpdateManager` method and not specify the "/release/latest". For synchronous checking, this is now working:
```
var updateManager = UpdateManager.GitHubUpdateManager("https://github.com/phw198/OutlookGoogleCalendarSync");
UpdateInfo info = updateManager.Result.CheckForUpdate().Result;
```
